export const depth = {
  'SL 5.1': {
    skills: ['Compute secant gradients over shrinking intervals.', 'Interpret a derivative as a local rate of change.', 'Read derivative information from a graph without assuming every point is smooth.'],
    why: 'A secant compares two distinct points; a tangent gradient arises as their separation tends to zero. The limiting process explains why the derivative at a point can describe instantaneous speed despite using nearby changes. A sharp corner can have left and right secant slopes that approach different numbers, so its derivative does not exist there.',
    edge: 'For $f(x)=x^2$, the secant gradient from $x=2$ to $x=2+h$ is $[(2+h)^2-4]/h=4+h$ when $h\\neq0$. As $h\\to0$, this tends to $4$, the tangent gradient. It would be invalid to set $h=0$ in the original fraction before simplifying because that denominator would vanish.',
    connection: 'Rates have units of output per input, such as metres per second. A negative derivative means decreasing output, not a negative amount of elapsed time. Compare a local derivative with an average rate on a broader interval to avoid conflating instant and interval behavior.',
  },
  'SL 5.2': {
    skills: ['Find intervals where a function increases or decreases from $f\u0027(x)$.', 'Locate stationary candidates and test derivative signs around them.', 'Distinguish a flat inflection from a maximum or minimum.'],
    why: 'A positive derivative indicates local increase and a negative derivative local decrease where differentiability holds. At a stationary point $f\u0027=0$, the sign can switch from positive to negative, negative to positive, or not switch at all. Therefore solving $f\u0027=0$ produces candidates, not a classification by itself.',
    edge: 'For $f(x)=x^3$, $f\u0027(x)=3x^2\\geq0$, and the only stationary point is $x=0$. The derivative is positive on both sides, so the origin is not a local maximum or minimum. For $g(x)=-x^2$, $g\u0027=-2x$ changes from positive to negative at zero, giving a local maximum.',
    connection: 'If the domain is a closed interval, endpoint values can be global extrema even without vanishing derivative. Sketch the derivative sign chart and refer back to the original function when reporting coordinates. Do not assume that zero derivative implies zero function value.',
  },
  'SL 5.3': {
    skills: ['Differentiate integer powers, including negative powers on their domains.', 'Combine constant, sum and power rules.', 'Evaluate a derivative at a specified coordinate and interpret its unit.'],
    why: 'The power rule replaces $x^n$ by $nx^{n-1}$ for integer $n$ wherever the original function is differentiable. A negative exponent represents a reciprocal and excludes $x=0$. Differentiation acts term by term on a polynomial sum; a constant derivative is zero because its local change is always zero.',
    edge: 'For $f(x)=4x^3-3x^{-2}+7$, $f\u0027(x)=12x^2+6x^{-3}$ for $x\\neq0$. At $x=1$, the gradient is $18$. At $x=0$, neither the reciprocal term nor the derivative exists, so an algebraic expression that contains negative powers must carry its domain.',
    connection: 'Check the result by differentiating a simple antiderivative in reverse or by comparing a small numerical secant near a permitted point. When a time-dependent function is a position, the derivative is velocity rather than another position. State whether a requested answer is a function or one evaluated number.',
  },
  'SL 5.4': {
    skills: ['Locate the point on the curve before forming a tangent.', 'Find a normal with negative reciprocal gradient when appropriate.', 'Handle horizontal tangents and vertical normals as separate cases.'],
    why: 'A tangent line matches the curve’s first-order direction at the contact point. The normal is perpendicular to that tangent, so its gradient is $-1/m$ only when the tangent gradient $m$ is nonzero and finite. A horizontal tangent has a vertical normal, which cannot be expressed as $y=mx+c$.',
    edge: 'For $y=x^2$ at $x=-2$, the point is $(-2,4)$ and tangent gradient is $2x=-4$. Hence the tangent is $y-4=-4(x+2)$; the normal is $y-4=\\tfrac14(x+2)$. Substituting $(-2,4)$ checks both lines, and their gradients multiply to $-1$.',
    connection: 'Do not substitute the $x$-coordinate into the derivative and mistake the resulting gradient for the $y$-coordinate. In a context, the tangent approximates nearby output values, whereas the normal is a geometric construction. State the contact point explicitly in the final equations.',
  },
  'SL 5.5': {
    skills: ['Read an integral as accumulated signed change.', 'Find elementary antiderivatives with constants.', 'Separate area above and below the axis when physical area is required.'],
    why: 'An antiderivative reverses differentiation up to an additive constant. A definite integral accumulates signed contributions: below-axis regions subtract instead of adding. Geometric area is nonnegative, so a curve that crosses the axis requires splitting at its zeroes and taking magnitudes for each interval. An integral of a positive function needs no such adjustment.',
    edge: 'The integral $\\int_{-1}^{1}x\\,dx=0$ because the negative area on $[-1,0]$ cancels the positive area on $[0,1]$. Total geometric area is $\\int_{-1}^{0}(-x)\\,dx+\\int_0^1x\\,dx=1$. Reporting zero as the enclosed area would confuse signed accumulation with extent.',
    connection: 'A definite integral has units equal to the product of integrand and horizontal-axis units. Verify an antiderivative by differentiation and include $C$ only for indefinite integrals. If a graph is given without a formula, signed areas of simple shapes can still evaluate the integral exactly.',
  },
  'SL 5.6': {
    skills: ['Use the chain rule for nested functions.', 'Differentiate rational powers while respecting the original domain and endpoint.', 'Differentiate products without multiplying out unnecessarily.', 'Apply the quotient rule with a squared denominator and domain exclusions.', 'Differentiate standard trig, exponential and log expressions.'],
    why: 'The chain rule tracks how an outer output changes when its inner input changes. The product rule comes from changes in both factors, so differentiating each factor and multiplying the results is not valid. For a quotient, the denominator changes as well; keep its square intact and state where the quotient was originally defined.',
    edge: 'For $f(x)=(x^2+1)^3$, $f\u0027(x)=3(x^2+1)^2(2x)$. For $g(x)=x^2e^x$, $g\u0027=e^x(2x+x^2)$. For $h(x)=x/(x+1)$, $h\u0027=[(x+1)-x]/(x+1)^2=1/(x+1)^2$ for $x\\neq-1$. Each expression requires a different structural rule.',
    connection: 'Identify the outermost operation before differentiating: nesting, multiplication or division. Sometimes simplifying first turns a quotient into an easier sum, but never erase an original excluded value. Numerically compare the derivative at a safe point with a small secant to detect a missing inner derivative.',
  },
  'SL 5.7': {
    skills: ['Differentiate twice with consistent notation.', 'Use $f\u0027\u0027$ to analyze concavity where its sign is known.', 'Identify when an inflection test needs a sign change, not merely a zero.'],
    why: 'The second derivative measures how the first derivative changes. A positive second derivative corresponds to a rising gradient and upward concavity; a negative one to a falling gradient. An inflection point changes concavity. Solving $f\u0027\u0027=0$ only finds candidates, since a zero can occur without a sign change.',
    edge: 'For $f(x)=x^4$, $f\u0027\u0027(x)=12x^2$ is zero at $0$ but positive on both sides, so $(0,0)$ is not an inflection. For $g(x)=x^3$, $g\u0027\u0027(x)=6x$ changes sign at $0$, giving an inflection. Both functions have a horizontal tangent there, showing why one derivative condition is insufficient.',
    connection: 'In motion, position differentiated twice gives acceleration, with units of distance per time squared. Concavity on a graph is a mathematical shape statement, not necessarily a physical acceleration unless the horizontal variable is time and the vertical variable is position.',
  },
  'SL 5.8': {
    skills: ['Classify stationary points by signs or the second derivative.', 'Express an applied constraint as a one-variable objective.', 'Check endpoints and possible inflections before claiming global optimality.'],
    why: 'Differentiation finds stationary candidates, but optimization needs a feasible interval and a comparison with its boundaries. A negative second derivative at a candidate supports a local maximum; it does not alone prove it beats every endpoint. An inflection demands a change in concavity, not just a horizontal tangent or a zero second derivative.',
    edge: 'For a rectangle with perimeter $20$, let one side be $x$ and the other $10-x$ for $0\\leq x\\leq10$. Area $A=10x-x^2$ has $A\u0027=10-2x$, so $x=5$ and area $25$. Endpoint areas are zero and $A\u0027\u0027=-2<0$, confirming the global maximum on the feasible interval.',
    connection: 'Label the optimized quantity and its units before computing a derivative. If the physical model excludes zero lengths, the endpoints may be limiting boundary cases rather than attainable designs. Explain what your numerical optimum means in the original context, including any rounding to whole units.',
  },
  'SL 5.9': {
    skills: ['Differentiate position to velocity and velocity to acceleration.', 'Integrate velocity for displacement with correct bounds.', 'Find total distance by splitting at velocity sign changes.'],
    why: 'Displacement can be negative because it records final position minus initial position; distance traveled sums all movement irrespective of direction. The supplied 2023 booklet explicitly writes distance as the integral of $|v(t)|$, not of $v(t)$. PDF text extraction can drop the absolute-value bars, so check the visually printed formula when quoting it.',
    edge: 'If $v(t)=t-1$ for $0\\leq t\\leq2$, displacement is $\\int_0^2(t-1)\\,dt=0$. The particle moves one-half unit backward from $0$ to $1$ and one-half forward from $1$ to $2$, so total distance is $\\int_0^2|t-1|\\,dt=1$. Acceleration is the constant $1$.',
    connection: 'Draw a velocity sign chart before integrating for distance. A turning point in motion occurs when velocity changes sign, not merely when acceleration vanishes. Keep time units and position units distinct and report whether you computed a signed displacement, absolute distance, velocity or acceleration.',
  },
  'SL 5.10': {
    skills: ['Use power antiderivatives and standard log or trig integrals.', 'Spot a reverse-chain pattern by inspecting the inner derivative.', 'Make a substitution and adjust definite bounds when needed.'],
    why: 'Indefinite integration finds a family of functions that differ by a constant. For a composite form, substitution replaces the inner expression by a new variable and its derivative by the corresponding differential. When no inner derivative is present, a constant adjustment may help, but a guessed substitution cannot justify inventing an $x$ factor.',
    edge: 'For $\\int 6x(x^2+1)^2\\,dx$, let $u=x^2+1$, so $du=2x\\,dx$ and the integral becomes $3\\int u^2\\,du=u^3+C=(x^2+1)^3+C$. Differentiating gives $3(x^2+1)^2(2x)$, returning the original integrand.',
    connection: 'The formula $\\int1/x\\,dx=\\ln|x|+C$ applies separately on intervals not crossing zero. If the integral has limits, replace old endpoints with new $u$ values or convert the antiderivative back before evaluation. Do not leave a mix of $u$ and $x$ in the final expression. Constants can differ on disconnected intervals separated by a singularity, so name the interval on which your antiderivative applies.',
  },
  'SL 5.11': {
    skills: ['Use the fundamental theorem with correctly ordered limits.', 'Partition a signed integral at any axis crossings.', 'Integrate upper minus lower for the area between curves.'],
    why: 'The fundamental theorem turns a definite integral into antiderivative values at its bounds. Reversing the limits reverses its sign, but geometric area should remain nonnegative. When finding an enclosed region between curves, solve their intersections first and determine which is above on each interval; the order may switch.',
    edge: 'Between $y=x$ and $y=x^2$ on $0\\leq x\\leq1$, the line lies above the parabola, so area is $\\int_0^1(x-x^2)\\,dx=[x^2/2-x^3/3]_0^1=1/6$. Reversing the integrand would give $-1/6$, an invalid geometric area even though the signed integral is well-defined.',
    connection: 'A sketch prevents integrating the wrong top curve. If two graphs cross inside a larger interval, split the calculation at every crossing before applying an absolute value. Keep exact fractions or multiples of $\\pi$ when appropriate and add squared units for area.',
  },
  'AHL 5.12': {
    skills: ['Evaluate a derivative with a difference quotient and limit.', 'Compare second and higher derivatives.', 'Recognize nondifferentiable corners by unequal one-sided gradients.'],
    why: 'First principles requires a limit of a quotient with nonzero increment, followed only then by $h\\to0$. A formula such as the power rule is convenient, but the quotient explains why it works and what can fail at a corner. Higher derivatives describe repeated changes; each differentiation may shorten a polynomial until it reaches zero.',
    edge: 'For $f(x)=x^2+3x$, $[f(x+h)-f(x)]/h=(2xh+h^2+3h)/h=2x+h+3$ for $h\\neq0$, giving $f\u0027(x)=2x+3$. Differentiating again yields $f\u0027\u0027=2$. By contrast, $|x|$ has left gradient $-1$ and right gradient $1$ at zero, so the same limit does not exist there.',
    connection: 'A derivative from a graph may be one-sided at an endpoint but not a two-sided derivative on an open neighborhood. Keep the assumption of differentiability visible before invoking rules that require it. Use dimensions to check that a second derivative has output units per squared input unit.',
  },
  'AHL 5.13': {
    skills: ['Use factorization or rationalization before a limit.', 'Apply L’Hôpital only to valid $0/0$ or $\\infty/\\infty$ forms.', 'Compare leading powers at infinity and verify results independently.'],
    why: 'A limit describes approaching an input, not necessarily the value at that input. Removable algebraic factors can be canceled for nearby values while the function remains undefined at the center. L’Hôpital replaces a ratio by a ratio of derivatives only under its stated differentiability and indeterminate-form conditions; it is not a rule for arbitrary fractions.',
    edge: 'For $\\lim_{x\\to2}(x^2-4)/(x-2)$, the original quotient is $0/0$ at $2$. Factor to get $x+2$ for $x\\neq2$, so the limit is $4$. L’Hôpital also gives $\\lim 2x/1=4$ under its hypotheses. The limit exists even though the original expression has a hole at $2$.',
    connection: 'When a quotient tends to a nonzero number over zero, expect infinite or one-sided behavior rather than applying L’Hôpital automatically. A graph can suggest behavior but miss a removable hole. For limits at infinity, divide by the largest power and inspect whether the numerator and denominator have compatible degrees.',
  },
  'AHL 5.14': {
    skills: ['Differentiate an equation in $x$ and $y$ implicitly.', 'Use related rates by differentiating quantities with respect to time.', 'Check which physical dimensions remain constant in an optimization model.'],
    why: 'Implicit differentiation treats $y$ as a function of $x$, so differentiating $y^2$ gives $2y\\,dy/dx$ by the chain rule. Related rates adds a second independent variable, usually time: a changing radius, volume and height need rates tied by a geometric equation. Differentiate before inserting a special measured instant.',
    edge: 'For the circle $x^2+y^2=25$, differentiate to obtain $2x+2y\\,dy/dx=0$, hence $dy/dx=-x/y$ when $y\\neq0$. At $(3,4)$ the tangent gradient is $-3/4$. At $(5,0)$ that formula divides by zero, matching a vertical tangent rather than a finite gradient.',
    connection: 'In a rate problem, attach units per time to derivatives such as $dr/dt$. A diagram helps identify constant lengths and quantities that vary together. State a domain or sign condition before extracting square roots; a geometric radius is nonnegative even when algebra offers both signs.',
  },
  'AHL 5.15': {
    skills: ['Differentiate tangent, reciprocal trig, inverse trig or $a^x$.', 'Use a matching standard antiderivative with its domain.', 'Apply the chain rule to the argument of an unfamiliar standard form.'],
    why: 'Standard derivatives and integrals are pairs only after their constants and domains are accounted for. For $a^x$ the derivative includes $\\ln a$; for $\\log_a x$ the derivative includes $1/\\ln a$. Inverse-trig derivatives carry square-root or quadratic denominator restrictions, so the formula is not a license to evaluate outside a real domain.',
    edge: 'If $f(x)=3^x$, then $f\u0027(x)=3^x\\ln3$. An antiderivative of $3^x$ is $3^x/\\ln3+C$. For $g(x)=\\arctan(2x)$, the derivative is $2/(1+4x^2)$ by the chain rule, not $1/(1+4x^2)$. Differentiating a proposed antiderivative is an efficient check.',
    connection: 'The supplied booklet lists some further derivatives on printed page 9 and some antiderivatives on printed page 10. A student must still identify which expression matches a listed pattern and apply chain factors correctly. When formulas differ by absolute values or domain bounds, respect the original real domain.',
  },
  'AHL 5.16': {
    skills: ['Choose a substitution that simplifies a composite integrand.', 'Use integration by parts with a deliberate $u$ choice.', 'Repeat parts or recognize a cycle without discarding constants.'],
    why: 'Substitution reverses the chain rule; parts reverses the product rule. Neither is automatically the best method for every complicated expression. For parts, selecting $u$ to become simpler on differentiation often reduces the integral. In a repeating integral, move the returned integral to the other side before dividing; skipping that step loses a factor.',
    edge: 'For $\\int x e^x\\,dx$, take $u=x$, $dv=e^x\\,dx$, so $du=dx$ and $v=e^x$. Parts gives $xe^x-\\int e^x\\,dx=e^x(x-1)+C$. Differentiating $e^x(x-1)$ returns $xe^x$. With a definite integral, evaluate the boundary term and remaining integral over the same limits.',
    connection: 'A rational integrand may be better handled by partial fractions from Topic 1 before integrating. For a substituted definite integral, transform both endpoints or change back to the original variable consistently. Keep an eye on excluded values where a simplification or logarithm changes domain.',
  },
  'AHL 5.17': {
    skills: ['Integrate $x$ with respect to $y$ for a horizontal area slice.', 'Set up disc or washer volumes about either axis.', 'Check whether a region changes boundary curves along the interval.'],
    why: 'A horizontal slice has width right minus left and thickness $dy$; a vertical slice uses upper minus lower with $dx$. Rotating a slice creates a disc or washer whose cross-sectional area uses the square of its radius. The axis of revolution decides whether radius is described by $x$ or $y$, and a hollow center requires subtracting an inner squared radius.',
    edge: 'The region $0\\leq y\\leq2$ and $0\\leq x\\leq y$ has area $\\int_0^2y\\,dy=2$. Rotating it about the $y$-axis creates discs of radius $y$, so volume is $\\pi\\int_0^2 y^2\\,dy=8\\pi/3$. Integrating $y$ without squaring would compute a different geometric quantity.',
    connection: 'Draw one representative slice perpendicular to the rotation axis before writing limits. Use positive cross-sectional area, even if an algebraic radius expression can be negative outside the actual region. Add square units for planar area and cubic units for volume.',
  },
  'AHL 5.18': {
    skills: ['Approximate an initial-value problem with Euler steps.', 'Separate variables and integrate both sides when possible.', 'Use an integrating factor for a first-order linear equation.'],
    why: 'Euler’s method replaces a curved solution locally by a tangent segment, so its step size controls approximation error rather than changing the differential equation. Separable equations move all $y$-terms to one side and $x$-terms to the other. A linear equation $y\u0027+P(x)y=Q(x)$ instead admits integrating factor $e^{\\int P(x)dx}$ under appropriate conditions.',
    edge: 'For $y\u0027=y$, $y(0)=1$ and $h=0.1$, Euler gives $y_1=1+0.1(1)=1.1$ and $y_2=1.1+0.1(1.1)=1.21$. The exact separable solution is $y=e^x$, so $y(0.2)\\approx1.2214$. The Euler estimate is slightly low here; it is not an exact evaluation of $e^{0.2}$.',
    connection: 'Initial conditions choose one solution from a family and must be applied after integration. A constant equilibrium solution can disappear if variables are separated by dividing by zero, so check it separately. Show an Euler table of $(x_n,y_n,f(x_n,y_n))$ to expose a mistaken slope or step.',
  },
  'AHL 5.19': {
    skills: ['Build a Maclaurin polynomial from derivatives at zero.', 'Use known exponential, trigonometric and logarithmic expansions.', 'State where a power series is valid and control truncation error.'],
    why: 'A Maclaurin series encodes local behavior through successive derivatives at zero, dividing the $n$th derivative by $n!$. A finite truncation approximates a function near the center; it is not generally equal to the original function everywhere. Some printed expansions have restricted convergence, so a formula cannot be extended to an arbitrary argument without checking.',
    edge: 'The first terms of $e^x$ are $1+x+x^2/2+x^3/6$. At $x=0.1$ the cubic approximation is $1.105166\\ldots$, close to $e^{0.1}\\approx1.105171$. For $\\ln(1+x)$ the alternating series $x-x^2/2+x^3/3-\\cdots$ starts from $|x|<1$ as a safe convergence interval; a numerical substitution such as $x=3$ is not justified by that series.',
    connection: 'When combining series, keep only terms through the requested order and include an appropriate remainder symbol. A coefficient question may be easier by multiplying short truncations than by differentiating a complicated composite repeatedly. Check at $x=0$ that the constant term matches the original function.',
  },
};
