export const depth = {
  'SL 3.1': {
    skills: ['Find three-dimensional lengths and midpoints with coordinates.', 'Use right-triangle sections of solids to locate hidden distances.', 'Choose volume or surface-area formulas that match the shape and dimensions.'],
    why: 'A three-dimensional distance combines three perpendicular coordinate differences by applying Pythagoras twice. Drawing an appropriate cross-section turns an unfamiliar solid into a familiar right triangle. For volume, distinguish height perpendicular to the base from a sloping edge; replacing one by the other gives a systematically wrong answer.',
    edge: 'Points $(1,2,3)$ and $(4,6,15)$ are $\\sqrt{3^2+4^2+12^2}=13$ units apart. Their midpoint is $(5/2,4,9)$; check that the coordinate changes from the midpoint to either endpoint are opposites. For a right pyramid with base area $24$ and height $6$, volume is $24(6)/3=48$, not $144$.',
    connection: 'Attach units to lengths, square units to areas and cubic units to volumes. If a problem supplies a diagram, label the actual perpendicular height before using a formula booklet entry. Coordinate answers should remain exact when possible; round only when a physical measurement requires it.',
  },
  'SL 3.2': {
    skills: ['Use right-triangle sine, cosine and tangent with a consistent angle convention.', 'Select sine or cosine rule for non-right triangles.', 'Find triangle area from two sides and the included angle.'],
    why: 'The sine rule connects each side to its opposite angle, while the cosine rule handles an included angle and two sides or all three sides. These are not interchangeable data patterns. When solving an angle with inverse sine, another angle may have the same sine; triangle angle sum and side ordering decide whether an ambiguous second triangle is possible.',
    edge: 'With sides $a=5$, $b=7$ and included angle $C=60^\\circ$, the cosine rule gives $c^2=25+49-70(1/2)=39$, so $c=\\sqrt{39}$. The same data give area $\\tfrac12(5)(7)\\sin60^\\circ=35\\sqrt3/4$. Using $60^\\circ$ opposite side $5$ in the sine rule would mislabel the diagram.',
    connection: 'Set the calculator to the units used by the question, degrees or radians. Draw a rough triangle and check that the longest side faces the largest angle. For a right triangle the general rules still hold, but a direct right-triangle ratio is usually simpler.',
  },
  'SL 3.3': {
    skills: ['Model heights and horizontal distances from elevation or depression angles.', 'Translate a compass bearing into a clear diagram.', 'Combine two sight lines using triangle rules and realistic units.'],
    why: 'An angle of elevation is measured above a horizontal line at the observer, not from a vertical mast. Bearings are measured clockwise from north and require a direction reference at each location. A sketch with horizontal and vertical axes makes a right triangle visible before any trigonometric calculation.',
    edge: 'A tower subtends an elevation angle of $45^\\circ$ from a point $20$ metres from its base on level ground. Its height is $20\\tan45^\\circ=20$ metres. If the observer stands on a $2$ metre platform, the tower top is $22$ metres above ground, not $20$; the trig calculation found only the difference in heights.',
    connection: 'A practical answer depends on the modeled ground being level and the observation points being correct. When two sightings are provided, keep a single diagram with the same north arrow or baseline. Round a final distance to the requested precision and check that it is compatible with the geometry.',
  },
  'SL 3.4': {
    skills: ['Convert degrees to radians and back.', 'Find arc length, sector area and perimeter using radians.', 'Determine an angle from a measured arc or area without mixing units.'],
    why: 'A radian is defined by an arc length equal to the radius. Consequently, an angle $\\theta$ in radians measures arc-to-radius ratio and gives $s=r\\theta$. Sector area follows by taking the same fraction of a full circle. Both formulas require radians as input; a bare degree measure must be converted before substitution.',
    edge: 'For radius $6$ and angle $\\pi/3$, arc length is $2\\pi$ and sector area is $\\tfrac12(36)(\\pi/3)=6\\pi$. Sector perimeter is $12+2\\pi$, because two radii must be included. Using $60$ directly in the radian formula would overstate the answer dramatically.',
    connection: 'The central angle can exceed $2\\pi$ when modeling multiple revolutions, but a conventional single sector usually uses one full turn or less. Draw and label the radii to distinguish the curved boundary from the whole perimeter. Attach linear or squared units appropriately.',
  },
  'SL 3.5': {
    skills: ['Locate standard angles and exact sine and cosine coordinates.', 'Use quadrant signs and reference angles.', 'Relate tangent to sine over cosine when cosine is nonzero.'],
    why: 'On the unit circle the point at angle $\\theta$ is $(\\cos\\theta,\\sin\\theta)$. Angles differing by a full revolution reach the same point. The reference angle supplies magnitude; the quadrant supplies signs. Tangent is a ratio of these coordinates, so it is undefined where the cosine coordinate vanishes.',
    edge: 'At $5\\pi/6$, the reference angle is $\\pi/6$ in quadrant II. Thus $\\cos(5\\pi/6)=-\\sqrt3/2$, $\\sin(5\\pi/6)=1/2$, and $\\tan(5\\pi/6)=-1/\\sqrt3$. This is a sign check, not a calculator approximation. At $\\pi/2$, tangent has no finite real value.',
    connection: 'Use exact values to verify a calculator set to radians. When solving a trigonometric equation, an inverse function often supplies only a principal angle, not every angle in the required interval. Sketch the unit circle and add complete periods to enumerate the other candidates.',
  },
  'SL 3.6': {
    skills: ['Derive or apply $\\sin^2x+\\cos^2x=1$.', 'Switch among three equivalent forms of $\\cos2x$.', 'Prove an identity on a domain where every division is defined.'],
    why: 'The Pythagorean identity is the coordinate equation of the unit circle. Double-angle identities follow from compound-angle formulas and can be rewritten using the same Pythagorean relation. Choose the form that leaves one trigonometric function to solve for; do not divide by a function that can be zero without excluding those values.',
    edge: 'If $\\cos x=3/5$ and $x$ is in quadrant IV, $\\sin x=-4/5$. Hence $\\sin2x=2(3/5)(-4/5)=-24/25$ and $\\cos2x=2(3/5)^2-1=-7/25$. The interval information determined the sine sign; square roots alone would not.',
    connection: 'To prove an identity, work from one side toward the other while stating any denominator restrictions. Verifying it at a few angles is a check but not a proof. If an equation is created from an identity, substitute final roots in the original equation, especially after squaring.',
  },
  'SL 3.7': {
    skills: ['Identify amplitude, midline and period of a sinusoidal graph.', 'Explain horizontal and vertical phase shifts.', 'Model a repeated phenomenon only within sensible contextual bounds.'],
    why: 'For $a\\sin(b(x-c))+d$, the magnitude $|a|$ is amplitude, $2\\pi/|b|$ is period when $b\\neq0$, and $d$ is the midline. The sign of $a$ changes orientation. A phase shift alters where a cycle starts, not its height or duration. Domains can restrict how many peaks are relevant.',
    edge: 'The graph $y=2\\cos(3x)+1$ oscillates between $-1$ and $3$, about midline $1$, with period $2\\pi/3$. At $x=0$ it begins at a maximum of $3$. A proposed amplitude of $3$ confuses the upper value with its distance from the midline.',
    connection: 'If a model predicts negative depth or temperature below a physical limit, separate the mathematical graph from the realistic interpretation. Give a unit to the horizontal period. When fitted from data, several trigonometric formulas may produce the same graph through equivalent phase shifts.',
  },
  'SL 3.8': {
    skills: ['Solve sine, cosine or tangent equations over an exact interval.', 'Transform an angle such as $2x$ before enumerating candidates.', 'Reject solutions introduced by division or inverse-function shortcuts.'],
    why: 'Inverse trigonometric functions return principal values. Periodicity and symmetry supply other solutions: sine repeats every $2\\pi$ and has reflection symmetry, while tangent repeats every $\\pi$. If the unknown appears inside $2x$, double the bounds of the requested interval before solving, then halve the candidates.',
    edge: 'For $\\sin x=1/2$ on $0\\leq x<2\\pi$, the solutions are $\\pi/6$ and $5\\pi/6$. For $\\sin(2x)=1/2$ on $0\\leq x<\\pi$, the angle $2x$ has the same full-turn interval, so $x=\\pi/12$ and $5\\pi/12$. Failing to change the interval causes missing or extra solutions.',
    connection: 'Mark whether endpoints are included. A calculator in degrees when the question uses radians can give plausible-looking but incompatible decimals. Verify each exact root with a known unit-circle value and state all solutions requested, not an unqualified general solution.',
  },
  'AHL 3.9': {
    skills: ['Define secant, cosecant and cotangent with excluded denominator zeroes.', 'Use $1+\\tan^2x=\\sec^2x$ or $1+\\cot^2x=\\csc^2x$.', 'Choose signs of reciprocal functions from quadrant information.'],
    why: 'A reciprocal ratio inherits every zero exclusion of its denominator. The identities arise by dividing $\\sin^2x+\\cos^2x=1$ by $\\cos^2x$ or $\\sin^2x$ on domains where those quantities are nonzero. The squares determine magnitude but not sign; quadrant information must settle the sign of a reciprocal value.',
    edge: 'If $\\tan x=3/4$ in quadrant III, construct a reference triangle with hypotenuse $5$. Both sine and cosine are negative, so $\\sec x=-5/4$ and $\\csc x=-5/3$. The identity $1+\\tan^2x=25/16=\\sec^2x$ confirms the magnitude but cannot determine the negative sign on its own.',
    connection: 'The reciprocal of tangent is cotangent, not the inverse function $\\arctan$. Writing definitions before manipulation prevents this notation confusion. When solving identities containing ratios, state which angles were excluded by division even if a rearranged equation appears defined there. A real secant or cosecant has magnitude at least one wherever defined, providing another useful check.',
  },
  'AHL 3.10': {
    skills: ['Expand sine and cosine of a sum or difference.', 'Apply the tangent addition formula only when its denominator is nonzero.', 'Derive exact double-angle values from known angles.'],
    why: 'Compound-angle identities combine two rotations, and the sign in the cosine formula reverses the sign in the angle. It is often safer to write the entire identity with $A$ and $B$ before inserting numerical angles. For tangent, $1-\\tan A\\tan B=0$ signals an undefined tangent of the sum, not an infinite numeric solution.',
    edge: 'Using $\\sin(45^\\circ+30^\\circ)$ gives $(\\sqrt2/2)(\\sqrt3/2)+(\\sqrt2/2)(1/2)=(\\sqrt6+\\sqrt2)/4$. The corresponding cosine is $(\\sqrt6-\\sqrt2)/4$ because its cross term is subtracted. Approximate $\\sin75^\\circ$ to confirm it lies near one, not near zero.',
    connection: 'When the problem mixes degrees and radians, convert before combining values. The double-angle formulas are special cases with equal angles; decide whether to express the answer in sine, cosine or tangent to match available data. State a restriction whenever a ratio includes a vanishing denominator. Recheck signs by substituting one angle pair into the unexpanded trigonometric expression.',
  },
  'AHL 3.11': {
    skills: ['Relate sine, cosine, tangent and their reciprocals.', 'Derive an equivalent expression using a Pythagorean relation.', 'Track quadrant signs when recovering a ratio from a squared value.'],
    why: 'A trigonometric ratio is not an isolated formula: tangent is a quotient and the reciprocal ratios are defined by the other two coordinates. Algebraic substitutions among these relationships are valid only where their denominators exist. Squaring both sides loses sign information, which can create apparent solutions outside a specified quadrant.',
    edge: 'If $\\sin x=-3/5$ and $x$ is in quadrant IV, then $\\cos x=4/5$, $\\tan x=-3/4$ and $\\sec x=5/4$. The Pythagorean identity yields $|\\cos x|=4/5$ first; the quadrant selects the positive sign. Every inferred ratio should be checked against its denominator condition.',
    connection: 'The booklet groups many of these relationships under printed sections 3.5, 3.6 and 3.9, even though there is no separate 3.11 row. A missing row is not evidence that a fact is irrelevant. Derive what you need from the definitions and identify which listed identities actually support the step.',
  },
  'AHL 3.12': {
    skills: ['Use directed components to add, subtract and scale vectors.', 'Compute a displacement and its magnitude in two or three dimensions.', 'Create a unit vector and distinguish direction from length.'],
    why: 'A vector specifies magnitude and direction rather than a location by itself. Subtracting position vectors gives displacement from the first point to the second; reversing the order reverses its direction but keeps its magnitude. The norm comes from Pythagoras in perpendicular coordinate directions. A unit vector exists only when the original vector is nonzero.',
    edge: 'From $P=(1,-2,3)$ to $Q=(5,1,3)$, displacement is $\\overrightarrow{PQ}=(4,3,0)$, of length $5$ and unit direction $(4/5,3/5,0)$. Reversing the arrow gives $(-4,-3,0)$, also length $5$. Adding coordinates of the endpoints would not represent the requested displacement.',
    connection: 'A scalar multiple changes length and possibly reverses direction, while vector addition represents successive displacements. State a coordinate system and unit when the vector represents physical movement. Distinguish a point such as $(4,3)$ from a displacement with the same ordered components.',
  },
  'AHL 3.13': {
    skills: ['Calculate the scalar product from components.', 'Find an angle between nonzero vectors from its cosine.', 'Test perpendicularity without confusing it with parallelism.'],
    why: 'The dot product records how much one vector points along another. Component multiplication adds contributions from each axis; the geometric form divides by both magnitudes to recover an angle. A zero dot product implies perpendicularity for nonzero vectors, not that either vector must be zero. The cosine must lie between $-1$ and $1$.',
    edge: 'For $\\mathbf u=(2,1,0)$ and $\\mathbf v=(1,-2,2)$, the dot product is $2-2+0=0$, so they meet at $90^\\circ$. Their magnitudes are $\\sqrt5$ and $3$. These values confirm that neither is zero; without that condition an angle between vectors would be undefined.',
    connection: 'A negative dot product gives an obtuse angle, but not the exact angle without the magnitudes. In an applied projection, keep track of whether you seek a scalar component or a vector. Use an independent numerical check of your cosine before evaluating an inverse cosine on a calculator.',
  },
  'AHL 3.14': {
    skills: ['Construct a direction from two points and write a vector line.', 'Convert vector form to parametric component equations.', 'Write Cartesian symmetric form without dividing by a zero direction component.', 'Test membership using one common parameter value in every coordinate.'],
    why: 'A line consists of an anchor point plus all real multiples of a nonzero direction vector. Different anchor points or rescaled nonzero directions can describe the same line. A point lies on the line only if one parameter works simultaneously in all components; solving each coordinate with unrelated parameters does not establish membership.',
    edge: 'Through $A=(1,2,0)$ and $B=(3,1,4)$, use direction $B-A=(2,-1,4)$, giving $(x,y,z)=(1,2,0)+t(2,-1,4)$. The point $(5,0,8)$ uses $t=2$ in all three coordinates. The point $(5,0,7)$ fails the third coordinate despite matching the first two.',
    connection: 'Cartesian symmetric form needs care when a direction component is zero; write that coordinate as a fixed value instead of dividing by zero. A line equation is not a finite segment unless bounds on the parameter are stated. Check a proposed direction by subtracting the given endpoints.',
  },
  'AHL 3.15': {
    skills: ['Compare directions to recognize parallel or coincident lines.', 'Solve all coordinate equations to find a true intersection.', 'Demonstrate skewness when nonparallel spatial lines do not meet.'],
    why: 'In a plane, two nonparallel lines meet; in three dimensions they can be skew. Testing direction vectors alone distinguishes parallel from nonparallel, but a coincident line also needs a common point. For an intersection solve a pair of parameter equations and verify the third component. That final check is exactly what distinguishes skewness.',
    edge: 'Let $L_1=(t,0,0)$ and $L_2=(0,s,1)$. Their directions $(1,0,0)$ and $(0,1,0)$ are not parallel, but every point of $L_1$ has $z=0$ while every point of $L_2$ has $z=1$. They cannot intersect and are skew. A flat sketch can incorrectly make their projections cross.',
    connection: 'Use separate symbols for the two line parameters; a shared symbol would impose an unjustified timing condition. When a solver returns a point, substitute it into both complete line equations. A zero direction vector is invalid as a line direction and must not be treated as a parallel special case.',
  },
  'AHL 3.16': {
    skills: ['Compute a vector product with correct component signs.', 'Use its magnitude for parallelogram and triangle area.', 'Check perpendicularity of the result to both input vectors.'],
    why: 'The cross product is perpendicular to the plane spanned by two three-dimensional vectors. Reversing the input order changes its sign but not its magnitude. The magnitude measures the area of their parallelogram because it equals $|\\mathbf u||\\mathbf v|\\sin\\theta$. Half that area belongs to the triangle made by the same sides.',
    edge: 'For $\\mathbf u=(1,0,0)$ and $\\mathbf v=(0,2,0)$, $\\mathbf u\\times\\mathbf v=(0,0,2)$. Their parallelogram area is $2$, and their triangle area is $1$. Reversing the vectors gives $(0,0,-2)$; both possible normals have the same length and are orthogonal to each input.',
    connection: 'Parallel vectors have zero cross product and zero spanned area, not an undefined result. For a more complex component calculation, take dot products of your answer with each original vector as a quick diagnostic. Use the resulting normal to construct a plane equation.',
  },
  'AHL 3.17': {
    skills: ['Describe a plane by a point and two independent directions.', 'Obtain a normal from a cross product and write Cartesian form.', 'Test whether a point lies on the plane.'],
    why: 'A plane needs two nonparallel directions; a single direction describes only a line. Their cross product supplies a normal. In normal form, every displacement within the plane has zero dot product with that normal. A normal can be scaled without changing the plane, but the constant term must be recomputed from a known point.',
    edge: 'The plane through $(1,0,2)$ with normal $(2,-1,3)$ satisfies $2(x-1)-y+3(z-2)=0$, or $2x-y+3z=8$. Point $(0,1,3)$ yields $-1+9=8$, so it lies on the plane; point $(0,0,0)$ does not. Substituting a given point is the simplest check of the constant.',
    connection: 'If two proposed spanning directions are parallel, their cross product is zero and they cannot determine a unique plane. Distinguish a plane parameterization from its single Cartesian equation. When comparing planes, proportional normal vectors alone indicate parallel orientation, not necessarily identical planes.',
  },
  'AHL 3.18': {
    skills: ['Substitute a parametric line into a plane equation.', 'Classify parallel, contained and one-point intersection cases.', 'Find or compare intersections of two planes.'],
    why: 'Putting $\\mathbf r=\\mathbf a+t\\mathbf d$ into $\\mathbf n\\cdot\\mathbf r=c$ gives one linear equation in $t$. A nonzero coefficient yields a unique crossing. If the coefficient of $t$ vanishes, the line is parallel to the plane; the remaining constant says whether it lies within that plane or misses it entirely.',
    edge: 'For $(x,y,z)=(1,0,0)+t(1,2,1)$ and plane $x+y+z=5$, substitution gives $1+4t=5$, so $t=1$ and the point is $(2,2,1)$. Check $2+2+1=5$. If the direction were $(1,-1,0)$ instead, its dot product with normal $(1,1,1)$ would vanish, indicating no unique crossing.',
    connection: 'An intersection of two nonparallel planes is a line, not a point. When a system produces a free parameter, express that geometric line explicitly. Keep separate any restricted line segment bounds; an intersection on the infinite line might not lie in the original physical segment.',
  },
};
