export const lessons = [
  ['SL 5.1', 'Introduction to differential calculus',
    String.raw`A derivative measures instantaneous change as the limiting slope of secant lines. It can describe a tangent's gradient, velocity, or a rate per unit change. The underlying limit matters when a graph has a corner or a gap, where a derivative may not exist.`,
    String.raw`$f'(a)=\lim_{h\to0}[f(a+h)-f(a)]/h$ if the limit exists. Geometrically the numerator is change in output and $h$ is change in input. A differentiable function is continuous at that point, but continuity alone does not guarantee differentiability.`,
    String.raw`For $f(x)=x^2$ at $x=3$, the difference quotient is $[(3+h)^2-3^2]/h=(6h+h^2)/h=6+h$ for $h\neq0$. As $h\to0$, the quotient tends to $6$. Thus the tangent slope at $(3,9)$ is $6$, even though no nonzero secant step of exactly zero was divided by.`,
    'Paper 1 style: show cancellation before taking the limit; never substitute $h=0$ into an expression with denominator $h$.',
    String.raw`An average rate over an interval is a secant slope, not automatically the instantaneous rate at its endpoint.`,
    String.raw`Find the average rate of change of $x^2$ from $x=1$ to $x=3$.`,
    String.raw`$(9-1)/(3-1)=4$ per unit $x$.`],
  ['SL 5.2', 'Increasing and decreasing functions',
    String.raw`A differentiable function increases where its derivative is positive and decreases where it is negative. Critical values partition the domain for a sign test. A zero derivative alone does not prove a maximum or a minimum.`,
    String.raw`If $f'(x)>0$ throughout an interval, $f$ increases there; if $f'(x)<0$, it decreases. Include points where $f'$ does not exist when constructing a complete critical-point list. Use open intervals for sign statements unless endpoints are separately considered.`,
    String.raw`For $f(x)=x^3-3x$, $f'(x)=3x^2-3=3(x-1)(x+1)$. It is positive for $x<-1$ and $x>1$, negative for $-1<x<1$. Therefore $f$ increases on $(-\infty,-1)$ and $(1,\infty)$ and decreases on $(-1,1)$. At $x=-1$ the sign changes positive to negative, giving a local maximum.`,
    'Paper 1 style: supply a derivative sign chart, not just a list of stationary points.',
    String.raw`$f'(a)=0$ is a candidate for a turning point. For $f(x)=x^3$, $f'(0)=0$ but the function keeps increasing.`,
    String.raw`Where does $f(x)=x^2$ increase?`,
    String.raw`$f'(x)=2x>0$ for $x>0$, so it increases on $(0,\infty)$.`],
  ['SL 5.3', 'Differentiating integer powers',
    String.raw`The power rule turns a polynomial's local rate into another algebraic expression. It also works for negative integer powers away from excluded inputs. Differentiation is linear, so handle sums term by term.`,
    String.raw`$\dfrac{d}{dx}x^n=nx^{n-1}$ for the appropriate domain, including integer $n$. Constants differentiate to zero and $d(af+bg)/dx=af'+bg'$. For a negative power, retain any domain restriction such as $x\neq0$.`,
    String.raw`Differentiate $f(x)=2x^3-5x+1$: $f'(x)=6x^2-5$. At $x=1$, the slope is $6-5=1$. Separately, $d(x^{-2})/dx=-2x^{-3}$ for $x\neq0$. Check the first result by noting the constant $1$ contributes no slope.`,
    'Paper 1 style: show a separate derivative for each term before evaluating at a point.',
    String.raw`Do not keep the constant $+1$ in $f'$. The derivative of any constant is zero.`,
    String.raw`Find $d(3x^4-2x^2)/dx$.`,
    String.raw`$12x^3-4x$.`],
  ['SL 5.4', 'Tangents and normals',
    String.raw`A tangent follows the local slope of a curve. A normal passes through the same point and is perpendicular to the tangent. Finding either line requires both its gradient and a point on the curve.`,
    String.raw`At $x=a$, tangent gradient is $f'(a)$ and tangent equation is $y-f(a)=f'(a)(x-a)$. If $f'(a)\neq0$, normal gradient is $-1/f'(a)$. A horizontal tangent has a vertical normal $x=a$.`,
    String.raw`For $y=x^2$ at $x=2$, the point is $(2,4)$ and derivative $2x$ gives tangent gradient $4$. Thus $y-4=4(x-2)$, or $y=4x-4$. The normal has gradient $-1/4$ and equation $y-4=-\tfrac14(x-2)$. Both lines pass through $(2,4)$.`,
    'Paper 1 style: write the point before finding either line, and check the perpendicular gradients multiply to $-1$.',
    String.raw`The normal gradient is the negative reciprocal, not just the negative tangent gradient.`,
    String.raw`Find the tangent to $y=3x$ at $x=1$.`,
    String.raw`The curve is already a line, so the tangent is $y=3x$.`],
  ['SL 5.5', 'Integration and area from a graph',
    String.raw`Integration reverses differentiation and can also accumulate signed area under a graph. A definite integral is positive where the graph lies above the axis and negative where it lies below. Geometric area uses absolute values if a region crosses the axis.`,
    String.raw`If $F'=f$, then $\int_a^b f(x)\,dx=F(b)-F(a)$ when the conditions of the fundamental theorem hold. For a nonnegative $f$ on $[a,b]$, this equals the area between its graph and the $x$-axis.`,
    String.raw`For $f(x)=2x$ on $0\leq x\leq3$, an antiderivative is $F(x)=x^2$. Hence $\int_0^3 2x\,dx=[x^2]_0^3=9$ square units. Geometry agrees: the region is a triangle with base $3$ and height $f(3)=6$, so its area is $3(6)/2=9$.`,
    'Paper 1 style: state whether the integral is a signed value or a positive geometric area.',
    String.raw`If a curve goes below the axis, adding a single integral may cancel positive and negative areas. Split at the zeros for total area.`,
    String.raw`Find $\int_0^2 x\,dx$ and interpret it as area.`,
    String.raw`$[x^2/2]_0^2=2$ square units, a triangle of base $2$ and height $2$.`],
  ['SL 5.6', 'Chain, product and quotient rules',
    String.raw`Complicated derivatives are built from simpler ones. The chain rule tracks a change inside a function; the product rule tracks two changing factors; the quotient rule accounts for a changing denominator. Selecting the structure first avoids applying a rule blindly.`,
    String.raw`$(f(g(x)))'=f'(g(x))g'(x)$, $(uv)'=u'v+uv'$, and $(u/v)'=(vu'-uv')/v^2$ for $v\neq0$. The power rule also extends to rational exponents wherever the relevant real function is differentiable.`,
    String.raw`For $h(x)=(x^2+1)^3$, let $u=x^2+1$. Then $dh/dx=3u^2(2x)=6x(x^2+1)^2$. For $p(x)=x^2e^x$, $p'=2xe^x+x^2e^x=e^x(x^2+2x)$. For $q=x/(x+1)$, $q'=[(x+1)-x]/(x+1)^2=1/(x+1)^2$ when $x\neq-1$.`,
    'Paper 1 style: identify the inner function or the two factors before differentiating; keep domain restrictions.',
    String.raw`Differentiating $(x^2+1)^3$ as $3(x^2+1)^2$ omits the inner derivative $2x$.`,
    String.raw`Differentiate $(3x+1)^4$.`,
    String.raw`$4(3x+1)^3\cdot3=12(3x+1)^3$.`],
  ['SL 5.7', 'The second derivative',
    String.raw`The second derivative measures how the first derivative changes. Its sign describes concavity locally: upward for positive values, downward for negative ones. A zero second derivative is only a candidate for a change in concavity.`,
    String.raw`$f''(x)=d(f'(x))/dx$. At a stationary point $f'(a)=0$, $f''(a)>0$ indicates a local minimum and $f''(a)<0$ a local maximum; when $f''(a)=0$, the test is inconclusive.`,
    String.raw`For $f(x)=x^4-2x^2$, $f'(x)=4x^3-4x$ and $f''(x)=12x^2-4$. At $x=0$, the first derivative is zero and $f''(0)=-4<0$, so $(0,0)$ is a local maximum. At $x=1$, $f'(1)=0$ and $f''(1)=8>0$, so $(1,-1)$ is a local minimum.`,
    "Paper 1 style: evaluate both $f'$ and $f''$ at each candidate before classifying it.",
    String.raw`$f''(a)=0$ does not prove an inflection. Check whether concavity changes on either side.`,
    String.raw`Find the second derivative of $f(x)=x^3+2x$.`,
    String.raw`$f'(x)=3x^2+2$ and $f''(x)=6x$.`],
  ['SL 5.8', 'Optimization and points of inflection',
    String.raw`Optimization selects the best value under a constraint, often by reducing a model to one variable. Stationary points must be compared with boundaries and domain restrictions. An inflection is a genuine change of concavity, not merely a zero of the second derivative.`,
    String.raw`Solve $f'(x)=0$ for interior candidates, classify with a derivative sign chart or second-derivative test, and check endpoints for a closed domain. To test an inflection at $a$, inspect the sign of $f''$ on either side.`,
    String.raw`For $f(x)=-x^2+6x-5$ on $0\leq x\leq6$, $f'(x)=-2x+6$ vanishes at $x=3$, while $f''=-2<0$, so it is a maximum. Evaluate $f(3)=4$ and endpoints $f(0)=f(6)=-5$. Thus the global maximum on this interval is $4$ at $x=3$. The constant negative second derivative means this parabola has no inflection.`,
    'Paper 2 style: write the feasible domain from the context and compare all candidate values before declaring a global optimum.',
    String.raw`A stationary point with the largest value among *only* stationary points need not beat an endpoint. Check all permitted boundaries.`,
    String.raw`Find the minimum of $f(x)=(x-4)^2+1$ for all real $x$.`,
    String.raw`$1$ at $x=4$, where the square is zero.`],
  ['SL 5.9', 'Kinematics with calculus',
    String.raw`Position, velocity and acceleration are connected by differentiation. Displacement includes direction; distance traveled adds the lengths of individual journeys and may require splitting at times when velocity changes sign. Specify initial conditions when integrating back to position.`,
    String.raw`$v(t)=s'(t)$ and $a(t)=v'(t)=s''(t)$. Displacement on $[a,b]$ is $s(b)-s(a)=\int_a^b v(t)\,dt$; total distance is $\int_a^b|v(t)|\,dt$. Time is generally restricted to a meaningful interval.`,
    String.raw`Let $s(t)=t^3-6t^2+9t$ metres for $t\geq0$. Then $v(t)=3t^2-12t+9=3(t-1)(t-3)$ m/s and $a(t)=6t-12$ m/s$^2$. At $t=1$, the particle is instantaneously at rest with acceleration $-6$ m/s$^2$. The velocity changes sign around $t=1$, so later distance cannot be found solely from final minus initial position.`,
    'Paper 2 style: label units, locate turning times by solving $v=0$, and distinguish displacement from total distance.',
    String.raw`Negative velocity means movement in the negative direction, not a negative physical distance.`,
    String.raw`For $s(t)=2t^2+1$, find $v(3)$ and $a(3)$.`,
    String.raw`$v(t)=4t$, so $v(3)=12$; $a(t)=4$, so $a(3)=4$.`],
  ['SL 5.10', 'Indefinite integrals and substitution',
    String.raw`An indefinite integral describes a family of antiderivatives, differing by an arbitrary constant. Reverse chain rule recognizes an inner derivative beside a composed function. Substitution makes that structure explicit and helps avoid incorrect powers.`,
    String.raw`For differentiable $u(x)$, $\int f(u)u'(x)\,dx=F(u)+C$ when $F'=f$. For $n\neq-1$, $\int x^n\,dx=x^{n+1}/(n+1)+C$ on a suitable domain; $\int dx/x=\ln|x|+C$.`,
    String.raw`Integrate $\int6x(3x^2+1)^4\,dx$. Let $u=3x^2+1$, so $du=6x\,dx$. Then $\int u^4\,du=u^5/5+C=(3x^2+1)^5/5+C$. Differentiate the answer: $(1/5)5(3x^2+1)^4(6x)$ reproduces the integrand.`,
    'Paper 1 style: show the substitution and verify by differentiation if a coefficient is easy to miss.',
    String.raw`Leaving out $+C$ gives only one member of the antiderivative family.`,
    String.raw`Evaluate $\int 4x\,dx$.`,
    String.raw`$2x^2+C$.`],
  ['SL 5.11', 'Definite integrals and areas',
    String.raw`A definite integral accumulates net signed change between two bounds. The fundamental theorem evaluates it using any antiderivative. To report an actual area, partition at crossings of the axis or between curves and integrate the positive height difference on each interval.`,
    String.raw`$\int_a^b f(x)\,dx=F(b)-F(a)$ when $F'=f$ under the usual continuity conditions. Geometric area between $f$ and the $x$-axis is $\int_a^b|f(x)|\,dx$. Between upper $u$ and lower $l$, it is $\int_a^b[u(x)-l(x)]\,dx$.`,
    String.raw`Evaluate $\int_0^2(x^2+1)\,dx$. An antiderivative is $x^3/3+x$. At $2$ this is $8/3+2=14/3$; at $0$ it is $0$. Since $x^2+1>0$, the net integral also equals the area between the curve and the $x$-axis on the interval.`,
    'Paper 2 style: use the graph to identify crossings and verify the sign of the integrand before calling a definite integral an area.',
    String.raw`Substituting only the upper bound omits $F(a)$. Always write $F(b)-F(a)$ explicitly.`,
    String.raw`Evaluate $\int_1^3 2x\,dx$.`,
    String.raw`$[x^2]_1^3=9-1=8$.`],
  ['AHL 5.12', 'First principles and higher derivatives',
    String.raw`First principles establish a derivative from a limit, rather than quoting a rule. Repeated differentiation yields higher derivatives and reveals how rates themselves change. A clear algebraic difference quotient is especially important when a removable factor appears.`,
    String.raw`$f'(a)=\lim_{h\to0}[f(a+h)-f(a)]/h$. Define $f''=(f')'$ and, where they exist, $f^{(n)}$ by repeated differentiation. The limit must be finite and agree from both sides for an ordinary two-sided derivative.`,
    String.raw`Take $f(x)=x^2+3x$. At $x=1$, $f(1)=4$ and $f(1+h)=4+5h+h^2$. The difference quotient is $(5h+h^2)/h=5+h$ for $h\neq0$, so $f'(1)=5$. Differentiating generally gives $f'(x)=2x+3$ and $f''(x)=2$, which checks the local calculation.`,
    'Paper 1 style: expand and factor the numerator before using the limit; show how the denominator cancels.',
    String.raw`Writing $0/0$ after substituting $h=0$ is not a derivative. Simplify first and then take the limit.`,
    String.raw`Use the power rule to find the third derivative of $x^4$.`,
    String.raw`$f'=4x^3$, $f''=12x^2$, $f'''=24x$.`],
  ['AHL 5.13', 'Limits and L’Hôpital’s rule',
    String.raw`A limit concerns the behavior near a point, not necessarily the function value at that point. L’Hôpital’s rule can turn certain indeterminate quotient forms into derivative quotients, but its hypotheses and the resulting limit must be checked. Algebraic simplification is often easier.`,
    String.raw`If numerator and denominator tend to $0$ or both diverge in the required way, and differentiability and nonzero denominator-derivative conditions hold nearby, one may consider $\lim f/g=\lim f'/g'$ when the latter limit exists appropriately. The rule does not apply directly to arbitrary products or non-indeterminate quotients.`,
    String.raw`Evaluate $\lim_{x\to0}(e^x-1)/x$. Both parts tend to $0$, so the form is $0/0$. Their derivatives are $e^x$ and $1$, and the derivative quotient tends to $e^0=1$. Hence the original limit is $1$. This is consistent with the tangent slope of $e^x$ at $0$.`,
    'Paper 1 style: state the indeterminate form and the derivative quotient; do not write the rule without checking applicability.',
    String.raw`L’Hôpital’s rule is not a license to differentiate a fraction term by term when the original limit is not $0/0$ or $\infty/\infty$.`,
    String.raw`Find $\lim_{x\to2}(x^2-4)/(x-2)$ by factoring.`,
    String.raw`$(x-2)(x+2)/(x-2)=x+2$ for $x\neq2$, so the limit is $4$.`],
  ['AHL 5.14', 'Implicit differentiation and related rates',
    String.raw`Implicit equations may define $y$ without isolating it as a function of $x$. Differentiate every occurrence of $y$ using the chain rule. For related rates, all changing quantities depend on time, so differentiate with respect to $t$ and substitute the instant's values afterward.`,
    String.raw`If $F(x,y)=0$ and $F_y\neq0$, then locally $dy/dx=-F_x/F_y$. For a circle $x^2+y^2=R^2$, $2x+2y\,dy/dx=0$. For moving points, $2x\,dx/dt+2y\,dy/dt=0$.`,
    String.raw`On $x^2+y^2=25$ at $(3,4)$, $dy/dx=-x/y=-3/4$. If the point moves along the circle and $dx/dt=2$ at that instant, differentiating in time gives $2(3)(2)+2(4)dy/dt=0$. Thus $dy/dt=-12/8=-3/2$ distance units per time unit. The signs agree with moving right and down in quadrant I.`,
    'Paper 2 style: state which quantity changes with which variable and include units and sign in the final rate.',
    String.raw`Treating $y$ as a constant while differentiating $y^2$ loses the factor $dy/dx$.`,
    String.raw`Find $dy/dx$ from $x^2+y^2=9$ at $(0,3)$.`,
    String.raw`$dy/dx=-x/y=0$ at $(0,3)$.`],
  ['AHL 5.15', 'Further differentiation and antiderivatives',
    String.raw`Exponential, logarithmic and trigonometric functions have derivative patterns beyond polynomials. Pairing each rule with its reverse is useful for checking an indefinite integral. Domains matter for logarithms and functions with poles.`,
    String.raw`$d(e^{ax})/dx=ae^{ax}$ and $\int e^{ax}\,dx=e^{ax}/a+C$ for $a\neq0$. $d(\ln|x|)/dx=1/x$ for $x\neq0$, and $d(\tan x)/dx=\sec^2x$ where tangent is defined.`,
    String.raw`Differentiate $e^{2x}$ by the chain rule: derivative $2e^{2x}$. Reverse the operation to integrate $e^{2x}$: an antiderivative is $\tfrac12e^{2x}$, so $\int e^{2x}\,dx=\tfrac12e^{2x}+C$. Differentiating the result returns the original integrand.`,
    'Paper 1 style: use a derivative check when integrating a function with an inner linear coefficient.',
    String.raw`$\int e^{2x}\,dx$ is not $e^{2x}+C$; differentiating that would produce $2e^{2x}$.`,
    String.raw`Integrate $\cos x$ and differentiate $\ln x$ for $x>0$.`,
    String.raw`$\int\cos x\,dx=\sin x+C$ and $d(\ln x)/dx=1/x$.`],
  ['AHL 5.16', 'Integration by substitution and parts',
    String.raw`Substitution reverses the chain rule, while integration by parts reverses the product rule. Choose a factor whose derivative simplifies when applying parts. Repeated integration by parts can return to a starting integral, which can then be solved algebraically.`,
    String.raw`$\int u\,dv=uv-\int v\,du$, provided the terms are integrable. For substitution $w=g(x)$, replace both the inner expression and $g'(x)\,dx$; in a definite integral also transform the limits.`,
    String.raw`Compute $\int xe^x\,dx$. Set $u=x$ and $dv=e^x\,dx$, so $du=dx$ and $v=e^x$. Then $\int xe^x\,dx=xe^x-\int e^x\,dx=(x-1)e^x+C$. Check by differentiation: $e^x+(x-1)e^x=xe^x$. Separately, $\int2x\cos(x^2)\,dx=\sin(x^2)+C$ by substitution.`,
    'Paper 1 style: show the choices of $u$ and $dv$ and differentiate the final answer to catch a sign error.',
    String.raw`The minus sign in $uv-\int v\,du$ is essential; without it the derivative of the result will not match.`,
    String.raw`Evaluate $\int x\cos x\,dx$ using parts.`,
    String.raw`With $u=x$, $dv=\cos x\,dx$, the result is $x\sin x+\cos x+C$.`],
  ['AHL 5.17', 'Areas with respect to y and volumes',
    String.raw`Vertical slices give integrals with respect to $x$; horizontal slices give integrals with respect to $y$. Choose the direction that makes the right and left boundaries easiest to express. Volumes of revolution add circular cross-sections, with radius determined by distance to the axis.`,
    String.raw`Horizontal-slice area is $\int_{y_0}^{y_1}[x_{\rm right}(y)-x_{\rm left}(y)]\,dy$. Revolving a nonnegative curve $y=f(x)$ about the $x$-axis gives $V=\pi\int_a^b f(x)^2\,dx$ when discs fill the region. For holes use outer area minus inner area.`,
    String.raw`Between $x=y^2$ and $x=2y$ for $0\leq y\leq2$, the right boundary is $2y$ and the left is $y^2$. Area $=\int_0^2(2y-y^2)\,dy=[y^2-y^3/3]_0^2=4/3$. Separately, revolving the region under $y=x$ from $x=0$ to $2$ about the $x$-axis yields $V=\pi\int_0^2x^2\,dx=8\pi/3$.`,
    'Paper 2 style: draw a typical slice to justify which function is rightmost or which radius is outer.',
    String.raw`For volume, square the radius before integrating. $\pi\int f(x)\,dx$ does not generally measure a solid of revolution.`,
    String.raw`Revolve $y=2$ from $x=0$ to $3$ about the $x$-axis. Find the volume.`,
    String.raw`Cylinder: $\pi\int_0^3(2)^2\,dx=12\pi$ cubic units.`],
  ['AHL 5.18', 'First-order differential equations and Euler’s method',
    String.raw`A differential equation describes how an unknown function changes. Separation of variables can give an exact family; an initial value selects a specific member. Euler's method instead follows short tangent steps and accumulates approximation error.`,
    String.raw`For $dy/dx=F(x,y)$, Euler's step is $y_{n+1}=y_n+hF(x_n,y_n)$ with $x_{n+1}=x_n+h$. When variables separate, rearrange into a function of $y$ times $dy$ and a function of $x$ times $dx$, integrate, and use the initial condition.`,
    String.raw`Solve $dy/dx=2xy$, $y(0)=3$. Separation gives $dy/y=2x\,dx$ for a nonzero solution, so $\ln|y|=x^2+C$ and $y=3e^{x^2}$. Euler with $h=0.1$ starts at $(0,3)$: $y_1=3+0.1[2(0)(3)]=3$. The next step is $y_2=3+0.1[2(0.1)(3)]=3.06$. Exact $y(0.2)=3e^{0.04}\approx3.1224$, showing approximation error.`,
    'Paper 2 style: tabulate $x_n,y_n,F(x_n,y_n)$ for each Euler step and compare with a known exact solution when available.',
    String.raw`Euler uses the slope at the *start* of each step, not the unknown value at its end.`,
    String.raw`One Euler step with $h=0.2$ from $(0,1)$ for $dy/dx=x+y$ gives which value?`,
    String.raw`$y_1=1+0.2(0+1)=1.2$ at $x=0.2$.`],
  ['AHL 5.19', 'Maclaurin series',
    String.raw`A Maclaurin series builds a local polynomial approximation from a function's derivatives at zero. More terms can improve a nearby approximation, but convergence and truncation error must be considered. A finite Taylor polynomial is not automatically equal to the full function.`,
    String.raw`$f(x)=\sum_{n=0}^\infty f^{(n)}(0)x^n/n!$ where the series converges to $f$. In particular $e^x=1+x+x^2/2!+x^3/3!+\cdots$ for all real $x$. A truncated approximation leaves a remainder, whose size depends on $x$ and the function.`,
    String.raw`Use the quadratic Maclaurin polynomial for $e^x$ at $x=0.1$: $1+0.1+0.1^2/2=1.105$. The true value is about $1.105170$, so the error is roughly $0.000170$. The next omitted term $0.1^3/6\approx0.0001667$ indicates the error scale; a rigorous bound would also control later terms.`,
    'Paper 1 style: identify how many terms are retained and distinguish approximation from equality.',
    String.raw`An ellipsis in the full series is not permission to omit the remainder when claiming an exact finite equality.`,
    String.raw`Write the first three nonzero Maclaurin terms of $\sin x$.`,
    String.raw`$\sin x=x-x^3/3!+x^5/5!+\cdots$.`],
];
