export const lessons = [
  ['SL 2.1', 'Straight lines and gradients',
    String.raw`The gradient measures change in $y$ per unit change in $x$. Two distinct nonvertical parallel lines have the same gradient. Nonvertical perpendicular lines have gradients with product $-1$. A vertical line cannot be written as $y=mx+c$, so use $x=a$ when needed.`,
    String.raw`$m=(y_2-y_1)/(x_2-x_1)$ for $x_2\neq x_1$; through $(x_1,y_1)$, $y-y_1=m(x-x_1)$. Parallel: $m_1=m_2$. Perpendicular: $m_1m_2=-1$ when both gradients are defined.`,
    String.raw`The line through $(1,2)$ and $(3,6)$ has $m=(6-2)/(3-1)=2$. Using $(1,2)$ gives $y-2=2(x-1)$, or $y=2x$. A perpendicular line through $(1,2)$ has gradient $-1/2$, hence $y-2=-\tfrac12(x-1)$. Check the original line at both given points.`,
    'Paper 1 style: calculate the gradient before finding the intercept; handle vertical lines separately.',
    String.raw`The negative reciprocal of $2$ is $-1/2$, not $-2$. Multiply the two gradients to test perpendicularity.`,
    String.raw`Find the equation of the line through $(0,3)$ and $(2,7)$.`,
    String.raw`$m=(7-3)/2=2$ and the intercept is $3$, so $y=2x+3$.`],
  ['SL 2.2', 'Functions, domains, ranges and inverses',
    String.raw`A function assigns exactly one output to each allowed input. Domain lists allowed inputs; range lists attainable outputs. An inverse reverses input and output only when the original function is one-to-one on its chosen domain.`,
    String.raw`If $y=f(x)$, solve this equation for $x$ and interchange the variables to obtain $f^{-1}$, then state its domain. The domain of $f^{-1}$ is the range of $f$. Square roots require nonnegative radicands in real-valued questions.`,
    String.raw`Let $f(x)=\sqrt{x-2}$. For real outputs, $x-2\geq0$, so $D_f=[2,\infty)$ and $R_f=[0,\infty)$. From $y=\sqrt{x-2}$, square to get $x=y^2+2$. Therefore $f^{-1}(x)=x^2+2$ for $x\geq0$. Check $f(f^{-1}(3))=\sqrt{11-2}=3$.`,
    'Paper 1 style: an inverse formula without its restricted domain can lose the key idea. Sketch a graph if the range is not obvious.',
    String.raw`$f^{-1}(x)$ does not mean $1/f(x)$. Inversion is reversal of the mapping, not a reciprocal.`,
    String.raw`Find the inverse of $f(x)=3x-2$ for real $x$.`,
    String.raw`$y=3x-2\Rightarrow x=(y+2)/3$, so $f^{-1}(x)=(x+2)/3$ with real domain.`],
  ['SL 2.3', 'Graphing functions',
    String.raw`A graph is a visual set of input-output pairs. Intercepts, vertex positions, symmetry and end behavior reveal structure before any plotting tool is used. A table samples the function but cannot prove there are no other features.`,
    String.raw`For $y=ax^2+bx+c$, the axis of symmetry is $x=-b/(2a)$ when $a\neq0$. To find $x$-intercepts set $y=0$; to find a $y$-intercept set $x=0$. Label axes and choose a window that shows relevant behavior.`,
    String.raw`Sketch $f(x)=x^2-4$. Since the square is nonnegative, the minimum is $-4$ at $x=0$, giving vertex $(0,-4)$. Setting $x^2-4=0$ yields intercepts $(-2,0)$ and $(2,0)$; the $y$-intercept is $(0,-4)$. The graph opens upward and is symmetric about the $y$-axis.`,
    'Paper 1 style: mark exact intercepts and a turning point rather than drawing an unlabeled curve.',
    String.raw`A graphing window may hide an intercept or turning point. A blank screen is not evidence that the function has no values.`,
    String.raw`List the intercepts and vertex of $y=(x-1)^2-9$.`,
    String.raw`Vertex $(1,-9)$, $x$-intercepts $(-2,0)$ and $(4,0)$, and $y$-intercept $(0,-8)$.`],
  ['SL 2.4', 'Graph features and intersections',
    String.raw`To find where two functions meet, equate their outputs at the same input. Technology can estimate crossing coordinates, but the algebra and the viewing window determine whether the reported solutions are complete. Distinguish a local feature from a global one.`,
    String.raw`Intersections satisfy $f(x)=g(x)$. For a polynomial, turning points have horizontal tangents, but a stationary point may be a maximum, a minimum or neither. For a rational function, discontinuities can interrupt a graphical trace.`,
    String.raw`Find the intersections of $y=x^2$ and $y=2x+3$. Equate: $x^2=2x+3$, so $x^2-2x-3=(x-3)(x+1)=0$. With $x=3$, $y=9$; with $x=-1$, $y=1$. The crossing points are $(3,9)$ and $(-1,1)$. A calculator plot should show both if its window includes them.`,
    'Paper 2 style: record coordinates and a calculation or graph method, then check each point in both functions.',
    String.raw`Reporting only the $x$-coordinates does not give intersection points. Substitute back to find the corresponding $y$-values.`,
    String.raw`Where do $y=x+2$ and $y=2x-1$ intersect?`,
    String.raw`$x+2=2x-1$ gives $x=3$, then $y=5$: $(3,5)$.`],
  ['SL 2.5', 'Composite and inverse functions',
    String.raw`Composition means applying one mapping after another. Its order matters: $f\circ g$ first applies $g$. The input must pass through the inner function and then lie in the domain of the outer one. An inverse undoes a one-to-one function on a specified domain.`,
    String.raw`$(f\circ g)(x)=f(g(x))$. For an invertible $f$, $f(f^{-1}(x))=x$ on the range of $f$ and $f^{-1}(f(x))=x$ on its domain. The identity mapping sends $x$ to $x$.`,
    String.raw`Let $f(x)=2x+1$ and $g(x)=x^2$. Then $(f\circ g)(x)=2x^2+1$ while $(g\circ f)(x)=(2x+1)^2=4x^2+4x+1$. They are different. Solve $y=2x+1$ to find $f^{-1}(x)=(x-1)/2$, and check $f(f^{-1}(x))=x$.`,
    'Paper 1 style: write the inner substitution visibly, and state domain restrictions when square roots or denominators are involved.',
    String.raw`Do not cancel an $f$ against a $g$. The composition is ordered and cannot be treated like ordinary multiplication.`,
    String.raw`If $f(x)=x+3$ and $g(x)=2x$, find $(g\circ f)(4)$.`,
    String.raw`$f(4)=7$ and $g(7)=14$.`],
  ['SL 2.6', 'Quadratic functions',
    String.raw`A quadratic graph is a parabola. Its completed-square form makes the vertex and direction visible, while factored form makes roots visible. Every quadratic with nonzero leading coefficient has exactly one axis of symmetry.`,
    String.raw`$f(x)=a(x-h)^2+k$ has vertex $(h,k)$ and opens upward if $a>0$, downward if $a<0$. The discriminant $\Delta=b^2-4ac$ indicates two, one or no distinct real roots as $\Delta$ is positive, zero or negative.`,
    String.raw`For $f(x)=-2(x-3)^2+8$, the vertex is $(3,8)$ and the graph opens downward. Solve $-2(x-3)^2+8=0$: $(x-3)^2=4$, so $x=1$ or $x=5$. The roots are equally spaced from the axis $x=3$. The maximum value of $f$ is $8$.`,
    'Paper 1 style: move between completed-square and factored representations to explain roots and extremum.',
    String.raw`In $a(x-h)^2+k$, the vertex has $x=h$, not $-h$. Check by making the squared term zero.`,
    String.raw`Give the vertex of $y=3(x+2)^2-5$.`,
    String.raw`$(-2,-5)$, and this is a minimum because $3>0$.`],
  ['SL 2.7', 'Quadratic equations and inequalities',
    String.raw`Solving a quadratic equation finds boundary points; solving a quadratic inequality also asks which intervals satisfy a sign condition. The sign of the leading coefficient and the roots tell you which intervals to test. Equality affects whether endpoints belong to the answer.`,
    String.raw`$x=(-b\pm\sqrt{b^2-4ac})/(2a)$ for $ax^2+bx+c=0$, $a\neq0$. Factoring is often faster when integers work. For inequalities, use a sign chart or a clear sketch; never infer an interval from the roots alone.`,
    String.raw`Solve $x^2-5x+6<0$. Factor $(x-2)(x-3)<0$. The roots $2$ and $3$ split the line into three intervals. Test $x=0$: positive; test $x=5/2$: negative; test $x=4$: positive. Therefore $2<x<3$. The strict inequality excludes both roots.`,
    'Paper 1 style: include a sign diagram or test point so the chosen interval is justified.',
    String.raw`For $\leq0$, include roots where the expression equals zero. For $<0$, exclude them.`,
    String.raw`Solve $x^2-4\geq0$.`,
    String.raw`$(x-2)(x+2)\geq0$ for $x\leq-2$ or $x\geq2$.`],
  ['SL 2.8', 'Reciprocal and simple rational functions',
    String.raw`A rational graph can have vertical asymptotes, horizontal asymptotes or holes. The algebraic domain must be checked before simplifying. A hole occurs when a factor cancels, whereas an uncancelled denominator zero produces a vertical blow-up in typical simple cases.`,
    String.raw`$f(x)=a+k/(x-h)$ has vertical asymptote $x=h$ if $k\neq0$ and horizontal asymptote $y=a$. To locate intercepts, solve numerator $=0$ for the $x$-intercept and substitute $x=0$ for the $y$-intercept, if allowed.`,
    String.raw`Rewrite $(x+1)/(x-2)$ as $1+3/(x-2)$, because $x+1=(x-2)+3$. Thus $x=2$ and $y=1$ are asymptotes. The $x$-intercept is $-1$; at $x=0$, $y=-1/2$. The graph cannot include $x=2$, and the two branches approach but do not touch the vertical line.`,
    'Paper 1 style: justify the asymptotes by division and mark at least one intercept.',
    String.raw`An asymptote is not necessarily a line the graph never crosses. A horizontal asymptote describes behavior at large $|x|$.`,
    String.raw`State the asymptotes of $y=2+5/(x+1)$.`,
    String.raw`Vertical $x=-1$; horizontal $y=2$.`],
  ['SL 2.9', 'Exponential and logarithmic functions',
    String.raw`Exponential growth changes by a constant ratio over equal input steps. A logarithmic function reverses a positive-base exponential. Their graphs are reflections across $y=x$ when paired as inverses, with domain and range exchanged.`,
    String.raw`For $b>0$, $b\neq1$, $f(x)=b^x$ has range $(0,\infty)$; $f^{-1}(x)=\log_b x$ has domain $(0,\infty)$. When $b>1$, both functions increase. Growth models of the form $A b^t$ require units and interpretation of $t$.`,
    String.raw`For $f(x)=3^x$, solve $f(x)=27$ by writing $27=3^3$: $x=3$. The inverse is $f^{-1}(x)=\log_3 x$ for $x>0$. Check the inverse at $x=27$: $\log_3 27=3$. The exponential passes through $(0,1)$; the log passes through $(1,0)$.`,
    'Paper 2 style: use a graph or numerical solve when exponentials cannot be reduced to a common base; interpret the answer in context.',
    String.raw`A logarithmic graph does not include $x=0$. Its vertical asymptote reflects the exponential horizontal asymptote $y=0$.`,
    String.raw`State the domain of $y=\ln(x-4)$ and solve $e^x=e^2$.`,
    String.raw`Domain $x>4$ and solution $x=2$.`],
  ['SL 2.10', 'Solving equations graphically and analytically',
    String.raw`An equation $f(x)=g(x)$ can be treated as intersections of two graphs or as zeros of $h(x)=f(x)-g(x)$. An analytic solution is exact when possible; a numerical root is approximate and should state accuracy and a valid interval.`,
    String.raw`For $f(x)=g(x)$, plot both in a suitable window or solve $f(x)-g(x)=0$. Always substitute candidate roots into the original equation, especially if squaring or multiplying by an expression that might be zero.`,
    String.raw`Solve $x^2=2x+3$. On a graph, look for crossings of $y=x^2$ and $y=2x+3$. Analytically, $x^2-2x-3=(x-3)(x+1)=0$, so $x=3$ or $x=-1$. Both check: $9=9$ and $1=1$. The graphical method should locate two crossings rather than reporting only the first one.`,
    'Paper 2 style: cite the function pair or zero-finding setup and the window used, then round only as instructed.',
    String.raw`A solver can miss roots outside its search interval. Scan the relevant domain before trusting a single returned value.`,
    String.raw`Solve $|x|=x+2$ for real $x$.`,
    String.raw`For $x<0$, $-x=x+2$ gives $x=-1$; the $x\geq0$ case gives $0=2$, impossible. Answer $-1$.`],
  ['SL 2.11', 'Transformations of functions',
    String.raw`A transformation changes a graph without recalculating every point. Changes inside a function act on inputs and often reverse the intuitive direction; changes outside act on outputs. The order matters when stretches and translations are combined.`,
    String.raw`If $y=f(x)$, then $f(x-h)+k$ shifts right $h$ and up $k$. Multiplying outside by $a$ scales vertical distances by $|a|$ and reflects in the $x$-axis when $a<0$. For $f(bx)$, horizontal distances scale by $1/|b|$.`,
    String.raw`Start with $f(x)=x^2$. For $g(x)=-2(x-3)^2+1$, shift right $3$, stretch vertically by $2$, reflect in the $x$-axis, then shift up $1$. The vertex moves from $(0,0)$ to $(3,1)$ and becomes a maximum. Check $g(3)=1$ and $g(4)=-1$.`,
    'Paper 1 style: describe the transformation sequence and track an anchor point, such as the vertex.',
    String.raw`$f(x+3)$ shifts left $3$, not right $3$. Solve $x+3=0$ to see where the old anchor at $0$ goes.`,
    String.raw`Where does the vertex of $y=x^2$ move under $y=(x+4)^2-2$?`,
    String.raw`To $(-4,-2)$.`],
  ['AHL 2.12', 'Factor, remainder and root relations',
    String.raw`Division by $x-a$ leaves remainder $p(a)$. Thus $p(a)=0$ exactly when $x-a$ is a factor. Vieta's relations connect roots to coefficients without solving every root first. These tools work well together on cubics and higher polynomials.`,
    String.raw`$p(x)=(x-a)q(x)+p(a)$. For a monic cubic $x^3+bx^2+cx+d$ with roots $r_1,r_2,r_3$, $r_1+r_2+r_3=-b$ and $r_1r_2r_3=-d$, counting multiplicities.`,
    String.raw`Let $p(x)=x^3-2x^2-x+2$. Since $p(2)=8-8-2+2=0$, $x-2$ is a factor. Group terms: $x^2(x-2)-1(x-2)=(x-2)(x^2-1)=(x-2)(x-1)(x+1)$. Its roots $2,1,-1$ sum to $2$ and multiply to $-2$, matching the coefficients.`,
    'Paper 1 style: show the substitution establishing a factor before dividing or grouping.',
    String.raw`A nonzero remainder $p(a)$ is not a factor condition. It means $x-a$ does not divide $p(x)$ evenly.`,
    String.raw`Find the remainder when $p(x)=x^3+2x$ is divided by $x-2$.`,
    String.raw`$p(2)=8+4=12$.`],
  ['AHL 2.13', 'Rational functions and discontinuities',
    String.raw`Rational functions are quotients of polynomials. Their original domain excludes denominator zeros even if algebraic cancellation later produces a simpler formula. Long division reveals slant or polynomial asymptotes, while factorization reveals holes and vertical asymptotes.`,
    String.raw`For $f(x)=N(x)/D(x)$, begin with $D(x)\neq0$. A common factor can create a removable discontinuity; an uncancelled zero in the denominator may give a vertical asymptote. Horizontal asymptotes follow the ratio of leading terms when degrees match.`,
    String.raw`Consider $f(x)=(x^2-1)/(x-1)$ with original domain $x\neq1$. Factor $x^2-1=(x-1)(x+1)$ to get $f(x)=x+1$ only for $x\neq1$. The graph is the line $y=x+1$ with a hole at $(1,2)$. Calling $x=1$ a vertical asymptote would be incorrect because nearby values approach $2$.`,
    'Paper 1 style: give the excluded input and the hole coordinate after cancellation.',
    String.raw`Cancellation does not add an excluded input back to the original domain. Keep the restriction in the final answer.`,
    String.raw`Locate the hole of $(x^2-4)/(x-2)$.`,
    String.raw`The expression equals $x+2$ for $x\neq2$, so the hole is $(2,4)$.`],
  ['AHL 2.14', 'Odd, even and self-inverse functions',
    String.raw`Parity describes symmetry: even graphs reflect in the $y$-axis, and odd graphs rotate half a turn around the origin. Testing parity requires a domain symmetric about zero. A self-inverse function reverses itself, so composing it with itself gives the identity.`,
    String.raw`Even: $f(-x)=f(x)$; odd: $f(-x)=-f(x)$ on a symmetric domain. Self-inverse: $f(f(x))=x$ on the correct domain. The parabola $x^2$ needs a domain restriction such as $x\geq0$ before it has an inverse function.`,
    String.raw`The function $f(x)=x^2$ on all real numbers is even but not one-to-one since $f(2)=f(-2)$. Restrict to $x\geq0$ and the inverse becomes $\sqrt{x}$ for $x\geq0$. In contrast, $g(x)=1/x$ on nonzero reals is self-inverse: $g(g(x))=1/(1/x)=x$. It is also odd.`,
    'Paper 1 style: test $f(-x)$ algebraically and explicitly mention domain symmetry.',
    String.raw`An even function is not automatically invertible. A horizontal line may meet its graph twice.`,
    String.raw`Is $f(x)=x^3$ odd, even, or neither?`,
    String.raw`Odd: $f(-x)=(-x)^3=-x^3=-f(x)$.`],
  ['AHL 2.15', 'Rational and other inequalities',
    String.raw`An inequality with a denominator changes sign when that denominator changes sign. Multiplying both sides by an unknown-sign expression can silently reverse the inequality, so a sign chart is safer. Endpoints where the numerator vanishes may be included; poles never are.`,
    String.raw`Factor numerator and denominator, mark every zero and excluded point, test one input in each interval, and apply strict or inclusive endpoints carefully. When multiplying by a known negative constant, reverse the inequality direction.`,
    String.raw`Solve $(x-1)/(x+2)\geq0$. Critical points are $x=-2$ (excluded) and $x=1$ (zero). For $x<-2$, both factors are negative, so the quotient is positive. For $-2<x<1$, it is negative. For $x>1$, it is positive. The answer is $(-\infty,-2)\cup[1,\infty)$.`,
    'Paper 1 style: present a sign table or test values and label the pole separately from a root.',
    String.raw`Never include $x=-2$ just because the inequality includes equality. A division by zero is undefined.`,
    String.raw`Solve $(x-3)/(x+1)>0$.`,
    String.raw`The quotient is positive on $(-\infty,-1)\cup(3,\infty)$; exclude both boundaries.`],
  ['AHL 2.16', 'Modulus equations and inequalities',
    String.raw`Absolute value records distance from zero. An equation $|x-a|=r$ with $r\geq0$ gives points a distance $r$ from $a$; the corresponding strict inequality $|x-a|<r$ describes an open interval around $a$. Piecewise reasoning explains more complicated graphs.`,
    String.raw`$|u|=u$ if $u\geq0$, and $|u|=-u$ if $u<0$. For $r>0$, $|x-a|<r\iff a-r<x<a+r$; $|x-a|>r$ gives two exterior rays. Always check signs in each piece.`,
    String.raw`Solve $|x-2|=3$. The two distance equations are $x-2=3$ and $x-2=-3$, so $x=5$ or $x=-1$. For $|x-2|<3$, we need $-3<x-2<3$, giving $-1<x<5$. On a graph, $y=|x-2|$ is a V with vertex $(2,0)$.`,
    'Paper 1 style: explain the two cases or the distance interpretation; do not omit a valid branch.',
    String.raw`If the right side of $|u|=c$ is negative, there are no real solutions because absolute value is nonnegative.`,
    String.raw`Solve $|2x+1|=5$.`,
    String.raw`$2x+1=\pm5$ gives $x=2$ or $x=-3$.`],
];
