export const lessons = [
  ['SL 3.1', 'Three-dimensional geometry',
    String.raw`Three-dimensional distances come from repeated right triangles. A diagram helps identify which length is horizontal, vertical or oblique. A true spatial diagonal is not the same as a face diagonal, and a context may restrict which route can actually be traveled.`,
    String.raw`For a rectangular box with perpendicular side lengths $a,b,c$, the spatial diagonal is $d=\sqrt{a^2+b^2+c^2}$. Derive it by finding the base diagonal $\sqrt{a^2+b^2}$ and then applying Pythagoras with the height $c$.`,
    String.raw`A cuboid measures $3$, $4$ and $12$ units along three mutually perpendicular edges. Its base diagonal is $\sqrt{3^2+4^2}=5$. The spatial diagonal is $\sqrt{5^2+12^2}=13$. Direct calculation gives $\sqrt{9+16+144}=13$, confirming the two-stage construction.`,
    'Paper 2 style: draw the right triangle used at each stage, state units, and check whether the requested distance is inside or on the surface.',
    String.raw`Adding edge lengths gives a path along edges, not the straight-line diagonal. Use perpendicular squares for straight-line distance.`,
    String.raw`Find the spatial diagonal of a $2\times3\times6$ cuboid.`,
    String.raw`$\sqrt{2^2+3^2+6^2}=\sqrt{49}=7$ units.`],
  ['SL 3.2', 'Trigonometric ratios',
    String.raw`In a right triangle, sine, cosine and tangent relate an angle to particular side ratios. Label opposite and adjacent relative to the angle you are using, not relative to how the page is rotated. Exact special-angle ratios are useful checks on calculator answers.`,
    String.raw`$\sin\theta=\text{opposite}/\text{hypotenuse}$, $\cos\theta=\text{adjacent}/\text{hypotenuse}$ and $\tan\theta=\text{opposite}/\text{adjacent}$ for an acute angle in a right triangle. Check the calculator's degree or radian mode.`,
    String.raw`A right triangle has hypotenuse $10$ and an acute angle of $30^\circ$. The opposite side is $10\sin30^\circ=10(1/2)=5$. By Pythagoras the adjacent side is $\sqrt{10^2-5^2}=5\sqrt3$, agreeing with $10\cos30^\circ$. The ratios depend on the chosen angle.`,
    'Paper 1 style: show which ratio matches the known and unknown sides; Paper 2 can estimate non-special angles.',
    String.raw`A result longer than the hypotenuse for a side of the same right triangle is a warning that the sides or calculator mode are wrong.`,
    String.raw`If the legs are $6$ and $8$, find the hypotenuse and the sine of the angle opposite the side $6$.`,
    String.raw`Hypotenuse $10$ and sine $6/10=3/5$.`],
  ['SL 3.3', 'Applications of trigonometry',
    String.raw`Trigonometry connects diagrams with real measurements: bearings, heights, inaccessible distances and inclined surfaces. Bearings are measured clockwise from north, unlike standard coordinate angles measured counterclockwise from the positive horizontal direction.`,
    String.raw`For non-right triangles use $a/\sin A=b/\sin B=c/\sin C$ when opposite side-angle pairs are known, or $c^2=a^2+b^2-2ab\cos C$ when two sides and the included angle are known. Check the ambiguous sine-rule case where two triangles may fit.`,
    String.raw`A walker travels $6$ km east and $8$ km north. The displacement is $\sqrt{6^2+8^2}=10$ km. From north, the direction turns toward east by $\arctan(6/8)\approx36.87^\circ$, so the bearing is approximately $037^\circ$. A sketch prevents measuring the angle from east instead.`,
    'Paper 2 style: name the north reference, show the triangle, and round a bearing to three digits if appropriate.',
    String.raw`$37^\circ$ as a coordinate angle from east is a different direction from a bearing of $037^\circ$ from north.`,
    String.raw`A point lies $3$ km east and $4$ km north of the start. Find its straight-line distance.`,
    String.raw`$\sqrt{3^2+4^2}=5$ km.`],
  ['SL 3.4', 'Circles, radians and sectors',
    String.raw`A radian measures angle through arc length relative to radius. This makes sector formulas simple, because angle becomes a dimensionless ratio. A full revolution is $2\pi$ radians, so check that any sector angle is in the correct units before substitution.`,
    String.raw`For radius $r$ and central angle $\theta$ **in radians**, arc length $s=r\theta$ and sector area $A=\tfrac12r^2\theta$. In degrees, first convert by $\theta_{\rm rad}=\theta_{\rm deg}\pi/180$.`,
    String.raw`A sector has radius $6$ cm and angle $\pi/3$. Its arc length is $6(\pi/3)=2\pi$ cm. Its area is $\tfrac12(6)^2(\pi/3)=6\pi$ cm$^2$. As a check, $\pi/3$ is one sixth of a full circle, and one sixth of $36\pi$ is $6\pi$.`,
    'Paper 1 style: include units and label radians; a diagram can justify which arc belongs to a perimeter.',
    String.raw`Putting $60$ into $s=r\theta$ without converting degrees produces an answer about ten times too large. Use $\pi/3$ instead.`,
    String.raw`Find the arc length of a $4$ cm radius sector with angle $\pi/2$.`,
    String.raw`$s=4(\pi/2)=2\pi$ cm.`],
  ['SL 3.5', 'The unit circle',
    String.raw`On a circle of radius one, the point at angle $\theta$ has coordinates $(\cos\theta,\sin\theta)$. Quadrant signs and symmetry allow exact values for related angles. This extends trigonometry beyond acute right-triangle angles.`,
    String.raw`$\cos^2\theta+\sin^2\theta=1$ follows from the circle equation $x^2+y^2=1$. Adding $2\pi$ leaves the same point. In quadrant II, sine is positive and cosine is negative.`,
    String.raw`For $\theta=5\pi/6$, the reference angle is $\pi/6$ and the terminal point lies in quadrant II. Therefore $\sin(5\pi/6)=1/2$ and $\cos(5\pi/6)=-\sqrt3/2$. Their quotient gives $\tan(5\pi/6)=-1/\sqrt3$. Check $1/4+3/4=1$.`,
    'Paper 1 style: mark the quadrant and reference angle before writing exact trigonometric values.',
    String.raw`The reference angle alone does not determine signs. The actual quadrant does.`,
    String.raw`Find $\sin(7\pi/6)$ and $\cos(7\pi/6)$.`,
    String.raw`Quadrant III with reference angle $\pi/6$: $-1/2$ and $-\sqrt3/2$.`],
  ['SL 3.6', 'Trigonometric identities',
    String.raw`An identity holds for all inputs in its common domain, rather than only for the solutions of one equation. The Pythagorean identity follows from the unit circle. Equivalent forms can replace a sine square with a cosine square or simplify a mixed expression.`,
    String.raw`$\sin^2x+\cos^2x=1$ and $\tan x=\sin x/\cos x$ when $\cos x\neq0$. Dividing the first identity by $\cos^2x$ gives $1+\tan^2x=\sec^2x$ where defined.`,
    String.raw`Suppose $\cos x=3/5$ and $x$ is in quadrant IV. Then $\sin^2x=1-9/25=16/25$. Quadrant IV has negative sine, so $\sin x=-4/5$. Consequently $\tan x=(-4/5)/(3/5)=-4/3$. Substitution into $\sin^2x+\cos^2x=1$ checks the result.`,
    'Paper 1 style: state sign information as well as the identity; a square root by itself has two signs.',
    String.raw`From $\sin^2x=16/25$ it does not follow that $\sin x=4/5$ without a quadrant condition.`,
    String.raw`If $\sin x=5/13$ and $x$ is in quadrant II, find $\cos x$.`,
    String.raw`$\cos^2x=1-25/169=144/169$, and quadrant II gives $\cos x=-12/13$.`],
  ['SL 3.7', 'Trigonometric functions and graphs',
    String.raw`The sine and cosine graphs repeat after a fixed horizontal period. Multiplication outside sets amplitude; multiplication of the input changes the period. A vertical translation changes the midline, so the range is centered on that line.`,
    String.raw`For $y=a\sin(bx)+d$ with $b\neq0$, amplitude is $|a|$, period is $2\pi/|b|$, midline is $y=d$, and range is $[d-|a|,d+|a|]$. Horizontal shifts enter as $b(x-h)$; keep parentheses.`,
    String.raw`For $f(x)=2\sin(3x)+1$, the amplitude is $2$ and period $2\pi/3$. The midline is $y=1$, giving range $[-1,3]$. At $x=0$, $f(0)=1$; at $x=\pi/6$, $3x=\pi/2$ and $f=3$, a maximum. These anchor points determine a sketch of one cycle.`,
    'Paper 1 style: label one full period and the shifted midline rather than drawing an unscaled wave.',
    String.raw`The period of $\sin(3x)$ is $2\pi/3$, not $6\pi$. Input scaling is inverse.`,
    String.raw`Give the amplitude, period and range of $y=3\cos(2x)-1$.`,
    String.raw`Amplitude $3$, period $\pi$, range $[-4,2]$.`],
  ['SL 3.8', 'Trigonometric equations',
    String.raw`A trigonometric equation usually has more than one solution because functions repeat. Find a reference angle, select the quadrants with the correct sign, then include all periods that lie in the requested interval. An inverse-trig button returns only a principal value.`,
    String.raw`$\sin x=\sin\alpha$ gives $x=\alpha+2k\pi$ or $x=\pi-\alpha+2k\pi$ for integer $k$. For cosine and tangent use their corresponding symmetries and periods. Always state whether the interval endpoints are included.`,
    String.raw`Solve $2\sin x=1$ for $0\leq x<2\pi$. Then $\sin x=1/2$. The reference angle is $\pi/6$ and sine is positive in quadrants I and II. Thus $x=\pi/6$ or $x=5\pi/6$. Neither excluded endpoint $2\pi$ is a solution.`,
    'Paper 1 style: show the reference angle and both valid quadrants; Paper 2 can check the interval graphically.',
    String.raw`Returning only $\arcsin(1/2)=\pi/6$ misses the quadrant II solution.`,
    String.raw`Solve $\cos x=0$ for $0\leq x<2\pi$.`,
    String.raw`$x=\pi/2$ or $x=3\pi/2$.`],
  ['AHL 3.9', 'Reciprocal ratios and identities',
    String.raw`Reciprocal trigonometric ratios are convenient shorthand, but each has excluded inputs where its denominator is zero. Their Pythagorean identities follow by dividing $\sin^2x+\cos^2x=1$ by a nonzero sine or cosine square.`,
    String.raw`$\sec x=1/\cos x$, $\csc x=1/\sin x$, and $\cot x=\cos x/\sin x$. Where defined, $1+\cot^2x=\csc^2x$ and $1+\tan^2x=\sec^2x$. Do not cancel across values at which the original functions are undefined.`,
    String.raw`If $\sin x=3/5$ and $\cos x=4/5$, then $\csc x=5/3$ and $\cot x=(4/5)/(3/5)=4/3$. Check $1+(4/3)^2=25/9=(5/3)^2$. The equation is valid because $\sin x\neq0$.`,
    'Paper 1 style: derive an identity from the unit-circle equation instead of treating reciprocal notation as a new operation.',
    String.raw`$\sin^{-1}x$ usually denotes arcsine, not $1/\sin x$. Use $\csc x$ for the reciprocal.`,
    String.raw`If $\cos x=1/2$, what is $\sec x$?`,
    String.raw`$\sec x=2$.`],
  ['AHL 3.10', 'Compound-angle identities',
    String.raw`Compound-angle formulas express the trigonometric value of a sum or difference in terms of the separate angles. They give exact values of less familiar angles and underpin double-angle identities. Signs must follow the particular formula.`,
    String.raw`$\sin(A\pm B)=\sin A\cos B\pm\cos A\sin B$ and $\cos(A\pm B)=\cos A\cos B\mp\sin A\sin B$. Set $B=A$ to get $\sin2A=2\sin A\cos A$.`,
    String.raw`To find $\sin75^\circ$, write $75^\circ=45^\circ+30^\circ$. Then $\sin75^\circ=\sin45^\circ\cos30^\circ+\cos45^\circ\sin30^\circ=(\sqrt2/2)(\sqrt3/2)+(\sqrt2/2)(1/2)=(\sqrt6+\sqrt2)/4$. This is positive and close to one, as the angle suggests.`,
    'Paper 1 style: select special angles whose sum gives the target and keep radicals exact.',
    String.raw`Cosine of a sum has a minus sign in the middle; copying the sine sign gives a wrong identity.`,
    String.raw`Find $\cos75^\circ$ in exact form.`,
    String.raw`$\cos(45^\circ+30^\circ)=(\sqrt6-\sqrt2)/4$.`],
  ['AHL 3.11', 'Relationships among trigonometric functions',
    String.raw`Double-angle and related identities make it possible to move between known values at $x$ and expressions at $2x$. The quadrant of the original angle determines any missing signs. Identity manipulation is also useful for converting an equation into one trigonometric function.`,
    String.raw`$\sin2x=2\sin x\cos x$, $\cos2x=\cos^2x-\sin^2x=1-2\sin^2x=2\cos^2x-1$. These are equal forms of the same identity, not separate restrictions.`,
    String.raw`Suppose $\sin x=4/5$ and $\cos x=3/5$ for an acute $x$. Then $\sin2x=2(4/5)(3/5)=24/25$ and $\cos2x=(3/5)^2-(4/5)^2=-7/25$. The negative cosine is reasonable because $2x$ lies in quadrant II for this triangle.`,
    'Paper 1 style: choose the double-angle form with the fewest unknown quantities.',
    String.raw`The sign of $\cos2x$ is not necessarily the sign of $\cos x$. Doubling may move the terminal side to another quadrant.`,
    String.raw`If $\sin x=1/2$ and $x$ is acute, find $\cos2x$.`,
    String.raw`$1-2(1/2)^2=1/2$.`],
  ['AHL 3.12', 'Vector concepts in two and three dimensions',
    String.raw`A vector has direction and magnitude. Subtracting position vectors gives displacement from one point to another. A unit vector has magnitude one and records direction without distance. Distinguish a point's coordinates from the displacement between points.`,
    String.raw`For $\mathbf v=(v_1,v_2,v_3)$, $|\mathbf v|=\sqrt{v_1^2+v_2^2+v_3^2}$ and its unit direction is $\mathbf v/|\mathbf v|$ when $\mathbf v\neq\mathbf0$. $\overrightarrow{AB}=\mathbf b-\mathbf a$.`,
    String.raw`Let $A=(1,2,3)$ and $B=(4,6,3)$. Then $\overrightarrow{AB}=(4-1,6-2,3-3)=(3,4,0)$ and its magnitude is $\sqrt{9+16}=5$. The unit vector from $A$ toward $B$ is $(3/5,4/5,0)$. Its squared magnitude is $9/25+16/25=1$.`,
    'Paper 1 style: write the subtraction in the correct order; a diagram helps distinguish $AB$ from $BA$.',
    String.raw`$\overrightarrow{BA}$ is the negative of $\overrightarrow{AB}$, not the same vector, even though their lengths are equal.`,
    String.raw`Find the vector from $(2,-1)$ to $(5,3)$.`,
    String.raw`$(3,4)$, of magnitude $5$.`],
  ['AHL 3.13', 'Scalar product and angles',
    String.raw`The scalar or dot product measures directional alignment. A zero dot product for nonzero vectors signals perpendicularity; a negative result signals an obtuse angle between them. It is a number, not a vector.`,
    String.raw`$\mathbf a\cdot\mathbf b=a_1b_1+a_2b_2+a_3b_3=|\mathbf a||\mathbf b|\cos\theta$ for nonzero vectors. Thus $\cos\theta=(\mathbf a\cdot\mathbf b)/(|\mathbf a||\mathbf b|)$.`,
    String.raw`Take $\mathbf a=(1,2,2)$ and $\mathbf b=(2,0,-1)$. Their dot product is $1(2)+2(0)+2(-1)=0$. Both are nonzero, so $\cos\theta=0$ and the vectors are perpendicular. Their magnitudes are $3$ and $\sqrt5$, which are nonzero as required.`,
    'Paper 1 style: show component multiplication and check the vectors are nonzero before concluding perpendicularity.',
    String.raw`A zero vector has zero dot product with everything but has no well-defined direction or angle.`,
    String.raw`Find $(3,-1)\cdot(2,4)$.`,
    String.raw`$3(2)+(-1)(4)=2$.`],
  ['AHL 3.14', 'Vector equations of lines',
    String.raw`A line consists of a fixed point plus all scalar multiples of a nonzero direction vector. The parameter determines how far and which way to travel along the line. Different-looking vector equations can represent the same geometric line.`,
    String.raw`$\mathbf r=\mathbf a+t\mathbf d$, where $\mathbf a$ is a point, $\mathbf d\neq\mathbf0$ is a direction and $t\in\mathbb R$. In three dimensions this gives three scalar equations with the same parameter.`,
    String.raw`The line $\mathbf r=(1,2,0)+t(2,-1,3)$ passes through $(1,2,0)$ when $t=0$. At $t=2$, its coordinates are $(1+4,2-2,0+6)=(5,0,6)$. The direction vector is $(2,-1,3)$; doubling it would describe the same line with a rescaled parameter.`,
    'Paper 1 style: identify a point and nonzero direction, then substitute one shared parameter across coordinates.',
    String.raw`Giving three unrelated parameters for $x$, $y$ and $z$ describes a region rather than one line. Use the same $t$.`,
    String.raw`Give a vector equation for the line through $(0,1,2)$ parallel to $(1,0,-1)$.`,
    String.raw`$\mathbf r=(0,1,2)+t(1,0,-1)$ for $t\in\mathbb R$.`],
  ['AHL 3.15', 'Coincident, parallel, intersecting and skew lines',
    String.raw`In three dimensions, two nonparallel lines need not meet. Skew lines are neither parallel nor intersecting. Compare direction vectors first, then solve for parameters if they are not parallel; all coordinate equations must hold simultaneously.`,
    String.raw`For lines $\mathbf a+s\mathbf u$ and $\mathbf b+t\mathbf v$, proportional nonzero directions indicate parallel or coincident lines. If directions are not proportional, solve $\mathbf a+s\mathbf u=\mathbf b+t\mathbf v$; inconsistency gives skew lines.`,
    String.raw`Consider $L_1=(0,0,0)+s(1,0,0)$ and $L_2=(0,1,1)+t(0,1,0)$. The directions are not proportional. On $L_1$ every point has $z=0$; on $L_2$ every point has $z=1$. They cannot meet, so the lines are skew. They are not parallel because their directions differ.`,
    'Paper 1 style: an inconsistent third coordinate is enough to rule out an intersection after checking direction vectors.',
    String.raw`Two nonparallel lines in the plane intersect, but that two-dimensional rule is false in three dimensions.`,
    String.raw`Are $(0,0,0)+t(1,0,0)$ and $(0,1,0)+s(1,0,0)$ parallel or coincident?`,
    String.raw`Parallel and distinct: every point on the second has $y=1$, unlike the first.`],
  ['AHL 3.16', 'Vector product',
    String.raw`The vector or cross product of two three-dimensional vectors is perpendicular to both. Its magnitude is the area of their parallelogram. Order controls orientation: swapping inputs reverses the result. This makes it useful for plane normals and geometric area.`,
    String.raw`$\mathbf a\times\mathbf b=(a_2b_3-a_3b_2,\ a_3b_1-a_1b_3,\ a_1b_2-a_2b_1)$ and $|\mathbf a\times\mathbf b|=|\mathbf a||\mathbf b|\sin\theta$. The triangle area is half this magnitude.`,
    String.raw`Let $\mathbf a=(1,0,0)$ and $\mathbf b=(0,1,0)$. Then $\mathbf a\times\mathbf b=(0,0,1)$. Its dot product with either input is zero, confirming perpendicularity, and its magnitude $1$ equals the area of the unit square they span. Reversing the order gives $(0,0,-1)$.`,
    'Paper 1 style: check orientation and use a dot product to verify the computed normal.',
    String.raw`The cross product is not commutative: $\mathbf a\times\mathbf b=-\mathbf b\times\mathbf a$.`,
    String.raw`Find $(2,0,0)\times(0,3,0)$ and its magnitude.`,
    String.raw`$(0,0,6)$, magnitude $6$.`],
  ['AHL 3.17', 'Vector equations of planes',
    String.raw`A plane can be described by a point and a normal vector. Every displacement within the plane is perpendicular to that normal. A parametric form instead uses two nonparallel directions lying within the plane.`,
    String.raw`$\mathbf n\cdot(\mathbf r-\mathbf a)=0$ with nonzero normal $\mathbf n$. For $\mathbf n=(A,B,C)$ this becomes $Ax+By+Cz=D$. Alternatively, $\mathbf r=\mathbf a+s\mathbf u+t\mathbf v$ for independent in-plane vectors.`,
    String.raw`Through $(1,0,0)$ with normal $(2,-1,1)$, the equation is $2(x-1)-y+z=0$, or $2x-y+z=2$. The point $(1,1,1)$ satisfies $2(1)-1+1=2$, so it lies in the plane. A point such as $(0,0,0)$ does not.`,
    'Paper 1 style: state the given point and normal, then substitute a point to check the equation.',
    String.raw`A vector parallel to the plane is not a normal. Its dot product with the normal should be zero.`,
    String.raw`Give a plane through the origin with normal $(0,0,1)$.`,
    String.raw`$z=0$, the $xy$-plane.`],
  ['AHL 3.18', 'Intersections of lines and planes',
    String.raw`To intersect a line with a plane, substitute the line's parameter into the plane equation. A single parameter value gives one intersection point; an identity means the whole line lies in the plane; an impossibility means the line is parallel and disjoint.`,
    String.raw`Insert $\mathbf r=\mathbf a+t\mathbf d$ into $\mathbf n\cdot\mathbf r=c$. If $\mathbf n\cdot\mathbf d\neq0$, then $t=(c-\mathbf n\cdot\mathbf a)/(\mathbf n\cdot\mathbf d)$. A zero denominator requires a separate containment check.`,
    String.raw`Intersect $(x,y,z)=(0,0,1)+t(1,2,-1)$ with $x+y+z=4$. Substitution gives $t+2t+(1-t)=1+2t=4$, so $t=3/2$. The point is $(3/2,3,-1/2)$. Check its plane coordinates: $3/2+3-1/2=4$.`,
    'Paper 1 style: solve for the line parameter first, report the point, then check it in the plane.',
    String.raw`The parameter $t=3/2$ is not the intersection point. Substitute it into every coordinate of the line.`,
    String.raw`Where does $(x,y,z)=(1,0,0)+t(0,0,1)$ meet $z=3$?`,
    String.raw`$t=3$, giving $(1,0,3)$.`],
];
