// Each entry is original teaching text. Fields are expanded into individual Markdown lessons by build-course.mjs.
export const lessons = [
  ['SL 1.1', 'Standard form',
    String.raw`Standard form separates a nonzero quantity into a significand and a power of ten. It makes orders of magnitude visible: a small measurement has a negative power, while a large count has a positive power. Scientific notation is particularly useful when a question mixes microscopic and astronomical scales.`,
    String.raw`Write $a\times10^k$, where $1\leq |a|<10$ and $k$ is an integer. For multiplication, multiply the significands and add the exponents; normalize the result afterward. Preserve the precision justified by the inputs.`,
    String.raw`Express $0.0000723$ in standard form: move the decimal point five places right to get $7.23$, hence $0.0000723=7.23\times10^{-5}$. Now multiply $(3.2\times10^5)(4\times10^{-3})$: $3.2(4)\times10^{5-3}=12.8\times10^2=1.28\times10^3$. The final coefficient is in the required interval.`,
    'Paper 1 style: show the exponent arithmetic explicitly. In a context, compare the resulting order of magnitude with the original measurements.',
    String.raw`$12.8\times10^2$ has the right value but is not in standard form. Rewrite it as $1.28\times10^3$.`,
    String.raw`Write $0.0000064$ in standard form and evaluate $(2\times10^4)(3\times10^{-2})$.`,
    String.raw`$6.4\times10^{-6}$ and $6\times10^2=600$.`],
  ['SL 1.2', 'Arithmetic sequences and series',
    String.raw`An arithmetic sequence changes by the same amount at every step. The term index counts the number of moves from the first term: term $n$ is reached after $n-1$ additions of the common difference. A series asks for the sum, not the last term.`,
    String.raw`$u_n=u_1+(n-1)d$ and $S_n=\frac n2[2u_1+(n-1)d]=\frac n2(u_1+u_n)$. These formulas assume terms are indexed from $1$ and the difference $d$ is constant. Reversing the list pairs each first term with a last term and explains the sum formula.`,
    String.raw`Suppose $u_4=14$ and $u_9=34$. Subtract $u_1+3d=14$ from $u_1+8d=34$ to obtain $5d=20$, so $d=4$ and $u_1=2$. Then $S_{12}=\frac{12}{2}[2(2)+11(4)]=6(48)=288$. Check: $u_{12}=46$ and $12(2+46)/2=288$.`,
    'Paper 1 style: set up two term equations before eliminating. Show why your answer is a sum rather than a term.',
    String.raw`Replacing $n-1$ with $n$ gives an incorrect first term when $n=1$. Substitute $n=1$ as a quick diagnostic.`,
    String.raw`If $u_1=5$ and $d=-2$, find $u_8$ and $S_8$.`,
    String.raw`$u_8=5+7(-2)=-9$ and $S_8=8(5-9)/2=-16$.`],
  ['SL 1.3', 'Geometric sequences and series',
    String.raw`Geometric change means multiplication by a constant ratio, not addition of a constant difference. A negative ratio alternates signs. Summing a geometric sequence works by multiplying the whole sum by $r$ and subtracting to cancel the interior terms.`,
    String.raw`$u_n=u_1r^{n-1}$ and $S_n=u_1(1-r^n)/(1-r)$ for $r\neq1$. When $r=1$, every term equals $u_1$, so $S_n=nu_1$. A zero term needs care when inferring a ratio by division.`,
    String.raw`Take $u_1=6$, $r=-\tfrac12$. The first four terms are $6,-3,\tfrac32,-\tfrac34$. Thus $S_4=6-3+\tfrac32-\tfrac34=\tfrac{15}{4}$. The formula agrees: $6[1-(-\tfrac12)^4]/[1-(-\tfrac12)]=6(15/16)/(3/2)=15/4$.`,
    'Paper 1 style: choose the finite sum formula only after identifying the ratio; write parentheses around negative ratios.',
    String.raw`A negative $r$ does not mean the sum must be negative. Track the parity of $n$ before simplifying $r^n$.`,
    String.raw`Find $u_5$ and $S_5$ when $u_1=2$ and $r=3$.`,
    String.raw`$u_5=2(3)^4=162$ and $S_5=2(1-3^5)/(1-3)=242$.`],
  ['SL 1.4', 'Compound interest and depreciation',
    String.raw`A percentage change repeats by a multiplicative factor. Compounding more than once a year changes both the rate per period and the number of periods. Depreciation has a factor smaller than one; inflation-adjusted value divides nominal value by the cumulative price-level factor.`,
    String.raw`For decimal annual rate $i$, $FV=P(1+i/k)^{kt}$ for $k$ compounding periods per year over $t$ years. With a numeric percentage $p$, use $i=p/100$. Annual depreciation at numeric percentage $p$ uses $P(1-p/100)^t$. These are models, not guarantees about actual investments.`,
    String.raw`A deposit of €2400 grows by 3% annually for four years. The factor is $1.03$, so $FV=2400(1.03)^4=2701.22$ euros to the nearest cent. A €18,000 asset that depreciates 20% each year for three years has value $18000(0.80)^3=9216$ euros. The annual change applies to the current value, not the original one.`,
    'Paper 2 style: state the rate units and compounding frequency, calculate with full precision, then round money once.',
    String.raw`Do not use both $0.03$ and a second division by $100$. One represents a decimal rate, the other a percentage conversion.`,
    String.raw`A €1000 balance earns 2% annually for three years. Find its modeled value.`,
    String.raw`$1000(1.02)^3=1061.208$ euros, so €1061.21 to the nearest cent.`],
  ['SL 1.5', 'Introduction to logarithms',
    String.raw`A logarithm answers an exponent question: what power of a given base produces a positive number? It is the inverse operation to exponentiation. Thinking in inverse pairs is more reliable than memorizing isolated log identities.`,
    String.raw`$\log_b x=y\iff b^y=x$, with $b>0$, $b\neq1$, and $x>0$. In particular $\log_b1=0$ and $\log_b b=1$. The graph crosses $(1,0)$ and has no real value for nonpositive arguments.`,
    String.raw`Solve $\log_3 x=-2$. Rewrite in exponential form: $x=3^{-2}=1/9$, which is positive. To solve $2^y=32$, write $32=2^5$ and obtain $y=5$. Substitution verifies both results without a calculator.`,
    'Paper 1 style: convert to exponential form first, and reject any root that makes the original log argument nonpositive.',
    String.raw`$\log_b(-x)$ is not automatically $-\log_b x$; its real domain requires $-x>0$.`,
    String.raw`Solve $\log_5(2x-1)=2$.`,
    String.raw`$2x-1=25$, so $x=13$, satisfying $2x-1>0$.`],
  ['SL 1.6', 'Simple proof',
    String.raw`A proof establishes a statement throughout its stated domain. It starts from definitions or accepted results and uses valid implications. Testing several integers may suggest a pattern but cannot prove a universal claim.`,
    String.raw`For divisibility, exhibit an integer factor: $m\mid N$ means $N=mk$ for some integer $k$. For an identity, simplify one side under the stated domain; do not assume the identity you are trying to prove.`,
    String.raw`Prove that the sum of three consecutive integers is divisible by $3$. Let the integers be $n,n+1,n+2$, where $n\in\mathbb Z$. Their sum is $3n+3=3(n+1)$. Because $n+1$ is an integer, the sum is a multiple of $3$ for every allowed $n$. The quantifier and the integer condition complete the argument.`,
    'Paper 1 style: a clear general representation and a final sentence often matter more than long calculations.',
    String.raw`Checking $1+2+3$ verifies one instance, not all instances. Replace specific values with an arbitrary integer $n$.`,
    String.raw`Show that the difference of the squares of consecutive integers is odd.`,
    String.raw`$(n+1)^2-n^2=2n+1$, which is odd for every integer $n$.`],
  ['SL 1.7', 'Laws of exponents and logarithms',
    String.raw`Exponent laws follow from repeated multiplication and extend consistently to real exponents for positive bases. Log rules translate products into sums because multiplying powers adds exponents. This is a transformation tool, not permission to split every expression inside a log.`,
    String.raw`$a^ma^n=a^{m+n}$ and $(a^m)^n=a^{mn}$ for $a>0$ when real exponents are involved. For $x,y>0$, $\log_b(xy)=\log_b x+\log_b y$ and $\log_b(x/y)=\log_b x-\log_b y$; $\log_b(x^r)=r\log_b x$.`,
    String.raw`Solve $\log_2(8x)=5$. First require $x>0$. Exponentiate: $8x=2^5=32$, hence $x=4$. Alternatively $\log_2(8x)=\log_2 8+\log_2 x=3+\log_2 x$, so $\log_2 x=2$ and $x=4$. Verify $8(4)=32$.`,
    'Paper 1 style: write domains before manipulating logs; Paper 2 may require numerical values through change of base.',
    String.raw`There is no general rule $\log(x+y)=\log x+\log y$. The product rule applies only to multiplication.`,
    String.raw`Solve $\log_3 x+\log_3 9=4$.`,
    String.raw`$\log_3 x+2=4$, so $x=3^2=9>0$.`],
  ['SL 1.8', 'Infinite geometric series',
    String.raw`An infinite sum is defined through its finite partial sums. For a geometric series, the leftover term involves $r^n$, which tends to zero only when the absolute ratio is less than one, unless the first term is zero.`,
    String.raw`If $|r|<1$, then $S_\infty=\lim_{n\to\infty}u_1(1-r^n)/(1-r)=u_1/(1-r)$. For $r=1$ or $|r|>1$ the generic nonzero series does not have a finite sum. At $r=-1$ partial sums alternate and fail to converge.`,
    String.raw`For $u_1=12$ and $r=-1/3$, check $|r|=1/3<1$. Then $S_\infty=12/[1-(-1/3)]=12/(4/3)=9$. A quick sanity check uses partial sums $12,8,9.333\ldots,8.888\ldots$, which oscillate toward $9$.`,
    'Paper 1 style: explicitly state convergence before substituting. In a bouncing-ball context, count upward and downward travel separately.',
    String.raw`A term approaching zero is necessary, but not sufficient for every infinite series to converge. This formula is specific to a geometric series.`,
    String.raw`Find the sum of $5+2.5+1.25+\cdots$ and state why it exists.`,
    String.raw`$r=1/2$, so $|r|<1$ and $S_\infty=5/(1-1/2)=10$.`],
  ['SL 1.9', 'Binomial theorem: nonnegative integer index',
    String.raw`Choosing which factors contribute the second term of a product explains each coefficient of a finite binomial expansion. The term index starts at zero in the summation and at one when naming $T_{r+1}$.`,
    String.raw`$(a+b)^n=\sum_{r=0}^n\binom nr a^{n-r}b^r$ for a nonnegative integer $n$. Here $\binom nr=n!/[r!(n-r)!]$. The expansion terminates after $n+1$ terms.`,
    String.raw`Find the coefficient of $x^2$ in $(x-2)^4$. The general term is $\binom4r x^{4-r}(-2)^r$. Setting $4-r=2$ gives $r=2$. The required coefficient is $\binom42(-2)^2=6(4)=24$. This corresponds to the third term; the full expansion is not needed.`,
    'Paper 1 style: write the general term before solving for the index, and check the index is an integer in range.',
    String.raw`If the second term is negative, its sign depends on $r$. Do not apply an alternating sign after already raising $-2$ to $r$.`,
    String.raw`Find the coefficient of $x^3$ in $(x+1)^5$.`,
    String.raw`Set $5-r=3$, giving $r=2$; the coefficient is $\binom52=10$.`],
  ['AHL 1.10', 'Counting and generalized binomial series',
    String.raw`For counting, decide whether reordering changes an outcome. For generalized binomial expansions, first factor out the constant so the changing part looks like $1+t$. These ideas meet in the factorial products that define generalized coefficients.`,
    String.raw`Ordered selections: $P(n,r)=n!/(n-r)!$; unordered selections: $\binom nr=n!/[r!(n-r)!]$. For non-integer or negative $\alpha$, $(1+t)^\alpha=1+\alpha t+\alpha(\alpha-1)t^2/2!+\cdots$, valid for $|t|<1$. A positive integer index is the terminating special case.`,
    String.raw`Five distinct students sit in a row; two specified students must sit together. Treat them as one block: $4!$ block orders times $2!$ internal orders, giving $48$. Separately, $(1-2x)^{-1}=1+2x+4x^2+\cdots$, valid when $|-2x|<1$, or $|x|<1/2$. Notice that the expansion does not terminate.`,
    'Paper 1 style: explain the choice of permutation versus combination; for a generalized series state the original-variable validity interval.',
    String.raw`$\binom nr$ counts groups, not seats. For series validity, $|x|<1$ is wrong after replacing $x$ with $-2x$.`,
    String.raw`How many ways can 3 of 7 distinct people fill 3 labeled roles? Expand $(1+x)^{-1}$ through $x^2$.`,
    String.raw`$7\cdot6\cdot5=210$ ways; $1-x+x^2+\cdots$ for $|x|<1$.`],
  ['AHL 1.11', 'Partial fractions',
    String.raw`A rational expression with a factored denominator can sometimes be written as simpler fractions. This reverses addition of fractions and helps with integration or algebraic simplification. Divide first if the numerator degree is at least the denominator degree.`,
    String.raw`For distinct linear factors, seek $\dfrac{N(x)}{(x-a)(x-b)}=\dfrac A{x-a}+\dfrac B{x-b}$. Multiply by the denominator and equate coefficients or substitute roots. A repeated factor $(x-a)^2$ requires both $A/(x-a)$ and $B/(x-a)^2$.`,
    String.raw`Decompose $(5x+1)/[(x-1)(x+2)]$. Write $5x+1=A(x+2)+B(x-1)$. At $x=1$, $6=3A$, so $A=2$. At $x=-2$, $-9=-3B$, so $B=3$. Therefore the expression is $2/(x-1)+3/(x+2)$, for $x\neq1,-2$. Recombine to check the numerator.`,
    'Paper 1 style: show the identity after clearing denominators; remember excluded values even when the final algebra looks simpler.',
    String.raw`A repeated linear denominator cannot usually be handled with one fraction alone. Include every power up to its multiplicity.`,
    String.raw`Decompose $(3x+1)/[(x-1)(x+1)]$.`,
    String.raw`$3x+1=2(x+1)+1(x-1)$, giving $2/(x-1)+1/(x+1)$, $x\neq\pm1$.`],
  ['AHL 1.12', 'Complex numbers in Cartesian form',
    String.raw`Complex numbers extend the real line by allowing $i^2=-1$. Cartesian form records a real and imaginary coordinate, so the Argand diagram represents addition geometrically as vector addition. Conjugation reflects a point in the real axis.`,
    String.raw`$z=a+bi$, $\overline z=a-bi$, $|z|=\sqrt{a^2+b^2}$, and $z\overline z=|z|^2$. For $w\neq0$, multiply $z/w$ by $\overline w/\overline w$ to obtain a real denominator.`,
    String.raw`Let $z=2+3i$ and $w=1-2i$. Multiply: $zw=2-4i+3i-6i^2=8-i$. Plot $z$ at $(2,3)$ on the Argand plane. Its modulus is $\sqrt{2^2+3^2}=\sqrt{13}$ and its conjugate is $2-3i$. The modulus is the distance from the origin.`,
    'Paper 1 style: draw or describe the Argand position and simplify every occurrence of $i^2$.',
    String.raw`The modulus of $a+bi$ is not $a+b$. It is a nonnegative distance found by Pythagoras.`,
    String.raw`Simplify $(3+i)(2-i)$ and find $|3+i|$.`,
    String.raw`$7-i$ and $\sqrt{10}$.`],
  ['AHL 1.13', 'Polar and Euler form',
    String.raw`Polar form records distance from the origin and angle from the positive real axis. Multiplication then adds arguments and multiplies moduli. Euler form packages the same geometry using complex exponentials. The principal argument must use the correct quadrant.`,
    String.raw`$z=r(\cos\theta+i\sin\theta)=re^{i\theta}$ for $r=|z|>0$; arguments differ by $2\pi k$. De Moivre: $z^n=r^n[\cos(n\theta)+i\sin(n\theta)]$. For $z=0$ the argument is undefined.`,
    String.raw`For $z=-1+i\sqrt3$, $r=\sqrt{1+3}=2$. The point lies in quadrant II, so $\theta=2\pi/3$. Hence $z=2e^{2\pi i/3}$ and $z^3=8e^{2\pi i}=8$. Cartesian checking by multiplication reaches the same result, but polar form is shorter for powers.`,
    'Paper 1 style: justify the quadrant, state an appropriate argument, and use periodicity when listing all roots.',
    String.raw`$\arctan(b/a)$ alone gives a reference angle and can select the wrong quadrant. Plot the signs of $a$ and $b$ first.`,
    String.raw`Write $1+i$ in polar form with $0\leq\theta<2\pi$.`,
    String.raw`$\sqrt2e^{i\pi/4}=\sqrt2(\cos\frac\pi4+i\sin\frac\pi4)$.`],
  ['AHL 1.14', 'Complex roots and conjugate pairs',
    String.raw`Polynomials with real coefficients have conjugate nonreal roots: conjugating the entire equation leaves the real coefficients unchanged. This gives a way to reconstruct a real quadratic from one complex root and to factor higher-degree polynomials.`,
    String.raw`If $p(x)$ has real coefficients and $p(a+bi)=0$ with $b\neq0$, then $p(a-bi)=0$. A conjugate pair gives the real factor $(x-a-bi)(x-a+bi)=(x-a)^2+b^2$. The conclusion need not hold when coefficients are not real.`,
    String.raw`One root of $x^2-2x+5$ is $1+2i$. Its conjugate $1-2i$ is also a root. Multiplying the factors gives $[x-(1+2i)][x-(1-2i)]=(x-1)^2+4=x^2-2x+5$. Their sum is $2$ and product is $5$, matching Vieta's relations.`,
    'Paper 1 style: state why conjugation applies before writing down the partner root.',
    String.raw`A complex root does not force its conjugate to be a root of a polynomial with complex coefficients. Check the coefficient domain.`,
    String.raw`A real-coefficient polynomial has root $-2+3i$. What real quadratic factor must divide it?`,
    String.raw`$(x+2)^2+9=x^2+4x+13$.`],
  ['AHL 1.15', 'Induction, contradiction and counterexample',
    String.raw`These methods answer different logical tasks. Induction proves a claim on an integer domain step by step. Contradiction assumes the negation and derives an impossibility. A counterexample disproves a universal statement with one legal failing case.`,
    String.raw`For induction, show $P(n_0)$, assume $P(k)$, derive $P(k+1)$, then conclude. For a counterexample, exhibit $c$ in the stated domain with $P(c)$ false. A finite list of successful tests cannot establish $\forall n\,P(n)$.`,
    String.raw`Prove $1+3+\cdots+(2n-1)=n^2$ for positive integers. Base $n=1$: $1=1^2$. Assume the sum of the first $k$ odd integers is $k^2$. Add the next odd integer $2k+1$: $k^2+(2k+1)=(k+1)^2$. Therefore the formula holds for all positive integers by induction. To disprove $x^2\geq x$ for every real $x$, use $x=1/2$: $1/4<1/2$.`,
    'Paper 1 style: label the four induction steps; choose a counterexample only for a false universal claim.',
    String.raw`The induction hypothesis is assumed only for the step. It is not the final proof until the base and implication have both been established.`,
    String.raw`Give a counterexample to “every integer has a positive square” and explain why it works.`,
    String.raw`$n=0$ is an integer and $0^2=0$ is not positive.`],
  ['AHL 1.16', 'Systems of linear equations',
    String.raw`A linear system asks for values satisfying all equations at once. Elimination combines equations to remove one variable. Geometrically, two lines in the plane can cross once, coincide, or be parallel without meeting. A numerical solver is a check, not a substitute for interpreting which case occurs.`,
    String.raw`For $a_1x+b_1y=c_1$ and $a_2x+b_2y=c_2$, a unique solution exists when $a_1b_2-a_2b_1\neq0$. If the determinant is zero, compare the equations to distinguish infinitely many solutions from none.`,
    String.raw`Solve $2x+y=7$ and $x-y=2$. Add the equations to eliminate $y$: $3x=9$, giving $x=3$. Substitute into $x-y=2$ to get $y=1$. Check both: $2(3)+1=7$ and $3-1=2$. In three-variable problems, eliminate systematically and back-substitute.`,
    'Paper 1 style: keep a clean chain of equivalent equations. Paper 2 technology can verify a solution but should not hide inconsistency.',
    String.raw`If elimination produces $0=5$, do not divide by zero or claim a solution. It signals an inconsistent system.`,
    String.raw`Solve $x+y=5$ and $2x-y=4$.`,
    String.raw`Adding gives $3x=9$, so $x=3$ and $y=2$.`],
];
