export const lessons = [
  ['SL 4.1', 'Data reliability and sampling',
    String.raw`Statistical conclusions depend on how data were collected. A large sample does not automatically fix selection bias. A representative design should give relevant population members a known opportunity to be included and should avoid wording that steers answers.`,
    String.raw`A simple random sample selects units so every eligible unit has an equal chance under the design. A stratified sample divides the population into meaningful groups and samples within each group. Reliability, validity and representativeness describe different properties of a study.`,
    String.raw`A school has $600$ lower-year and $400$ upper-year students. For a proportional stratified sample of $100$, choose $100(600/1000)=60$ lower-year and $100(400/1000)=40$ upper-year students randomly within the two strata. Surveying only the first 100 students to enter the library would be convenient but could overrepresent frequent library users.`,
    'Paper 2 style: state the population, explain the sampling mechanism, and name a specific possible bias rather than only saying “biased.”',
    String.raw`A random draw from an incomplete list is still vulnerable to coverage bias. Ask who never appeared on the list.`,
    String.raw`A population is 30% group A. In a proportional sample of 80, how many should come from A?`,
    String.raw`$0.30(80)=24$, selected randomly within A.`],
  ['SL 4.2', 'Histograms, cumulative frequency and box plots',
    String.raw`Different statistical graphs communicate different aspects of a distribution. A histogram shows frequency through bar *area* when class widths vary. A cumulative-frequency curve adds counts up to each boundary. A box plot summarizes quartiles but does not show every feature of the raw distribution.`,
    String.raw`Histogram frequency density $=\text{class frequency}/\text{class width}$. The cumulative frequency at a boundary counts all observations below that boundary under the stated class convention. Interquartile range $Q_3-Q_1$ measures the middle half's spread.`,
    String.raw`Suppose intervals $[10,20)$ and $[20,25)$ contain $8$ and $10$ observations. Their widths are $10$ and $5$, so histogram heights are $8/10=0.8$ and $10/5=2$. The bar areas are $0.8(10)=8$ and $2(5)=10$, reproducing the frequencies. Cumulative frequency at $25$ is $18$.`,
    'Paper 2 style: label axes with units and use density rather than raw frequency when widths differ.',
    String.raw`Equal bar height is not equal frequency for unequal class widths. Compare the bar areas.`,
    String.raw`A class of width $4$ has frequency $12$. Find its histogram density.`,
    String.raw`$12/4=3$ observations per unit of class width.`],
  ['SL 4.3', 'Averages, grouped estimates and standard deviation',
    String.raw`Measures of center and spread answer different questions. The mean uses every numerical value and is sensitive to outliers; the median locates the middle rank. A grouped-data mean uses class midpoints and is an estimate because exact values within each class are unknown.`,
    String.raw`Population mean $\mu=\sum x_i/N$ and population standard deviation $\sigma=\sqrt{\sum(x_i-\mu)^2/N}$. A sample standard deviation convention instead uses $N-1$ in the denominator; state or select the intended measure.`,
    String.raw`For $2,4,4,6$, the mean is $(2+4+4+6)/4=4$ and the median is also $4$. Squared deviations from the mean are $4,0,0,4$, summing to $8$. The population variance is $8/4=2$ and population standard deviation is $\sqrt2$. Treating the same data as a sample would give $s=\sqrt{8/3}$ instead.`,
    'Paper 2 style: know whether the calculator reports population or sample standard deviation and use the symbol requested.',
    String.raw`Do not describe an estimated grouped mean as exact when the class members' individual values were not supplied.`,
    String.raw`Find the mean and median of $1,2,9$.`,
    String.raw`Mean $4$; median $2$. The large value pulls the mean upward.`],
  ['SL 4.4', 'Pearson correlation and regression of y on x',
    String.raw`Correlation measures strength and direction of an approximately linear association, not whether one variable causes another. A regression line of $y$ on $x$ predicts a response $y$ from a given $x$ by minimizing vertical squared residuals.`,
    String.raw`Pearson's coefficient $r$ lies between $-1$ and $1$. The least-squares line is commonly written $\hat y=a+bx$. Use it within the observed range with caution; extrapolation can be unreliable. Check the scatter plot for curvature and outliers.`,
    String.raw`For points $(1,2),(2,4),(3,6)$, every observation lies on $y=2x$, so the sample has perfect positive linear correlation $r=1$. The regression of $y$ on $x$ is $\hat y=2x$. Predicting at $x=2.5$ gives $\hat y=5$, an interpolation between recorded inputs. This pattern alone cannot establish causation.`,
    'Paper 2 style: interpret the direction of $r$, write the correct dependent variable on the left, and identify predictions outside the data range.',
    String.raw`Do not substitute an observed $y$ into the $y$-on-$x$ equation to claim an $x$-on-$y$ regression unless that second line has been fitted.`,
    String.raw`A fitted line is $\hat y=3+2x$. Predict $y$ at $x=4$.`,
    String.raw`$\hat y=3+8=11$.`],
  ['SL 4.5', 'Probability concepts and expected counts',
    String.raw`Probability quantifies uncertainty between zero and one. With equally likely outcomes, favorable cases can be counted relative to all possible cases. An expected count over repeated trials is an average prediction, not a guarantee for any particular batch.`,
    String.raw`For equally likely outcomes, $P(A)=\#A/\#\Omega$. In $n$ comparable trials with event probability $p$, the expected number of occurrences is $np$. A complement has probability $P(A^c)=1-P(A)$.`,
    String.raw`Two fair dice have $36$ equally likely ordered outcomes. A sum of $7$ occurs in six ordered pairs: $(1,6),(2,5),(3,4),(4,3),(5,2),(6,1)$. Thus $P(\text{sum }7)=6/36=1/6$. In $120$ independent repetitions, the expected number of such sums is $120(1/6)=20$; exactly $20$ need not occur.`,
    'Paper 1 style: make the sample space explicit and distinguish an ordered pair from an unordered selection.',
    String.raw`An expected count of $20$ does not mean every set of $120$ rolls contains exactly $20$ successes.`,
    String.raw`A fair coin is tossed 50 times. How many heads are expected?`,
    String.raw`$50(1/2)=25$ on average.`],
  ['SL 4.6', 'Combined, conditional and independent events',
    String.raw`The addition rule corrects double counting in overlapping events. Conditional probability changes the reference population to those outcomes where the condition holds. Independence means learning one event does not change the probability of the other; it is not the same as mutual exclusivity.`,
    String.raw`$P(A\cup B)=P(A)+P(B)-P(A\cap B)$; if $P(B)>0$, $P(A\mid B)=P(A\cap B)/P(B)$. Independence is $P(A\cap B)=P(A)P(B)$. Mutual exclusivity means $P(A\cap B)=0$.`,
    String.raw`Let $P(A)=0.6$, $P(B)=0.5$ and $P(A\cap B)=0.2$. Then $P(A\cup B)=0.6+0.5-0.2=0.9$. Also $P(A\mid B)=0.2/0.5=0.4$. Since $P(A)P(B)=0.3\neq0.2$, the events are not independent. They are not mutually exclusive because their intersection has positive probability.`,
    'Paper 2 style: draw a Venn diagram or probability tree and state what the conditional denominator represents.',
    String.raw`“Independent” does not mean “cannot happen together.” Nontrivial mutually exclusive events are generally dependent.`,
    String.raw`If $P(A)=0.4$, $P(B)=0.3$ and $P(A\cap B)=0.1$, find $P(A\cup B)$.`,
    String.raw`$0.4+0.3-0.1=0.6$.`],
  ['SL 4.7', 'Discrete random variables',
    String.raw`A discrete random variable assigns numbers to outcomes and has a probability for each attainable value. Expected value is the long-run weighted average. Variance measures squared deviation from that average and can be computed from a second moment.`,
    String.raw`For a discrete $X$, $\sum_xP(X=x)=1$, $E(X)=\sum_x xP(X=x)$ and $\operatorname{Var}(X)=E(X^2)-[E(X)]^2$. Probabilities must be nonnegative; standard deviation is the square root of variance.`,
    String.raw`Let $P(X=0)=1/4$, $P(X=1)=1/2$, $P(X=2)=1/4$. The probabilities sum to one. $E(X)=0+1/2+2/4=1$. Also $E(X^2)=0+1/2+4/4=3/2$, so $\operatorname{Var}(X)=3/2-1=1/2$ and $\sigma=\sqrt{1/2}$.`,
    'Paper 1 style: verify the distribution before calculating its expectation and variance.',
    String.raw`Variance is not $E(X^2)-E(X)$. Subtract the *square* of the mean.`,
    String.raw`If $X$ is $0$ or $2$ with probability $1/2$ each, find $E(X)$.`,
    String.raw`$0(1/2)+2(1/2)=1$.`],
  ['SL 4.8', 'Binomial distribution',
    String.raw`A binomial random variable counts successes across a fixed number of independent trials, each with the same success probability. Check these assumptions before using the formula. A changing probability or dependent draws without replacement may call for another model.`,
    String.raw`For $X\sim B(n,p)$, $P(X=k)=\binom nk p^k(1-p)^{n-k}$ for integers $0\leq k\leq n$. Its mean is $np$ and variance $np(1-p)$. State what “success” means in context.`,
    String.raw`Four independent attempts succeed with probability $1/4$ each. For exactly two successes, $P(X=2)=\binom42(1/4)^2(3/4)^2=6(1/16)(9/16)=27/128\approx0.21094$. The binomial coefficient counts the six possible positions of the two successes. The expected count is $4(1/4)=1$.`,
    'Paper 2 style: identify $n$, $p$ and $k$; use the GDC for a cumulative probability when many values are summed.',
    String.raw`For “at least two,” $P(X=2)$ alone is insufficient. Add $P(X=2),P(X=3)$ and $P(X=4)$ or use a complement.`,
    String.raw`For $X\sim B(3,1/2)$, find $P(X=3)$.`,
    String.raw`$\binom33(1/2)^3=1/8$.`],
  ['SL 4.9', 'Normal distribution',
    String.raw`A normal model is a continuous, symmetric bell-shaped distribution described by a mean and standard deviation. Areas under its curve are probabilities. A single exact value has probability zero, while an interval has a nonzero area.`,
    String.raw`If $X\sim N(\mu,\sigma^2)$ with $\sigma>0$, then $Z=(X-\mu)/\sigma\sim N(0,1)$. The cumulative function $\Phi(z)=P(Z\leq z)$ is evaluated with a table or technology. Normality is a modeling assumption, not a property of every dataset.`,
    String.raw`Suppose $X\sim N(100,15^2)$. For $X<115$, standardize: $z=(115-100)/15=1$. Thus $P(X<115)=\Phi(1)\approx0.8413$. By symmetry $P(X>115)\approx0.1587$. Since the distribution is continuous, writing $<$ or $\leq$ at $115$ makes no difference.`,
    'Paper 2 style: sketch the shaded region, standardize, and check whether the requested tail is above or below one half.',
    String.raw`In $N(\mu,\sigma^2)$ the second parameter is a variance, not the standard deviation. $N(100,15^2)$ has $\sigma=15$.`,
    String.raw`For $X\sim N(0,1)$, estimate $P(X>0)$.`,
    String.raw`$0.5$ by symmetry about the mean.`],
  ['SL 4.10', 'Regression of x on y',
    String.raw`When the goal is to predict $x$ from an observed $y$, fit the regression of $x$ on $y$. This minimizes horizontal squared prediction errors in the original coordinate plot, not the vertical errors used for $y$ on $x$. The two regression lines are generally not algebraic inverses.`,
    String.raw`Write the fitted line as $\hat x=c+dy$ when predicting $x$ from $y$. Perfectly linear data have $|r|=1$ and make the two lines inverse functions; otherwise fitting direction changes the coefficients.`,
    String.raw`For observations $(x,y)=(1,2),(2,4),(3,6)$, the relationship is exactly $x=y/2$. The regression of $x$ on $y$ is therefore $\hat x=0.5y$. Given $y=5$, predict $x=2.5$. In less-than-perfect data, you would fit a fresh $x$-on-$y$ line rather than rearranging the $y$-on-$x$ line.`,
    'Paper 2 style: state clearly which variable is predicted and which is supplied before using calculator regression output.',
    String.raw`Solving $\hat y=a+bx$ for $x$ does not generally give the least-squares $x$-on-$y$ regression.`,
    String.raw`If an $x$-on-$y$ line is $\hat x=2+0.3y$, predict $x$ at $y=10$.`,
    String.raw`$\hat x=2+3=5$.`],
  ['SL 4.11', 'Conditional probabilities and independence tests',
    String.raw`A two-way table or probability tree exposes which group is used as a denominator. To test independence, compare a conditional probability with its unconditional counterpart, or compare the intersection with the product of marginals. Either method requires the relevant probabilities to be defined.`,
    String.raw`If $P(B)>0$, independence is equivalent to $P(A\mid B)=P(A)$. It is also equivalent to $P(A\cap B)=P(A)P(B)$. Mutually exclusive positive-probability events cannot be independent.`,
    String.raw`Suppose $P(A)=0.5$, $P(B)=0.4$ and $P(A\cap B)=0.2$. Then $P(A\mid B)=0.2/0.4=0.5=P(A)$. The product test agrees: $0.5(0.4)=0.2$. These two events are independent in the modeled probability space, but they still overlap.`,
    'Paper 1 style: state the test used and compute both sides; avoid concluding independence from visual similarity in a small sample alone.',
    String.raw`$P(A\mid B)$ divides by $P(B)$, not $P(A)$. Read the condition after the vertical bar as the new reference population.`,
    String.raw`If $P(A)=0.3$ and $P(B)=0.4$ are independent, find $P(A\cap B)$.`,
    String.raw`$0.3(0.4)=0.12$.`],
  ['SL 4.12', 'Z-scores and inverse normal calculations',
    String.raw`A z-score reports how many standard deviations a measurement lies above or below the mean. Inverse normal calculations work in reverse: a specified cumulative area determines a cutoff. With two independent percentile conditions, one may solve for an unknown mean and spread.`,
    String.raw`$z=(x-\mu)/\sigma$ and $x=\mu+z\sigma$ with $\sigma>0$. For a lower-tail probability $p$, use the standard-normal quantile $z_p=\Phi^{-1}(p)$. Check whether the question instead specifies an upper tail.`,
    String.raw`For a normal model with $\mu=50$ and $\sigma=10$, find its 90th percentile. Technology gives $z_{0.90}\approx1.28155$. Therefore $x=50+10(1.28155)\approx62.82$. Check that the result is above the mean, since 90% of modeled values lie below it.`,
    'Paper 2 style: record whether the input area is cumulative from the left, then keep enough digits of the z-value before rounding.',
    String.raw`Using $0.10$ instead of $0.90$ finds the 10th percentile, on the opposite side of the mean.`,
    String.raw`A score is $70$ with mean $50$ and standard deviation $10$. Find its z-score.`,
    String.raw`$(70-50)/10=2$.`],
  ['AHL 4.13', 'Bayes theorem',
    String.raw`Bayes theorem updates a probability after new evidence. A positive test can be more likely among affected people yet still have a modest positive predictive value when the condition is rare. A probability tree or frequency table makes the denominators transparent.`,
    String.raw`$P(A\mid B)=P(B\mid A)P(A)/P(B)$ when $P(B)>0$, where $P(B)=P(B\mid A)P(A)+P(B\mid A^c)P(A^c)$ for a two-case partition. Name the prior, likelihood and evidence before substituting.`,
    String.raw`A condition affects $1\%$ of people; sensitivity is $90\%$ and the false-positive rate is $5\%$. The joint chance of condition and positive test is $0.01(0.90)=0.009$. All positives have probability $0.009+0.99(0.05)=0.0585$. Hence $P(\text{condition}\mid\text{positive})=0.009/0.0585\approx0.1538$, or about $15.4\%$.`,
    'Paper 2 style: draw the tree first so the false-positive branch is included in the denominator.',
    String.raw`Sensitivity $P(+\mid A)$ is not the same as positive predictive value $P(A\mid+)$. Reverse the conditioning with Bayes.`,
    String.raw`If $P(A)=1/2$, $P(+\mid A)=1$ and $P(+\mid A^c)=1/2$, find $P(A\mid+)$.`,
    String.raw`$(1/2)/[(1/2)+(1/2)(1/2)]=2/3$.`],
  ['AHL 4.14', 'Properties of random variables',
    String.raw`Discrete distributions assign mass to individual values; continuous distributions assign probability to intervals through an area under a density curve. Both use expectation and variance, but a continuous single point has zero probability under an ordinary density.`,
    String.raw`For a continuous density $f(x)\geq0$, $\int_{-\infty}^\infty f(x)\,dx=1$, $P(a<X<b)=\int_a^b f(x)\,dx$ and $E(X)=\int_{-\infty}^\infty x f(x)\,dx$ when the integrals exist. Linear transforms obey $E(aX+b)=aE(X)+b$.`,
    String.raw`Take $f(x)=2x$ on $0<x<1$, zero elsewhere. Its total area is $\int_0^1 2x\,dx=[x^2]_0^1=1$, so it is a density. $P(X<1/2)=\int_0^{1/2}2x\,dx=1/4$. The expected value is $E(X)=\int_0^1 2x^2\,dx=2/3$. In contrast $P(X=1/2)=0$.`,
    'Paper 2 style: check normalization before using a proposed density, and state whether an endpoint matters.',
    String.raw`The height $f(1/2)=1$ is a density value, not $P(X=1/2)$. Integrate over an interval to get a probability.`,
    String.raw`If $E(X)=3$, find $E(2X+1)$.`,
    String.raw`$2E(X)+1=7$.`],
];
