import { BookOpen, CircleHelp, Radio } from 'lucide-react';

/** Evidence notes, not a product efficacy claim. */
export function FocusScience() {
  return <section className="mt-16 border-t border-line pt-12" aria-labelledby="focus-science-heading">
    <p className="section-label mb-3">A considered explanation / not a promise</p><h2 id="focus-science-heading" className="text-[clamp(2rem,4vw,3.1rem)] font-semibold tracking-[-0.055em]">Why a study room might help<span className="text-faint">.</span></h2>
    <p className="mt-4 max-w-[810px] text-[14px] leading-[1.8] text-muted">A quiet video and familiar background sound can help some people settle into a task. Those effects are personal and contextual. Here is a careful distinction between a social cue, a measurable auditory-brain response, and a claim that a particular soundtrack improves your grades.</p>
    <div className="mt-9 grid gap-4 md:grid-cols-2">
      <article className="rounded-2xl border border-line bg-surface p-6 sm:p-8"><BookOpen size={22} strokeWidth={1.6} /><h3 className="mt-5 text-[22px] font-semibold tracking-tight">The social-norm cue</h3>
        <p className="mt-4 text-[13px] leading-[1.8] text-muted">A “study with me” recording shows someone choosing to sit down and work. It can provide a visible start signal, a rough session structure and a sense of company. In social psychology, people sometimes adapt their behavior to cues about what others are doing. Some learners describe working alongside another person as “body doubling.” These descriptions do not show that a prerecorded video will improve everybody's attention or that a real social relationship exists with its creator.</p>
        <p className="mt-3 text-[13px] leading-[1.8] text-muted">If you already have a clear task, a low-key companion may make getting started feel less solitary. If the screen becomes something to watch, the same video can become a distraction. Try a small personal comparison: set a specific goal, do one 25-minute session with a study video and another in quiet conditions, and note both what you completed and how you felt. Do not confuse a pleasant feeling with proof of better learning or long-term recall.</p>
      </article>
      <article className="rounded-2xl border border-line bg-surface p-6 sm:p-8"><Radio size={22} strokeWidth={1.6} /><h3 className="mt-5 text-[22px] font-semibold tracking-tight">What phase locking means</h3>
        <p className="mt-4 text-[13px] leading-[1.8] text-muted">Sound pressure can rise and fall rhythmically. If a neural signal measured over repeated presentations follows the timing of that acoustic envelope, researchers may call the relationship stimulus-brain coupling or phase locking. This describes statistical alignment in a measurement. It is not evidence that a person's entire brain is forced into one frequency, nor that every cognitive process is synchronized. The precise sound pattern, modulation depth, task, listener and measurement method all matter.</p>
        <p className="mt-3 text-[13px] leading-[1.8] text-muted">A 2024 <em>Communications Biology</em> paper by Woods and colleagues examined music with controlled amplitude modulations. Its experiments reported stronger stimulus-brain coupling in EEG for some rapidly modulated music and effects on sustained-attention tasks that varied with attentional difficulties and timing. In a later comparison, modulation near 16 Hz helped participants with more self-reported ADHD symptoms more than some other tested rates. The authors describe a possible mechanism, not a universal treatment or a guaranteed result in everyday study. Their sound stimuli and lab tasks are not the six ambient mixes generated on this page.</p>
      </article>
    </div>
    <div className="mt-4 flex items-start gap-4 rounded-xl border border-line p-5 text-[12px] leading-[1.8] text-muted sm:p-6"><CircleHelp size={20} className="mt-0.5 shrink-0 text-ink" /><div><strong className="text-ink">What this studio does and does not do.</strong> Our audio layers contain gentle filtered noise, tones and slow sound-design motion. They do not reproduce the published experimental stimuli and were not tested for neural effects. The videos come from external creators; their effects are not measured by this app. Choose comfortable volume or silence, take breaks and use the tool only if it helps your own work. Source: <a href="https://doi.org/10.1038/s42003-024-07026-3" target="_blank" rel="noopener noreferrer" className="font-semibold text-ink underline underline-offset-4">Woods et al., Communications Biology (2024)</a>, for the experimental methods and results. Those results are limited to the conditions studied.</div></div>
  </section>;
}
