const F=(name,paper,build)=>({name,paper,build});
const Q=(prompt,...steps)=>({prompt,steps:steps.map(text=>[1,text])});
const at=(xs,k)=>xs[k%xs.length];
export const families={
 'SL 5.1':[
  F('secant-toward-tangent','P1',k=>{const a=at([1,2,3,4],k),h=at([1,0.5,0.25,0.125],k);return Q(String.raw`For $f(x)=x^2$, find the secant gradient from $x=${a}$ to $x=${a+h}$, then state its limiting gradient as the interval shrinks.`,String.raw`For a general nonzero $h$, $[f(${a}+h)-f(${a})]/h=[(${a}+h)^2-${a*a}]/h$.`,String.raw`Simplification gives $${2*a}+h$, so at $h=${h}$ the secant gradient is $${2*a+h}$.`,String.raw`As $h\to0$, this approaches the tangent gradient $${2*a}$.`);}),
  F('difference-quotient','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find $f'(${a})$ from the difference quotient for $f(x)=x^2+${a}x$.`,String.raw`$[f(${a}+h)-f(${a})]/h=[2(${a})h+h^2+${a}h]/h$ for $h\neq0$.`,String.raw`After cancellation the expression is $${3*a}+h$.`,String.raw`Let $h\to0$ to obtain $f'(${a})=${3*a}$.`);}),
  F('average-vs-instant','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`A position is $s(t)=${a}t^2$ m. Compare average velocity on $[1,2]$ s with instantaneous velocity at $t=1$ s.`,String.raw`Average velocity $=[s(2)-s(1)]/(2-1)=${a}(4-1)=${3*a}$ m/s.`,String.raw`$v(t)=ds/dt=${2*a}t$, so $v(1)=${2*a}$ m/s.`, 'The two rates differ because the position graph bends rather than remaining a straight line.');}),
 ],
 'SL 5.2':[
  F('quadratic-monotonic','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find intervals of increase and decrease of $f(x)=x^2-${2*a}x$ on the real line.`,String.raw`$f'(x)=2x-${2*a}=2(x-${a})$.`,String.raw`The derivative is negative for $x<${a}$ and positive for $x>${a}$.`,String.raw`Thus $f$ decreases on $(-\infty,${a})$ and increases on $(${a},\infty)$.`);}),
  F('flat-not-extreme','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $g(x)=(x-${a})^3$, find its stationary point and explain why it is not an extremum.`,String.raw`$g'(x)=3(x-${a})^2$, so it vanishes only at $x=${a}$.`,String.raw`$g'(x)>0$ on both sides of $${a}$, so the function keeps increasing.`,String.raw`The point $(${a},0)$ is stationary but not a local maximum or minimum.`);}),
  F('maximum-sign-change','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Classify the stationary point of $h(x)=-(x-${a})^2+${b}$ using the sign of $h'$.`,String.raw`$h'(x)=-2(x-${a})$, zero at $x=${a}$.`,String.raw`It is positive to the left and negative to the right of $${a}$.`,String.raw`Therefore $(${a},${b})$ is a local maximum.`);}),
 ],
 'SL 5.3':[
  F('differentiate-polynomial','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`Differentiate $f(x)=${a}x^3+${b}x^2-${a}x+7$ with respect to $x$.`,String.raw`Differentiate the cubic term to get $${3*a}x^2$ and the quadratic to get $${2*b}x$.`,String.raw`The linear derivative is $-${a}$ and the constant derivative is $0$.`,String.raw`Thus $f'(x)=${3*a}x^2+${2*b}x-${a}$.`);}),
  F('negative-power','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $f(x)=${a}x^{-2}$, find $f'(x)$ and its real domain.`,String.raw`The original $x^{-2}=1/x^2$ excludes $x=0$.`,String.raw`By the power rule, $f'(x)=${a}(-2)x^{-3}=-${2*a}x^{-3}$.`, 'The derivative is defined for all real $x$ except zero, just like the original expression.');}),
  F('evaluate-derivative','P1',k=>{const a=at([1,2,3,4],k),x=at([1,2,3,4],k);return Q(String.raw`If $g(x)=x^3+${a}x$, evaluate $g'(${x})$ exactly.`,String.raw`Differentiate first: $g'(x)=3x^2+${a}$.`,String.raw`At $x=${x}$ the value is $3(${x})^2+${a}$.`,String.raw`The tangent gradient is $${3*x*x+a}$, not the function value $g(${x})$.`);}),
 ],
 'SL 5.4':[
  F('tangent-parabola','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the tangent equation to $y=x^2$ at $x=${a}$.`,String.raw`The contact point is $(${a},${a*a})$.`,String.raw`Derivative $dy/dx=2x$ gives tangent gradient $${2*a}$.`,String.raw`Equation: $y-${a*a}=${2*a}(x-${a})$.`);}),
  F('normal-parabola','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the normal equation to $y=x^2$ at $x=${a}$.`,String.raw`The curve point is $(${a},${a*a})$ and tangent gradient is $${2*a}\neq0$.`,String.raw`The perpendicular gradient is $-1/${2*a}$.`,String.raw`Normal: $y-${a*a}=-(x-${a})/${2*a}$.`);}),
  F('vertical-normal','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`For $y=(x-${a})^2+${b}$, give the tangent and normal at its vertex.`,String.raw`Vertex is $(${a},${b})$ and derivative $2(x-${a})$ is zero there.`,String.raw`The tangent is horizontal: $y=${b}$.`,String.raw`The normal is vertical: $x=${a}$, not a line with finite slope $-1/0$.`);}),
 ],
 'SL 5.5':[
  F('signed-vs-area','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $y=x$ on $[-${a},${a}]$, find signed integral and total geometric area.`,String.raw`Symmetry gives $\int_{-${a}}^{${a}}x\,dx=0$ because positive and negative contributions cancel.`,String.raw`Each triangular side has area $${a}^2/2=${a*a}/2$.`,String.raw`Total geometric area is $${a*a}$ square units, not zero.`);}),
  F('elementary-definite','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Evaluate $\int_0^{${a}}2x\,dx$ and interpret the area under the nonnegative curve.`,String.raw`An antiderivative of $2x$ is $x^2$.`,String.raw`Apply bounds: $[x^2]_0^{${a}}=${a*a}-0=${a*a}$.`,String.raw`Since $2x\geq0$ on this interval, area is $${a*a}$ square units.`);}),
  F('integration-constant','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`Find an antiderivative $F$ of $2x$ satisfying $F(1)=${a}$.`,String.raw`The general antiderivative is $F(x)=x^2+C$.`,String.raw`Use $F(1)=1+C=${a}$, hence $C=${a-1}$.`,String.raw`One required function is $F(x)=x^2+${a-1}$; differentiating returns $2x$.`);}),
 ],
 'SL 5.6':[
  F('chain-rule-power','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Differentiate $f(x)=(x^2+${a})^3$ and show the inner derivative.`,String.raw`Outer derivative is $3(x^2+${a})^2$.`, 'The inside $x^2+a$ has derivative $2x$.',String.raw`Chain rule gives $f'(x)=6x(x^2+${a})^2$.`);}),
  F('product-rule','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Differentiate $f(x)=x^2(x+${a})$ by the product rule.`,String.raw`Let $u=x^2$, $v=x+${a}$, so $u'=2x$, $v'=1$.`,String.raw`$f'=u'v+uv'=2x(x+${a})+x^2$.`,String.raw`Simplifying gives $f'(x)=3x^2+${2*a}x$.`);}),
  F('quotient-rule','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Differentiate $f(x)=x/(x+${a})$ and give its domain.`,String.raw`Domain excludes $x=-${a}$ where the denominator vanishes.`,String.raw`Quotient rule gives $[(x+${a})(1)-x(1)]/(x+${a})^2$.`,String.raw`Simplify to $f'(x)=${a}/(x+${a})^2$ for $x\neq-${a}$.`);}),
  F('chain-trig','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`Differentiate $g(x)=\sin(${a}x)+e^x$ on the real line.`,String.raw`The outer sine derivative is cosine and the inner derivative of $${a}x$ is $${a}$.`,String.raw`The exponential derivative is $e^x$.`,String.raw`Therefore $g'(x)=${a}\cos(${a}x)+e^x$.`);}),
  F('rational-power-domain','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For real $x$, differentiate $f(x)=(x+${a})^{1/2}$ on its differentiable interior and state the original domain.`,String.raw`The square root is real on $x\geq-${a}$, including the endpoint.`,String.raw`For $x>-${a}$, the chain and rational-power rules give $f'(x)=\tfrac12(x+${a})^{-1/2}$.`,String.raw`Thus $f'(x)=1/[2\sqrt{x+${a}}]$ for $x>-${a}$; no two-sided derivative exists at the domain endpoint.`);}),
 ],
 'SL 5.7':[
  F('concavity-cubic','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $f(x)=(x-${a})^3$, find where concavity changes and give the inflection coordinate.`,String.raw`$f''(x)=6(x-${a})$.`,String.raw`It is negative for $x<${a}$ and positive for $x>${a}$.`,String.raw`Concavity changes at $(${a},0)$, so that point is an inflection.`);}),
  F('zero-not-inflection','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $g(x)=(x-${a})^4$, test whether $x=${a}$ is an inflection.`,String.raw`$g''(x)=12(x-${a})^2$ and equals zero at $x=${a}$.`,String.raw`It remains positive on both sides of $${a}$, so concavity does not change.`,String.raw`No inflection occurs at $(${a},0)$ despite the vanishing second derivative.`);}),
  F('acceleration-second-derivative','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Position is $s(t)=${a}t^2+3t$ metres. Find velocity and acceleration, with units.`,String.raw`$v(t)=ds/dt=${2*a}t+3$ m/s.`,String.raw`Differentiate again: $dv/dt=${2*a}$.`,String.raw`Acceleration is the constant $${2*a}$ m/s$^2$, the second derivative of position.`);}),
 ],
 'SL 5.8':[
  F('minimum-second-derivative','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find and classify the stationary point of $f(x)=(x-${a})^2+${b}$.`,String.raw`$f'(x)=2(x-${a})=0$ at $x=${a}$.`,String.raw`$f''(x)=2>0$, so the stationary point is a minimum.`,String.raw`Substitution gives the coordinate $(${a},${b})$.`);}),
  F('maximum-second-derivative','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find and classify the stationary point of $g(x)=-(x-${a})^2+${b}$.`,String.raw`$g'(x)=-2(x-${a})=0$ at $x=${a}$.`,String.raw`$g''(x)=-2<0$, so this is a local maximum.`,String.raw`The maximum value is $${b}$, at point $(${a},${b})$.`);}),
  F('rectangle-optimum','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`A rectangular enclosure has perimeter $${4*a}$ m. Let one side be $x$ m. Find the greatest possible area and both side lengths.`,String.raw`The other side is $${2*a}-x$ and $A(x)=x(${2*a}-x)$ for $0\leq x\leq${2*a}$.`,String.raw`$A'(x)=${2*a}-2x=0$ at $x=${a}$; then the other side is $${a}$.`,String.raw`$A''=-2<0$ and endpoints have zero area, so the maximum is $${a*a}$ m$^2$.`);}),
 ],
 'SL 5.9':[
  F('linear-velocity-distance','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Velocity is $v(t)=t-${a}$ m/s on $0\leq t\leq${2*a}$. Find displacement and total distance traveled.`,String.raw`The velocity changes sign at $t=${a}$. Symmetry gives signed displacement $\int_0^{${2*a}}(t-${a})\,dt=0$.`,String.raw`The negative and positive triangular areas are each $${a*a}/2$.`,String.raw`Total distance is $${a*a}$ m, from integrating $|v(t)|$.`);}),
  F('position-velocity-accel','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`A particle has position $s(t)=t^2+${a}t$ metres. Find $v(t)$ and $a(t)$, then evaluate both at $t=2$ s.`,String.raw`Velocity is $v(t)=ds/dt=2t+${a}$.`,String.raw`Acceleration is $a(t)=dv/dt=2$.`,String.raw`At $t=2$, velocity is $${4+a}$ m/s and acceleration is $2$ m/s$^2$.`);}),
  F('quadratic-velocity-distance','P2',k=>{const a=at([1,2,3,4],k);return Q(String.raw`A particle moves with $v(t)=t^2-${a*a}$ on $0\leq t\leq${2*a}$. Find exact displacement and distance traveled.`,String.raw`$v$ changes from negative to positive at $t=${a}$; integrate $t^2-${a*a}$ separately on each side.`,String.raw`$\int_0^{${a}}v\,dt=-${2*a**3}/3$ and $\int_{${a}}^{${2*a}}v\,dt=${4*a**3}/3$.`,String.raw`Displacement is $${2*a**3}/3$, but distance is $(${2*a**3}+${4*a**3})/3=${2*a**3}$ units.`);}),
 ],
 'SL 5.10':[
  F('reverse-chain-integral','P1',k=>{const a=at([1,2,3,4],k),n=at([2,3,4,5],k);return Q(String.raw`Integrate $\int 2x(x^2+${a})^{${n}}\,dx$, including the constant.`,String.raw`Let $u=x^2+${a}$; then $du=2x\,dx$.`,String.raw`Integrate $u^{${n}}$ to get $u^{${n+1}}/${n+1}+C$.`,String.raw`Answer $(x^2+${a})^{${n+1}}/${n+1}+C$; differentiation checks it.`);}),
  F('logarithmic-antiderivative','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find $\int 1/(x+${a})\,dx$ and specify the excluded input.`,String.raw`Set $u=x+${a}$, so $du=dx$.`,String.raw`$\int1/u\,du=\ln|u|+C$.`,String.raw`The answer is $\ln|x+${a}|+C$ on either interval excluding $x=-${a}$.`);}),
  F('substitution-definite','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Evaluate $\int_0^{${a}}2x\,dx$ by substitution $u=x^2$ with correctly transformed limits.`,String.raw`$u=x^2$, $du=2x\,dx$; bounds $x=0,${a}$ become $u=0,${a*a}$.`,String.raw`The integral becomes $\int_0^{${a*a}}1\,du$.`,String.raw`Its exact value is $${a*a}$, a positive signed area here.`);}),
 ],
 'SL 5.11':[
  F('definite-power-area','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the area under $y=x$ from $x=0$ to $x=${a}$ by a definite integral.`,String.raw`The line is nonnegative on the interval, so area is $\int_0^{${a}}x\,dx$.`,String.raw`An antiderivative is $x^2/2$; evaluate $[x^2/2]_0^{${a}}$.`,String.raw`Area is $${a*a}/2$ square units.`);}),
  F('between-line-and-parabola','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the area enclosed by $y=${a}x$ and $y=x^2$ between their intersections.`,String.raw`Set $${a}x=x^2$ to get $x=0,${a}$. On this interval $${a}x\geq x^2$.`,String.raw`Area $=\int_0^{${a}}(${a}x-x^2)\,dx=[${a}x^2/2-x^3/3]_0^{${a}}$.`,String.raw`The result is $${a**3}/6$ square units.`);}),
  F('cubic-crosses-axis','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $y=x^3$ on $[-${a},${a}]$, compare signed integral with geometric area.`,String.raw`The odd function has $\int_{-${a}}^{${a}}x^3\,dx=0$.`,String.raw`Area is $2\int_0^{${a}}x^3\,dx=2[x^4/4]_0^{${a}}$.`,String.raw`Geometric area is $${a**4}/2$ square units, not zero.`);}),
 ],
 'AHL 5.12':[
  F('first-principles-scaled','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Use first principles to differentiate $f(x)=${a}x^2$.`,String.raw`$[f(x+h)-f(x)]/h=${a}[(x+h)^2-x^2]/h$ for $h\neq0$.`,String.raw`Simplify to $${a}(2x+h)$ before taking the limit.`,String.raw`As $h\to0$, $f'(x)=${2*a}x$.`);}),
  F('higher-derivatives','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the first, second and third derivatives of $f(x)=x^3+${a}x^2$.`,String.raw`$f'(x)=3x^2+${2*a}x$.`,String.raw`$f''(x)=6x+${2*a}$.`,String.raw`$f'''(x)=6$; subsequent derivatives of this cubic are zero.`);}),
  F('absolute-corner','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Explain from one-sided gradients why $f(x)=|x-${a}|$ is not differentiable at $x=${a}$.`,String.raw`For $x<${a}$, $f(x)=${a}-x$, so left derivative is $-1$.`,String.raw`For $x>${a}$, $f(x)=x-${a}$, so right derivative is $1$.`, 'The one-sided gradients disagree, so the derivative at the corner does not exist.');}),
 ],
 'AHL 5.13':[
  F('factor-removable-limit','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Evaluate $\lim_{x\to${a}}(x^2-${a*a})/(x-${a})$ and distinguish the limit from the value at $x=${a}$.`,String.raw`Factor numerator $(x-${a})(x+${a})$.`,String.raw`For nearby $x\neq${a}$ the fraction equals $x+${a}$.`,String.raw`The limit is $${2*a}$, while the original quotient is undefined at $x=${a}$.`);}),
  F('lhopital-sine','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Use L'Hôpital's rule, with its indeterminate-form check, to find $\lim_{x\to0}\sin(${a}x)/x$.`, 'Both numerator and denominator approach zero, so this is a $0/0$ limit.',String.raw`Differentiate top and bottom: $${a}\cos(${a}x)/1$.`,String.raw`At $x=0$ the new limit is $${a}\cos0=${a}$.`);}),
  F('rational-limit-infinity','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Evaluate $\lim_{x\to\infty}(${a}x^2+1)/(${b}x^2+1)$ by comparing powers.`, 'Divide numerator and denominator by $x^2$, which is nonzero for large input.',String.raw`The ratio becomes $(${a}+1/x^2)/(${b}+1/x^2)$.`,String.raw`As $x\to\infty$, it approaches $${a}/${b}$.`);}),
 ],
 'AHL 5.14':[
  F('implicit-circle','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`On $x^2+y^2=${25*s*s}$, find $dy/dx$ at $(${3*s},${4*s})$.`,String.raw`Differentiate implicitly: $2x+2y\,dy/dx=0$.`,String.raw`Where $y\neq0$, $dy/dx=-x/y$.`,String.raw`At $(${3*s},${4*s})$, tangent gradient is $-${3*s}/${4*s}=-3/4$.`);}),
  F('related-rates-sphere','P1',k=>{const r=at([2,3,4,5],k),v=at([1,2,3,4],k);return Q(String.raw`A sphere's radius is $${r}$ cm and growing at $${v}$ cm/s. Find its instantaneous volume growth rate.`,String.raw`$V=(4/3)\pi r^3$, so $dV/dt=4\pi r^2\,dr/dt$.`,String.raw`Substitute $r=${r}$ and $dr/dt=${v}$ cm/s.`,String.raw`The rate is $${4*r*r*v}\pi$ cm$^3$/s.`);}),
  F('implicit-hyperbola','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For the implicit curve $xy=${a}$, find $dy/dx$ and evaluate it at $(1,${a})$.`,String.raw`Product differentiation gives $y+x\,dy/dx=0$.`,String.raw`For $x\neq0$, $dy/dx=-y/x$.`,String.raw`At $(1,${a})$ the tangent gradient is $-${a}$.`);}),
  F('open-cylinder-optimum','P2',k=>{const r=at([2,3,4,5],k),v=r**3;return Q(String.raw`An open-topped cylindrical vessel has fixed volume $${v}\pi$ cm$^3$. Find the radius and height minimizing its base-plus-side surface area.`,String.raw`$V=\pi r^2h=${v}\pi$, so $h=${v}/r^2$ and $S(r)=\pi r^2+2\pi(${v})/r$ for $r>0$.`,String.raw`$S'(r)=2\pi r-2\pi(${v})/r^2=0$ gives $r^3=${v}$ and $r=${r}$ cm.`,String.raw`Then $h=${v}/${r*r}=${r}$ cm. Since $S''(r)=2\pi+4\pi(${v})/r^3>0$ for $r>0$, this is the minimum.`);}),
 ],
 'AHL 5.15':[
  F('derivative-tangent','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`Differentiate $f(x)=\tan(${a}x)$ on its real domain and note the exclusions.`,String.raw`Outer derivative is $\sec^2(${a}x)$.`,String.raw`Inner derivative of $${a}x$ is $${a}$, so $f'(x)=${a}\sec^2(${a}x)$.`,String.raw`Exclude inputs satisfying $\cos(${a}x)=0$, where tangent itself is undefined.`);}),
  F('integral-exponential-base','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`Find $\int ${a}^x\,dx$ for real $x$ and check by differentiating.`,String.raw`$d(${a}^x)/dx=${a}^x\ln(${a})$ for base $${a}>0$, $${a}\neq1$.`,String.raw`Divide by $\ln(${a})$ to compensate for the derivative factor.`,String.raw`Answer $${a}^x/\ln(${a})+C$; differentiation restores $${a}^x$.`);}),
  F('derivative-arctan','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Differentiate $g(x)=\arctan(${a}x)$ using the chain rule.`,String.raw`$d(\arctan u)/du=1/(1+u^2)$ for real $u$.`,String.raw`For $u=${a}x$, $du/dx=${a}$.`,String.raw`So $g'(x)=${a}/(1+${a*a}x^2)$ for every real $x$.`);}),
 ],
 'AHL 5.16':[
  F('parts-x-exp','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Evaluate $\int x e^{${a}x}\,dx$ by parts, including the integration constant.`,String.raw`Take $u=x$, $dv=e^{${a}x}dx$; then $du=dx$, $v=e^{${a}x}/${a}$.`,String.raw`Parts gives $xe^{${a}x}/${a}-\int e^{${a}x}/${a}\,dx$.`,String.raw`Thus the answer is $e^{${a}x}(x/${a}-1/${a*a})+C$.`);}),
  F('substitution-composite','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Use substitution to evaluate $\int_0^{${a}}2x(x^2+1)\,dx$.`,String.raw`Let $u=x^2+1$, $du=2x\,dx$; bounds become $u=1$ and $u=${a*a+1}$.`,String.raw`Compute $\int_1^{${a*a+1}}u\,du=[u^2/2]_1^{${a*a+1}}$.`,String.raw`The exact value is $((${a*a+1})^2-1)/2=${(a*a+1)**2/2-.5}$.`);}),
  F('repeated-parts','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Integrate $\int (x+${a})^2e^x\,dx$ by repeated parts.`,String.raw`Take $u=(x+${a})^2$ and $dv=e^xdx$: the first step gives $(x+${a})^2e^x-2\int(x+${a})e^x\,dx$.`,String.raw`Repeat parts on the remaining linear factor to obtain $\int(x+${a})e^x\,dx=e^x(x+${a}-1)+C$.`,String.raw`Result $e^x[(x+${a})^2-2(x+${a})+2]+C$; differentiating checks it.`);}),
 ],
 'AHL 5.17':[
  F('area-horizontal-slices','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find area of $0\leq y\leq${a}$, $0\leq x\leq y$ by integrating with respect to $y$.`,String.raw`A horizontal strip runs from $x=0$ to $x=y$, so width is $y$.`,String.raw`Area $=\int_0^{${a}}y\,dy=[y^2/2]_0^{${a}}$.`,String.raw`The area is $${a*a}/2$ square units.`);}),
  F('volume-rotate-y','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Rotate $0\leq y\leq${a}$ and $0\leq x\leq y$ about the $y$-axis. Find volume.`,String.raw`Horizontal discs have radius $r(y)=y$ and area $\pi y^2$.`,String.raw`$V=\pi\int_0^{${a}}y^2\,dy=\pi[y^3/3]_0^{${a}}$.`,String.raw`The volume is $${a**3}\pi/3$ cubic units.`);}),
  F('volume-rotate-x','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Rotate the region under $y=x$ on $0\leq x\leq${a}$ about the $x$-axis. Find volume.`,String.raw`Vertical discs have radius $y=x$, so area $\pi x^2$.`,String.raw`$V=\pi\int_0^{${a}}x^2\,dx=\pi[x^3/3]_0^{${a}}$.`,String.raw`The volume is $${a**3}\pi/3$ cubic units.`);}),
 ],
 'AHL 5.18':[
  F('euler-two-steps','P2',k=>{const a=at([1,2,3,4],k),y1=1.5*a,y2=2.25*a+0.25;return Q(String.raw`For $dy/dx=x+y$, $y(0)=${a}$, take two Euler steps of size $h=0.5$. Estimate $y(1)$.`,String.raw`At $(0,${a})$ slope is $${a}$; $y_1=${a}+0.5(${a})=${y1}$ at $x_1=0.5$.`,String.raw`Next slope is $0.5+${y1}=${y1+0.5}$ at $x_1=0.5$.`,String.raw`$y_2=${y1}+0.5(${y1+0.5})=${y2}$ at $x_2=1$, an Euler approximation.`);}),
  F('separable-exponential','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Solve $dy/dx=${a}y$ subject to $y(0)=2$, stating the positive solution.`,String.raw`Separate: $dy/y=${a}\,dx$ where $y>0$.`,String.raw`Integrate $\ln y=${a}x+C$ and exponentiate to obtain $y=K e^{${a}x}$.`,String.raw`$y(0)=2$ gives $K=2$, hence $y=2e^{${a}x}$.`);}),
  F('integrating-factor','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Solve $y'+${a}y=${a}$ with $y(0)=0$ using an integrating factor.`,String.raw`Multiply by $e^{${a}x}$ to obtain $(e^{${a}x}y)'=${a}e^{${a}x}$.`,String.raw`Integrate: $e^{${a}x}y=e^{${a}x}+C$, so $y=1+Ce^{-${a}x}$.`,String.raw`Use $y(0)=0$ to get $C=-1$, hence $y=1-e^{-${a}x}$.`);}),
 ],
 'AHL 5.19':[
  F('maclaurin-exponential','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the Maclaurin expansion of $e^{${a}x}$ through $x^3$.`,String.raw`Start $e^u=1+u+u^2/2!+u^3/3!+\cdots$ with $u=${a}x$.`,String.raw`The first three nonconstant terms are $${a}x+${a*a}x^2/2+${a**3}x^3/6$.`,String.raw`Thus $e^{${a}x}=1+${a}x+${a*a}x^2/2+${a**3}x^3/6+O(x^4)$.`);}),
  F('maclaurin-sine','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Give the first nonzero terms of $\sin(${a}x)$ through degree three at $x=0$.`,String.raw`Use $\sin u=u-u^3/3!+O(u^5)$.`,String.raw`Substitute $u=${a}x$, giving $${a}x-${a**3}x^3/6$.`,String.raw`The truncation is $\sin(${a}x)=${a}x-${a**3}x^3/6+O(x^5)$.`);}),
  F('maclaurin-cosine','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Give the Maclaurin terms of $\cos(${a}x)$ through degree four.`,String.raw`Use $\cos u=1-u^2/2!+u^4/4!+O(u^6)$.`,String.raw`Substitute $u=${a}x$ to get $1-${a*a}x^2/2+${a**4}x^4/24$.`,String.raw`Thus $\cos(${a}x)=1-${a*a}x^2/2+${a**4}x^4/24+O(x^6)$.`);}),
  F('maclaurin-logarithm','P1',k=>{const a=at([1,2,3,4],k),interval=a===1?'-1<x<1':`-1/${a}<x<1/${a}`;return Q(String.raw`Expand $\ln(1+${a}x)$ through $x^3$ about zero and give an open interval where the series is valid.`,String.raw`Use $\ln(1+u)=u-u^2/2+u^3/3+O(u^4)$ near zero with $u=${a}x$.`,String.raw`The cubic approximation is $${a}x-${a*a}x^2/2+${a**3}x^3/3$.`,String.raw`The infinite series converges for $|${a}x|<1$, so $${interval}$ is a valid open interval.`);}),
 ],
};
