const F = (name, paper, build) => ({ name, paper, build });
const Q = (prompt, ...steps) => ({ prompt, steps: steps.map((text) => [1, text]) });
const at = (xs, k) => xs[k % xs.length];
export const families = {
  'SL 2.1': [
    F('gradient-two-points','P1',k=>{const a=at([1,2,3,4],k),b=at([2,1,-1,3],k),m=at([2,3,-2,4],k),c=b-m*a;return Q(String.raw`Find the gradient and equation of the line through $(${a},${b})$ and $(${a+2},${b+2*m})$.`,String.raw`Gradient $m=(${b+2*m}-${b})/(${a+2}-${a})=${m}$.`,String.raw`Substitute $(${a},${b})$ into $y=${m}x+c$: $c=${b}-${m}(${a})=${c}$.`,String.raw`The line is $y=${m}x${c>=0?'+':''}${c}$; both points satisfy it.`);}),
    F('perpendicular-through-point','P1',k=>{const m=at([1,2,3,4],k),a=at([1,2,-1,3],k),b=at([2,3,4,1],k);return Q(String.raw`A line has gradient $${m}$. Find the equation of a perpendicular line through $(${a},${b})$.`,String.raw`Its gradient is the negative reciprocal $-1/${m}$, since $${m}(-1/${m})=-1$.`,String.raw`Use point-slope form $y-${b}=-(x-${a})/${m}$.`,String.raw`The stated equation passes through $(${a},${b})$ and is perpendicular to the original direction.`);}),
    F('line-intersection','P1',k=>{const m=at([1,2,3,4],k),a=at([2,3,1,4],k),t=at([1,2,3,4],k);return Q(String.raw`Find the intersection of $y=${m}x+${a}$ and $y=-${m}x+${a+2*m*t}$.`,String.raw`Equate right sides: $${m}x+${a}=-${m}x+${a+2*m*t}$.`,String.raw`Thus $${2*m}x=${2*m*t}$, giving $x=${t}$.`,String.raw`Substituting gives the intersection $(${t},${a+m*t})$.`);}),
    F('parallel-through-point','P1',k=>{const m=at([2,3,-2,4],k),c=at([1,2,3,4],k),x0=at([1,2,3,4],k),y0=m*x0+c+2,intercept=y0-m*x0;return Q(String.raw`Find the line parallel to $y=${m}x+${c}$ that passes through $(${x0},${y0})$.`,String.raw`Parallel nonvertical lines have equal gradient $${m}$.`,String.raw`Point-slope form gives $y-(${y0})=${m}(x-${x0})$.`,String.raw`The new equation is $y=${m}x${intercept>=0?'+':''}${intercept}$; it passes through $(${x0},${y0})$.`);}),
  ],
  'SL 2.2': [
    F('inverse-affine','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`For $f(x)=${a}x+${b}$ on $\mathbb R$, find $f^{-1}$ and its domain.`,String.raw`Set $y=${a}x+${b}$, then $y-${b}=${a}x$.`,String.raw`Exchange input and output: $f^{-1}(x)=(x-${b})/${a}$.`,'The original range is all real numbers, so the inverse domain is all real numbers.');}),
    F('restrict-square','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $f(x)=(x-${a})^2$ with $x\geq${a}$, give the range and inverse.`,String.raw`On $x\geq${a}$ the square grows from zero, so the range is $[0,\infty)$.`,String.raw`Solve $y=(x-${a})^2$ using $x-${a}\geq0$: $x=${a}+\sqrt y$.`,String.raw`Thus $f^{-1}(x)=${a}+\sqrt x$ for $x\geq0$.`);}),
    F('reciprocal-domain-range','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find the real domain and range of $h(x)=${b}+1/(x-${a})$.`,String.raw`The denominator vanishes at $x=${a}$, so exclude it from the domain.`,String.raw`The reciprocal term can never be zero, so $h(x)\neq${b}$.`,String.raw`Domain $\mathbb R\setminus\{${a}\}$; range $\mathbb R\setminus\{${b}\}$.`);}),
  ],
  'SL 2.3': [
    F('parabola-landmarks','P1',k=>{const a=at([1,2,3,4],k),b=a+2;return Q(String.raw`Sketch $y=(x-${a})(x-${b})$ by listing both $x$-intercepts, the $y$-intercept and the symmetry axis.`,String.raw`The zeros are $x=${a}$ and $x=${b}$, so the $x$-intercepts are $(${a},0)$ and $(${b},0)$.`,String.raw`At $x=0$, $y=(-${a})(-${b})=${a*b}$, giving $(0,${a*b})$.`,String.raw`The symmetry axis is midway at $x=${a+1}$; the parabola opens upward.`);}),
    F('modulus-graph','P1',k=>{const a=at([1,2,3,4],k),b=at([1,2,1,3],k);return Q(String.raw`Describe a sketch of $y=|x-${a}|+${b}$: vertex, range and two symmetric points.`,String.raw`The absolute-value corner is at $(${a},${b})$.`,String.raw`Values are at least $${b}$, so the range is $[${b},\infty)$.`,String.raw`At $x=${a-1}$ and $${a+1}$ the height is $${b+1}$, confirming symmetry.`);}),
    F('graph-asymptotes','P1',k=>{const a=at([1,2,3,4],k),b=at([1,2,3,4],k);return Q(String.raw`Sketch $y=1/(x-${a})+${b}$: name its asymptotes and one exact point on the right branch.`,String.raw`The denominator excludes $x=${a}$, giving vertical asymptote $x=${a}$.`,String.raw`As $|x|\to\infty$, the reciprocal tends to zero, giving horizontal asymptote $y=${b}$.`,String.raw`At $x=${a+1}$, $y=1+${b}=${b+1}$, so $(${a+1},${b+1})$ is on the curve.`);}),
  ],
  'SL 2.4': [
    F('line-parabola-intersections','P1',k=>{const s=at([2,3,4,5],k);return Q(String.raw`Find the intersections of $y=x^2$ and $y=${s+1}x-${s}$ exactly.`,String.raw`Equate outputs: $x^2-${s+1}x+${s}=0$.`,String.raw`Factor $(x-1)(x-${s})=0$, so $x=1$ or $${s}$.`,String.raw`The two intersection points are $(1,1)$ and $(${s},${s*s})$.`);}),
    F('restricted-maximum','P1',k=>{const c=at([2,3,4,5],k);return Q(String.raw`On $-1\leq x\leq1$, find the maximum and minimum of $f(x)=${c}-x^2$ and where they occur.`,String.raw`$x^2$ is smallest at $x=0$, so $f(0)=${c}$ is the maximum.`,String.raw`$x^2$ is largest at either endpoint $x=\pm1$.`,String.raw`$f(-1)=f(1)=${c-1}$ is the minimum on the stated domain.`);}),
    F('graph-features-rational','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,1,4],k);return Q(String.raw`For $g(x)=${b}/(x-${a})+1$, state both asymptotes and the $x$-intercept.`,String.raw`The vertical asymptote is $x=${a}$; the horizontal asymptote is $y=1$.`,String.raw`For the intercept, set $${b}/(x-${a})+1=0$, so $x-${a}=-${b}$.`,String.raw`The $x$-intercept is $(${a-b},0)$, which is not the excluded value $${a}$.`);}),
    F('graphical-numerical-intersection','P2',k=>{const height=at([2,3,5,6],k),root=Math.sqrt(height).toFixed(3);return Q(String.raw`Use graphing technology to estimate the intersection with positive $x$-coordinate of $y=x^2$ and $y=${height}$ to three decimal places. Identify the other intersection.`,String.raw`At an intersection $x^2=${height}$; one graph crossing has $x>0$.`,String.raw`The positive root is $x=\sqrt{${height}}\approx${root}$, giving $(${root},${height})$.`,String.raw`The negative crossing is $(-${root},${height})$ to three decimals. Squaring either rounded input approximately reproduces $${height}$.`);}),
  ],
  'SL 2.5': [
    F('compose-affine-square','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`For $f(x)=${a}x+${b}$ and $g(x)=x^2$, find both $f\circ g$ and $g\circ f$.`,String.raw`Apply $g$ first: $(f\circ g)(x)=f(x^2)=${a}x^2+${b}$.`,String.raw`Apply $f$ first: $(g\circ f)(x)=g(${a}x+${b})=(${a}x+${b})^2$.`,'Both domains are all real numbers, but the two compositions are not generally equal.');}),
    F('inverse-linear-identity','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`Find the inverse of $f(x)=${a}x-${b}$ and verify $f(f^{-1}(x))=x$.`,String.raw`Solve $y=${a}x-${b}$: $x=(y+${b})/${a}$.`,String.raw`Therefore $f^{-1}(x)=(x+${b})/${a}$.`,String.raw`$f((x+${b})/${a})=${a}(x+${b})/${a}-${b}=x$.`);}),
    F('composite-domain','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Let $f(x)=\sqrt x$ for $x\geq0$ and $g(x)=x-${a}$. Find $(f\circ g)(x)$ and its real domain.`,String.raw`Composition means $f(g(x))=\sqrt{x-${a}}$.`,String.raw`The input to $f$ must satisfy $x-${a}\geq0$.`,String.raw`Thus the domain is $x\geq${a}$, with outputs nonnegative.`);}),
    F('identity-composition','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`For $f(x)=${a}x+${b}$ and the identity function $I(x)=x$ on $\mathbb R$, calculate $f\circ I$ and $I\circ f$.`,String.raw`$(f\circ I)(x)=f(I(x))=f(x)=${a}x+${b}$.`,String.raw`$(I\circ f)(x)=I(f(x))=f(x)=${a}x+${b}$.`, 'Both compositions equal $f$ on the real domain; the identity leaves inputs and outputs unchanged.');}),
  ],
  'SL 2.6': [
    F('completed-square','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`Complete the square for $x^2-${2*a}x+${a*a-b*b}$, then find the vertex.`,String.raw`$x^2-${2*a}x+${a*a-b*b}=(x-${a})^2-${b*b}$.`,String.raw`The squared term is least at $x=${a}$.`,String.raw`The vertex is $(${a},-${b*b})$, a minimum because the leading coefficient is positive.`);}),
    F('roots-from-vertex','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`For $q(x)=(x-${a})^2-${b*b}$, find the zeros and axis of symmetry.`,String.raw`Set $(x-${a})^2=${b*b}$.`,String.raw`Then $x-${a}=\pm${b}$, giving roots $x=${a-b}$ and $x=${a+b}$.`,String.raw`Their midpoint is $${a}$, so the axis is $x=${a}$.`);}),
    F('quadratic-discriminant','P1',k=>{const a=at([1,2,3,4],k),c=at([-1,0,1,4],k);return Q(String.raw`How many distinct real roots has $x^2-${2*a}x+${a*a-c}=0$? Use its discriminant.`,String.raw`Here $b=-${2*a}$ and constant term is $${a*a-c}$.`,String.raw`$\Delta=b^2-4ac=${4*c}$.`,c>0?'A positive discriminant gives two distinct real roots.':c===0?'A zero discriminant gives exactly one repeated real root.':'A negative discriminant gives no real roots.');}),
  ],
  'SL 2.7': [
    F('factor-quadratic','P1',k=>{const a=at([1,2,3,4],k),b=a+2;return Q(String.raw`Solve $x^2-${a+b}x+${a*b}=0$ by factorization.`,String.raw`Find two numbers with sum $${a+b}$ and product $${a*b}$: $${a}$ and $${b}$.`,String.raw`Factor as $(x-${a})(x-${b})=0$.`,String.raw`Thus $x=${a}$ or $x=${b}$; both give zero in the original equation.`);}),
    F('quadratic-inequality','P1',k=>{const a=at([1,2,3,4],k),b=a+2;return Q(String.raw`Solve $x^2-${a+b}x+${a*b}\leq0$, giving an interval with correct endpoints.`,String.raw`Factor $(x-${a})(x-${b})$ and mark zeroes $${a},${b}$.`,'The upward-opening product is nonpositive between its two zeroes.',String.raw`The inclusive solution is $${a}\leq x\leq${b}$.`);}),
    F('quadratic-formula','P1',k=>{const c=at([1,2,4,5],k);return Q(String.raw`Solve $x^2+2x-${c}=0$ exactly using a completed square or quadratic formula.`,String.raw`Rearrange $(x+1)^2=${c+1}$.`,String.raw`Therefore $x+1=\pm\sqrt{${c+1}}$.`,String.raw`The exact roots are $x=-1\pm\sqrt{${c+1}}$.`);}),
  ],
  'SL 2.8': [
    F('reciprocal-asymptotes','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`For $h(x)=${b}+2/(x-${a})$, give domain, range and both asymptotes.`,String.raw`Exclude $x=${a}$; the vertical asymptote is $x=${a}$.`,String.raw`The nonzero reciprocal prevents output $${b}$; the horizontal asymptote is $y=${b}$.`,String.raw`Domain $\mathbb R\setminus\{${a}\}$ and range $\mathbb R\setminus\{${b}\}$.`);}),
    F('solve-reciprocal','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Solve $${b}/(x-${a})=${b}$, keeping the original domain restriction.`,String.raw`Require $x\neq${a}$ since the denominator must not vanish.`,String.raw`Divide by $${b}\neq0$ to obtain $1/(x-${a})=1$.`,String.raw`Then $x=${a+1}$, which is allowed and checks in the original equation.`);}),
    F('inverse-reciprocal','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find the inverse of $f(x)=${b}+1/(x-${a})$, stating its domain.`,String.raw`Write $y-${b}=1/(x-${a})$, with $x\neq${a}$.`,String.raw`Rearrange $x=${a}+1/(y-${b})$.`,String.raw`Thus $f^{-1}(x)=${a}+1/(x-${b})$, for $x\neq${b}$.`);}),
  ],
  'SL 2.9': [
    F('exponential-shift','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $f(x)=2^x-${a}$, state its domain, range and horizontal asymptote.`, 'The exponential $2^x$ is defined and strictly positive for every real input.',String.raw`Subtracting $${a}$ gives range $(-${a},\infty)$.`,String.raw`The domain is $\mathbb R$ and the horizontal asymptote is $y=-${a}$.`);}),
    F('exponential-solve','P1',k=>{const a=at([1,2,3,4],k),n=at([2,3,4,5],k);return Q(String.raw`Solve $2^{x-${a}}=${2**n}$ exactly.`,String.raw`Both sides are powers of $2$: $2^{x-${a}}=2^{${n}}$.`,String.raw`Equal exponents give $x-${a}=${n}$.`,String.raw`Therefore $x=${a+n}$, valid on the real domain.`);}),
    F('logarithm-shift','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`For $g(x)=\log_2(x-${a})$, give domain, range and vertical asymptote.`,String.raw`Require $x-${a}>0$, so domain is $x>${a}$.`, 'A logarithm takes every real output as its positive input varies.',String.raw`Range is $\mathbb R$; as $x\downarrow${a}$, the vertical asymptote is $x=${a}$.`);}),
  ],
  'SL 2.10': [
    F('two-curves-exact','P1',k=>{const s=at([2,3,4,5],k);return Q(String.raw`Solve $x^2=${s+1}x-${s}$ by turning the intersection into a zero problem.`,String.raw`Subtract the right side: $x^2-${s+1}x+${s}=0$.`,String.raw`Factor $(x-1)(x-${s})=0$.`,String.raw`The intersection inputs are $x=1$ and $x=${s}$; substitution gives their coordinates if needed.`);}),
    F('bracket-root','P2',k=>{const c=at([2,3,5,6],k),lower=Math.floor(Math.sqrt(c)),upper=lower+1,mid=(lower+upper)/2, newEnd=mid*mid<c?`${mid}<\\sqrt{${c}}<${upper}`:`${lower}<\\sqrt{${c}}<${mid}`;return Q(String.raw`Bracket the positive root of $x^2=${c}$ first between consecutive integers, then after one bisection step.`,String.raw`$${lower}^2=${lower*lower}<${c}<${upper*upper}=${upper}^2$, so the root lies between $${lower}$ and $${upper}$.`,String.raw`Midpoint $${mid}$ has square $${mid*mid}$; compare this with $${c}$.`,String.raw`The smaller bracket is $${newEnd}$.`);}),
    F('log-equation-check','P1',k=>{const b=at([2,3,4,5],k),n=at([2,3,2,3],k);return Q(String.raw`Solve the intersection of $y=\log_{${b}}x$ and the horizontal line $y=${n}$. Check the domain.`,String.raw`The log requires $x>0$ and $${b}>0$, $${b}\neq1$.`,String.raw`Convert $\log_{${b}}x=${n}$ into $x=${b}^{${n}}=${b**n}$.`,String.raw`The intersection is $(${b**n},${n})$ with valid positive input.`);}),
  ],
  'SL 2.11': [
    F('parabola-shift-stretch','P1',k=>{const a=at([1,2,3,4],k),m=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`From $f(x)=x^2$ describe the transformations to $g(x)=${m}(x-${a})^2+${b}$ and find its vertex.`,String.raw`$(x-${a})^2$ shifts the graph right by $${a}$.`,String.raw`The factor $${m}$ stretches vertically by $${m}$; $+${b}$ shifts it up $${b}$.`,String.raw`The new vertex is $(${a},${b})$ and its range starts at $${b}$.`);}),
    F('reflected-vertex','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Describe $y=-(x+${a})^2+${b}$ from $y=x^2$: vertex, reflection and range.`,String.raw`The input $x+${a}$ moves the vertex left to $x=-${a}$.`,String.raw`The negative coefficient reflects the graph in the $x$-axis; $+${b}$ moves it up.`,String.raw`Vertex $(-${a},${b})$ is a maximum, and range is $(-\infty,${b}]$.`);}),
    F('horizontal-compression','P1',k=>{const m=at([2,3,4,5],k),a=at([1,2,3,4],k);return Q(String.raw`For $f(x)=(x-${a})^2$, compare the landmark vertex with the graph $h(x)=f(${m}x)$.`,String.raw`$f$ has vertex at input $x=${a}$ with output zero.`,String.raw`$h(x)=(${m}x-${a})^2$ vanishes when $${m}x=${a}$.`,String.raw`The new vertex is $(${a}/${m},0)$, a horizontal compression by factor $${m}$.`);}),
  ],
  'AHL 2.12': [
    F('remainder-theorem','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find the remainder when $p(x)=x^2+${a}x+${b}$ is divided by $x-${a}$.`,String.raw`By the remainder theorem, compute $p(${a})$.`,String.raw`$p(${a})=${a}^2+${a}(${a})+${b}=${2*a*a+b}$.`,String.raw`The constant remainder is $${2*a*a+b}$; polynomial division would agree.`);}),
    F('factor-cubic','P1',k=>{const a=at([1,2,3,4],k),b=a+1,c=b+1;return Q(String.raw`A monic cubic is $(x-${a})(x-${b})(x-${c})$. State its three roots and their sum and product.`,String.raw`A factor $x-r$ vanishes at $x=r$, so roots are $${a},${b},${c}$.`,String.raw`Their sum is $${a}+${b}+${c}=${a+b+c}$.`,String.raw`Their product is $${a}(${b})(${c})=${a*b*c}$, including multiplicity if factors repeat.`);}),
    F('vieta-quadratic','P1',k=>{const a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`Without solving, find the sum and product of the roots of $2x^2-${2*a}x+${2*b}=0$.`, 'For a quadratic $Ax^2+Bx+C=0$, the root sum is $-B/A$ and product $C/A$.',String.raw`Here $A=2$, $B=-${2*a}$, $C=${2*b}$.`,String.raw`The sum is $${a}$ and the product is $${b}$.`);}),
  ],
  'AHL 2.13': [
    F('removable-hole','P1',k=>{const a=at([1,2,3,4],k),b=at([1,2,3,4],k);return Q(String.raw`Analyze $r(x)=[(x-${a})(x+${b})]/(x-${a})$: simplify, keep its domain and locate any hole.`,String.raw`Original denominator excludes $x=${a}$.`,String.raw`For $x\neq${a}$, cancel the factor and obtain $r(x)=x+${b}$.`,String.raw`The missing point is $(${a},${a+b})$, a removable hole rather than a vertical pole.`);}),
    F('genuine-pole','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`For $h(x)=${b}/(x-${a})+1$, state the domain, vertical asymptote and end behavior.`,String.raw`$x=${a}$ makes the denominator zero, so it is excluded.`,String.raw`Because numerator $${b}\neq0$, values grow unbounded near $x=${a}$: a vertical asymptote.`,String.raw`As $|x|\to\infty$, $h(x)\to1$, giving horizontal asymptote $y=1$.`);}),
    F('slant-asymptote','P1',k=>{const a=at([1,2,3,4],k),b=at([1,2,3,4],k);return Q(String.raw`Divide $(x^2+${a+1}x+${a+b})/(x+1)$ and give its slant asymptote.`,String.raw`$(x+1)(x+${a})=x^2+${a+1}x+${a}$.`,String.raw`The remaining numerator is $${b}$, so the fraction is $x+${a}+${b}/(x+1)$.`,String.raw`As $|x|\to\infty$, the last term tends to zero; slant asymptote $y=x+${a}$, domain $x\neq-1$.`);}),
  ],
  'AHL 2.14': [
    F('test-even','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Show that $f(x)=x^4+${a}x^2$ is even on its real domain.`,String.raw`The real domain is symmetric: $x$ and $-x$ are both allowed.`,String.raw`$f(-x)=(-x)^4+${a}(-x)^2=x^4+${a}x^2=f(x)$.`, 'Therefore the function is even and its graph is symmetric across the vertical axis.');}),
    F('test-odd','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Show that $g(x)=x^3+${a}x$ is odd on the real numbers.`,String.raw`Both $x$ and $-x$ belong to the real domain.`,String.raw`$g(-x)=-x^3-${a}x=-g(x)$.`, 'Thus the function is odd, with graph symmetric about the origin.');}),
    F('self-inverse-reciprocal','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Show that $h(x)=${a}/x$ is self-inverse on $\mathbb R\setminus\{0\}$.`,String.raw`For $x\neq0$, $h(x)=${a}/x\neq0$, so the composition is defined.`,String.raw`$h(h(x))=${a}/(${a}/x)=x$.`,String.raw`Hence $h^{-1}=h$ on the nonzero real domain and range.`);}),
  ],
  'AHL 2.15': [
    F('rational-sign-chart','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Solve $(x-${a})/x\geq0$, carefully handling zero and an excluded input.`,String.raw`Critical values are numerator zero $x=${a}$ and denominator zero $x=0$.`,String.raw`Testing signs gives positive on $(-\infty,0)$ and $(${a},\infty)$, negative on $(0,${a})$.`,String.raw`Answer $(-\infty,0)\cup[${a},\infty)$; include $${a}$ but exclude $0$.`);}),
    F('quadratic-sign-chart','P1',k=>{const a=at([1,2,3,4],k),b=a+2;return Q(String.raw`Solve $(x-${a})(x-${b})<0$ with an interval argument.`,String.raw`The zeros are $${a}$ and $${b}$.`, 'With positive leading coefficient, the product is negative only between the zeros.',String.raw`The strict solution is $${a}<x<${b}$; neither endpoint is included.`);}),
    F('modulus-outer','P1',k=>{const a=at([1,2,3,4],k),r=at([1,2,3,2],k);return Q(String.raw`Solve $|x-${a}|\geq${r}$ on the real number line.`,String.raw`Distance from $${a}$ is at least $${r}$ on either side.`,String.raw`Branches are $x-${a}\geq${r}$ or $x-${a}\leq-${r}$.`,String.raw`Thus $x\leq${a-r}$ or $x\geq${a+r}$, inclusive at both boundary points.`);}),
  ],
  'AHL 2.16': [
    F('modulus-two-solutions','P1',k=>{const a=at([1,2,3,4],k),r=at([2,3,4,5],k);return Q(String.raw`Solve $|x-${a}|=${r}$ and verify both candidates.`,String.raw`Absolute value splits into $x-${a}=${r}$ and $x-${a}=-${r}$.`,String.raw`This yields $x=${a+r}$ and $x=${a-r}$.`,String.raw`Both lie distance $${r}$ from $${a}$, so both satisfy the original.`);}),
    F('modulus-interior','P1',k=>{const a=at([1,2,3,4],k),r=at([2,3,4,5],k);return Q(String.raw`Solve $|x-${a}|<${r}$ and describe the corresponding graph region.`,String.raw`Equivalently $-${r}<x-${a}<${r}$.`,String.raw`Add $${a}$ to get $${a-r}<x<${a+r}$.`,'This is the open interval between the two crossings of the V-shaped graph and the horizontal level.');}),
    F('modulus-variable-rhs','P1',k=>{const a=at([2,4,6,8],k);return Q(String.raw`Solve $|x-${a}|=x$ for real $x$, checking the sign of the right-hand side.`, 'First require $x\\geq0$ because absolute value cannot be negative.',String.raw`For $x<${a}$, $${a}-x=x$ gives $x=${a/2}$, which obeys the branch condition.`,String.raw`For $x\geq${a}$, $x-${a}=x$ is impossible since $${a}\neq0$; sole solution $x=${a/2}$.`);}),
  ],
};
