const F=(name,paper,build)=>({name,paper,build});
const Q=(prompt,...steps)=>({prompt,steps:steps.map(text=>[1,text])});
const at=(xs,k)=>xs[k%xs.length];
const gcd=(a,b)=>b===0?a:gcd(b,a%b);
export const families={
 'SL 3.1':[
  F('distance-in-space','P1',k=>{const [a,b,c,d]=at([[3,4,0,5],[3,4,12,13],[6,8,0,10],[0,5,12,13]],k);return Q(String.raw`Find the distance from $P=(0,0,0)$ to $Q=(${a},${b},${c})$ in three dimensions.`,String.raw`Coordinate differences are $(${a},${b},${c})$.`,String.raw`$PQ=\sqrt{${a*a}+${b*b}+${c*c}}=\sqrt{${d*d}}$.`,String.raw`The distance is $${d}$ units, which is nonnegative.`);}),
  F('spatial-midpoint','P1',k=>{const a=at([2,4,6,8],k),b=at([4,6,8,10],k),c=at([2,6,4,8],k);return Q(String.raw`Find the midpoint of the segment from $(0,2,4)$ to $(${a},${b},${c})$.`,String.raw`Average the two $x$-coordinates: $(0+${a})/2=${a/2}$.`,String.raw`Average $y$-coordinates to get $${(2+b)/2}$ and $z$-coordinates to get $${(4+c)/2}$.`,String.raw`Midpoint $(${a/2},${(2+b)/2},${(4+c)/2})$ lies halfway along the segment.`);}),
  F('right-pyramid-volume','P1',k=>{const A=at([12,15,24,30],k),h=at([3,6,4,9],k);return Q(String.raw`A right pyramid has base area $${A}$ cm$^2$ and perpendicular height $${h}$ cm. Find its volume with units.`,String.raw`Use $V=Ah/3$ for a pyramid, not $Ah$.`,String.raw`Substitute $V=${A}(${h})/3$.`,String.raw`The volume is $${A*h/3}$ cm$^3$.`);}),
 ],
 'SL 3.2':[
  F('right-triangle-ratios','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`A right triangle has legs $${3*s}$ and $${4*s}$, and hypotenuse $${5*s}$. Find sine and cosine of the acute angle opposite the shorter leg.`,String.raw`Opposite side is $${3*s}$ and hypotenuse $${5*s}$, so $\sin\theta=${3*s}/${5*s}=3/5$.`,String.raw`Adjacent side is $${4*s}$, so $\cos\theta=${4*s}/${5*s}=4/5$.`,'Both ratios are positive and less than one, consistent with an acute angle.');}),
  F('cosine-rule-right-check','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`Two sides of lengths $${3*s}$ and $${4*s}$ enclose $90^\circ$. Use the cosine rule to find the opposite side.`,String.raw`$c^2=(${3*s})^2+(${4*s})^2-2(${3*s})(${4*s})\cos90^\circ$.`,'The cosine term is zero at a right angle.',String.raw`$c^2=${25*s*s}$, so the positive length is $c=${5*s}$.`);}),
  F('triangle-area-sine','P1',k=>{const a=at([2,4,6,8],k),b=at([3,5,7,9],k);return Q(String.raw`A triangle has two sides $${a}$ cm and $${b}$ cm enclosing $30^\circ$. Find its area exactly.`,String.raw`Use $A=\tfrac12 ab\sin C$ with the *included* angle.`,String.raw`$A=\tfrac12(${a})(${b})\sin30^\circ=(${a*b})/4$.`,String.raw`The exact area is $${a*b/4}$ cm$^2$.`);}),
  F('sine-rule-side','P1',k=>{const a=at([2,4,6,8],k);return Q(String.raw`In triangle $ABC$, $A=30^\circ$, $B=45^\circ$, and side $a=${a}$ cm is opposite $A$. Find side $b$ opposite $B$ exactly.`,String.raw`Use the sine rule with matching sides and opposite angles: $b/\sin45^\circ=${a}/\sin30^\circ$.`,String.raw`$b=${a}(\sqrt2/2)/(1/2)=${a}\sqrt2$.`,String.raw`The third angle is $105^\circ$, so this is a valid triangle and $b=${a}\sqrt2$ cm.`);}),
 ],
 'SL 3.3':[
  F('elevation-height','P1',k=>{const d=at([10,15,20,25],k);return Q(String.raw`From ground level, a point $${d}$ m horizontally from a tower sees its top at $45^\circ$. Find its height if ground is level.`,String.raw`Use $\tan45^\circ=h/${d}$ in the right-triangle sketch.`,String.raw`$\tan45^\circ=1$, so $h=${d}(1)$.`,String.raw`The tower is $${d}$ m high under the stated ground-level model.`);}),
  F('east-north-route','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`A walker goes $${3*s}$ km east and then $${4*s}$ km north. Find straight-line distance and an expression for bearing clockwise from north.`,String.raw`Pythagoras gives distance $\sqrt{(${3*s})^2+(${4*s})^2}=${5*s}$ km.`,String.raw`The direction has east component $${3*s}$ and north component $${4*s}$.`,String.raw`Bearing is $\arctan(3/4)$ clockwise from north, about $36.9^\circ$; scale cancels.`);}),
  F('platform-elevation','P1',k=>{const d=at([8,12,16,20],k),p=at([1,2,3,4],k);return Q(String.raw`A sight line at $45^\circ$ rises from a platform $${p}$ m above level ground to a tower $${d}$ m horizontally away. Find the tower-top height above ground.`,String.raw`Vertical rise above the observer is $${d}\tan45^\circ=${d}$ m.`,String.raw`The observer already stands $${p}$ m above ground.`,String.raw`Tower-top height is $${p}+${d}=${p+d}$ m above ground.`);}),
 ],
 'SL 3.4':[
  F('degrees-to-radians','P1',k=>{const deg=at([30,45,60,90],k),rad=at(['\\pi/6','\\pi/4','\\pi/3','\\pi/2'],k);return Q(String.raw`Convert $${deg}^\circ$ to radians exactly and state the conversion factor.`,String.raw`Multiply degrees by $\pi/180$.`,String.raw`$${deg}^\circ=${deg}\pi/180$ radians.`,String.raw`This simplifies to $${rad}$ radians.`);}),
  F('sector-arc-area','P1',k=>{const r=at([2,4,6,8],k);return Q(String.raw`A circle has radius $${r}$ cm and central angle $\pi/2$ radians. Find arc length and sector area exactly.`,String.raw`Arc length is $r\theta=${r}(\pi/2)=${r/2}\pi$ cm.`,String.raw`Area is $\frac12r^2\theta=\frac12(${r*r})(\pi/2)$.`,String.raw`The sector area is $${r*r/4}\pi$ cm$^2$.`);}),
  F('sector-perimeter','P1',k=>{const r=at([2,4,6,8],k);return Q(String.raw`A sector of radius $${r}$ cm has angle $\pi$ radians. Find its full perimeter including straight sides.`,String.raw`Curved arc length is $r\theta=${r}\pi$ cm.`,String.raw`The two radii add $2r=${2*r}$ cm.`,String.raw`Full perimeter is $${r}\pi+${2*r}$ cm.`);}),
 ],
 'SL 3.5':[
  F('unit-circle-quadrant','P1',k=>{const [angle,sin,cos]=at([['\\pi/6','1/2','\\sqrt3/2'],['2\\pi/3','\\sqrt3/2','-1/2'],['5\\pi/4','-\\sqrt2/2','-\\sqrt2/2'],['11\\pi/6','-1/2','\\sqrt3/2']],k);return Q(String.raw`Give exact $\sin(${angle})$ and $\cos(${angle})$ using a reference angle and quadrant.`,String.raw`Locate $${angle}$ on the unit circle and identify the reference angle.`,String.raw`The vertical coordinate is $\sin(${angle})=${sin}$.`,String.raw`The horizontal coordinate is $\cos(${angle})=${cos}$, with signs from its quadrant.`);}),
  F('coterminal-angle','P1',k=>{const n=at([1,2,3,4],k);return Q(String.raw`Reduce the angle $${2*n}\pi+\pi/3$ to $[0,2\pi)$ and find its sine exactly.`,String.raw`A full turn is $2\pi$, so subtract $${n}$ full turns.`,String.raw`The coterminal angle in the required interval is $\pi/3$.`,String.raw`Sine is therefore $\sin(\pi/3)=\sqrt3/2$.`);}),
  F('undefined-tangent','P1',k=>{const n=at([0,1,2,3],k);return Q(String.raw`Determine whether $\tan(\pi/2+${n}\pi)$ is defined, using unit-circle coordinates.`,String.raw`At $\pi/2+${n}\pi$, the cosine coordinate is $0$.`,String.raw`Tangent is $\sin\theta/\cos\theta$, so this would divide by zero.`, 'It is undefined as a real number; a large calculator display is not a finite answer.');}),
 ],
 'SL 3.6':[
  F('pythagorean-sign','P1',k=>{const [a,b]=at([[3,5],[4,5],[5,13],[12,13]],k);return Q(String.raw`If $\cos x=${a}/${b}$ and $x$ is in quadrant IV, find $\sin x$ exactly.`,String.raw`Use $\sin^2x=1-\cos^2x=(${b*b-a*a})/${b*b}$.`,String.raw`The sine magnitude is $\sqrt{${b*b-a*a}}/${b}$.`,String.raw`Quadrant IV has negative sine, so $\sin x=-${Math.sqrt(b*b-a*a)}/${b}$.`);}),
  F('double-angle-values','P1',k=>{const [a,b]=at([[3,4],[4,3],[5,12],[12,5]],k),hyp=Math.hypot(a,b);return Q(String.raw`An acute angle has $\sin x=${a}/${hyp}$ and $\cos x=${b}/${hyp}$. Find $\sin2x$ and $\cos2x$.`,String.raw`$\sin2x=2\sin x\cos x=2(${a})(${b})/${hyp*hyp}=${2*a*b}/${hyp*hyp}$.`,String.raw`$\cos2x=\cos^2x-\sin^2x=(${b*b}-${a*a})/${hyp*hyp}$.`,String.raw`Thus $\cos2x=${b*b-a*a}/${hyp*hyp}$; both results satisfy $\sin^22x+\cos^22x=1$.`);}),
  F('identity-pythagorean','P1',k=>{const x=at(['x','t','\\theta','u'],k);return Q(String.raw`Show $\dfrac{\sin^2 ${x}}{1+\cos ${x}}=1-\cos ${x}$ wherever the denominator is nonzero.`,String.raw`Use $\sin^2 ${x}=1-\cos^2 ${x}$.`,String.raw`Factor as $(1-\cos ${x})(1+\cos ${x})$ and cancel $1+\cos ${x}$.`,String.raw`The result is $1-\cos ${x}$ when $1+\cos ${x}\neq0$.`);}),
 ],
 'SL 3.7':[
  F('sine-features','P1',k=>{const a=at([2,3,4,5],k),b=at([2,3,4,5],k),d=at([1,2,3,4],k);return Q(String.raw`For $y=${a}\sin(${b}x)+${d}$, give amplitude, period, midline and range.`,String.raw`Amplitude is $|${a}|=${a}$ and midline is $y=${d}$.`,String.raw`Period is $2\pi/${b}$ radians of input.`,String.raw`Range is $[${d-a},${d+a}]$ because sine lies between $-1$ and $1$.`);}),
  F('cosine-extremes','P1',k=>{const a=at([1,2,3,4],k),d=at([2,3,4,5],k);return Q(String.raw`For $y=${a}\cos x+${d}$, find its greatest and least values, and a point attaining the greatest.`,String.raw`Cosine ranges from $-1$ to $1$, so multiply by $${a}>0$.`,String.raw`Maximum is $${d+a}$ and minimum is $${d-a}$.`,String.raw`At $x=0$, $\cos0=1$, giving the maximum point $(0,${d+a})$.`);}),
  F('shift-sine','P1',k=>{const shift=at(['\\pi/6','\\pi/4','\\pi/3','\\pi/2'],k);return Q(String.raw`Describe the phase shift of $y=\sin(x-${shift})$ from $y=\sin x$ and give one zero.`,String.raw`The input $x-${shift}$ shifts the graph right by $${shift}$.`,String.raw`Set the inner angle to zero: $x-${shift}=0$.`,String.raw`At $x=${shift}$, the output is $\sin0=0$; the amplitude and period are unchanged.`);}),
 ],
 'SL 3.8':[
  F('sine-interval-roots','P1',k=>{const [value,roots]=at([['1/2',['\\pi/6','5\\pi/6']],['\\sqrt2/2',['\\pi/4','3\\pi/4']],['\\sqrt3/2',['\\pi/3','2\\pi/3']],['1',['\\pi/2']],],k);return Q(String.raw`Solve $\sin x=${value}$ for $0\leq x<2\pi$; list every exact root.`,String.raw`Use the reference angle whose sine is $${value}$.`,String.raw`Sine is positive in quadrants I and II (or one top-axis point for sine $1$).`,String.raw`The complete solution in this interval is $x=${roots.join('\text{ or }')}$.`);}),
  F('cosine-interval-roots','P1',k=>{const [value,roots]=at([['1/2',['\\pi/3','5\\pi/3']],['-1/2',['2\\pi/3','4\\pi/3']],['0',['\\pi/2','3\\pi/2']],['-1',['\\pi']]],k);return Q(String.raw`Solve $\cos x=${value}$ on $0\leq x<2\pi$ with exact angles.`,String.raw`Use the unit-circle horizontal coordinate and its signs.`,String.raw`The reference angle determines where cosine has value $${value}$.`,String.raw`All roots in the stated interval are $x=${roots.join('\text{ or }')}$.`);}),
  F('tangent-period','P1',k=>{const [value,roots]=at([['1',['\\pi/4','5\\pi/4']],['-1',['3\\pi/4','7\\pi/4']],['0',['0','\\pi']],['\\sqrt3',['\\pi/3','4\\pi/3']]],k);return Q(String.raw`Solve $\tan x=${value}$ for $0\leq x<2\pi$, remembering its period.`,String.raw`Tangent has period $\pi$ where it is defined.`,String.raw`Select an angle with tangent $${value}$ and add $\pi$ as needed.`,String.raw`The required roots are $x=${roots.join('\text{ or }')}$.`);}),
 ],
 'AHL 3.9':[
  F('sec-csc-triple','P1',k=>{const [a,b,h]=at([[3,4,5],[5,12,13],[8,15,17],[7,24,25]],k);return Q(String.raw`For an acute angle with $\sin x=${a}/${h}$ and $\cos x=${b}/${h}$, find $\sec x$ and $\csc x$.`,String.raw`Secant is $1/\cos x=${h}/${b}$.`,String.raw`Cosecant is $1/\sin x=${h}/${a}$.`, 'Both denominators are nonzero for the specified acute angle.');}),
  F('sec-tan-identity','P1',k=>{const t=at([1,2,3,4],k);return Q(String.raw`If $\tan x=${t}$ and $x$ is in quadrant I, find $\sec x$ using a Pythagorean identity.`,String.raw`$1+\tan^2x=\sec^2x=1+${t*t}=${1+t*t}$.`,String.raw`Quadrant I gives positive cosine and hence positive secant.`,String.raw`Therefore $\sec x=\sqrt{${1+t*t}}$.`);}),
  F('reciprocal-domain','P1',k=>{const t=at([0,1,2,3],k);return Q(String.raw`Is $\csc(${t}\pi)$ defined? Explain with sine rather than calculator output.`,String.raw`$\sin(${t}\pi)=0$ at an integer multiple of $\pi$.`,String.raw`$\csc\theta=1/\sin\theta$ would require division by zero.`, 'Therefore cosecant is undefined at the specified angle.');}),
 ],
 'AHL 3.10':[
  F('sine-sum-exact','P1',k=>{const [A,B,expr]=at([['30','45','(\\sqrt6+\\sqrt2)/4'],['45','30','(\\sqrt6+\\sqrt2)/4'],['60','30','1'],['30','60','1']],k);return Q(String.raw`Evaluate $\sin(${A}^\circ+${B}^\circ)$ exactly using the sum identity.`,String.raw`Use $\sin(A+B)=\sin A\cos B+\cos A\sin B$.`,String.raw`Insert the exact special-angle sine and cosine values for $${A}^\circ$ and $${B}^\circ$.`,String.raw`The exact value is $${expr}$; compare with the known angle $${Number(A)+Number(B)}^\circ$.`);}),
  F('cosine-difference','P1',k=>{const [A,B,expr]=at([['60','30','\\sqrt3/2'],['45','30','(\\sqrt6+\\sqrt2)/4'],['90','30','1/2'],['60','45','(\\sqrt6+\\sqrt2)/4']],k);return Q(String.raw`Use a compound-angle identity to evaluate $\cos(${A}^\circ-${B}^\circ)$ exactly.`,String.raw`Use $\cos(A-B)=\cos A\cos B+\sin A\sin B$.`,String.raw`Substitute exact ratios for $${A}^\circ$ and $${B}^\circ$.`,String.raw`The result is $${expr}$, consistent with the angle $${Number(A)-Number(B)}^\circ$.`);}),
  F('tangent-sum','P1',k=>{const t=at([2,3,4,5],k);return Q(String.raw`Given $\tan A=1$ and $\tan B=1/${t}$, calculate $\tan(A+B)$ if the angles and sum have defined tangent.`,String.raw`$\tan(A+B)=(1+1/${t})/(1-1/${t})$.`,String.raw`The denominator is $(${t}-1)/${t}\neq0$ for $${t}>1$.`,String.raw`Simplifying gives $\tan(A+B)=(${t}+1)/(${t}-1)$.`);}),
 ],
 'AHL 3.11':[
  F('ratios-from-quadrant','P1',k=>{const [a,b,h]=at([[3,4,5],[5,12,13],[8,15,17],[7,24,25]],k);return Q(String.raw`If $\sin x=-${a}/${h}$ and $x$ lies in quadrant IV, find $\cos x$ and $\tan x$.`,String.raw`$\cos^2x=1-(${a}/${h})^2=${b*b}/${h*h}$.`,String.raw`Cosine is positive in quadrant IV, so $\cos x=${b}/${h}$.`,String.raw`$\tan x=\sin x/\cos x=-${a}/${b}$.`);}),
  F('double-angle-from-tangent','P1',k=>{const t=at([1,2,3,4],k),p=2*t,q=1+t*t,g=gcd(p,q),answer=q/g===1?String(p/g):`${p/g}/${q/g}`;return Q(String.raw`If $\tan x=${t}$ and cosine is nonzero, express $\sin2x$ using tangent alone.`,String.raw`$\sin2x=2\sin x\cos x=2\tan x\cos^2x$.`,String.raw`Use $\cos^2x=1/(1+\tan^2x)$.`,String.raw`Thus $\sin2x=2(${t})/(1+${t*t})=${answer}$.`);}),
  F('cot-from-tan','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`If $\tan x=${a}/${b}$, find $\cot x$ and $\sec^2x$ where defined.`,String.raw`Reciprocal tangent gives $\cot x=${b}/${a}$.`,String.raw`The Pythagorean relation gives $\sec^2x=1+\tan^2x$.`,String.raw`So $\sec^2x=1+${a*a}/${b*b}=(${a*a+b*b})/${b*b}$.`);}),
 ],
 'AHL 3.12':[
  F('vector-norm','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`Find the magnitude of $\mathbf v=(${3*s},${4*s},0)$ and one unit vector in its direction.`,String.raw`$|\mathbf v|=\sqrt{(${3*s})^2+(${4*s})^2}=${5*s}$.`,String.raw`Divide each component by $${5*s}$: $\mathbf v/|\mathbf v|=(3/5,4/5,0)$.`, 'The resulting vector has magnitude one and the same direction as the original.');}),
  F('position-displacement','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`From $P=(${a},0,1)$ to $Q=(${a+b},2,4)$, find $\overrightarrow{PQ}$ and its squared length.`,String.raw`Subtract terminal minus initial coordinates: $\overrightarrow{PQ}=(${b},2,3)$.`,String.raw`Its squared magnitude is $${b}^2+2^2+3^2=${b*b+13}$.`,String.raw`Thus the distance is $\sqrt{${b*b+13}}$; reversing the arrow reverses direction only.`);}),
  F('linear-combination','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`For $\mathbf u=(${a},1)$ and $\mathbf v=(1,${b})$, find $2\mathbf u-\mathbf v$.`,String.raw`$2\mathbf u=(${2*a},2)$.`,String.raw`Subtract components of $\mathbf v$: $(${2*a},2)-(1,${b})$.`,String.raw`The result is $(${2*a-1},${2-b})$.`);}),
 ],
 'AHL 3.13':[
  F('dot-product-components','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find the scalar product of $\mathbf u=(${a},1,0)$ and $\mathbf v=(2,${b},3)$.`,String.raw`Multiply matching coordinates: $${a}(2)+1(${b})+0(3)$.`,String.raw`This gives $${2*a}+${b}=${2*a+b}$.`,String.raw`Therefore $\mathbf u\cdot\mathbf v=${2*a+b}$.`);}),
  F('perpendicular-parameter','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find $t$ such that $(${a},${b},0)\cdot(${b},t,1)=0$.`,String.raw`The scalar product equals $${a*b}+${b}t$.`,String.raw`Set $${a*b}+${b}t=0$ and divide by $${b}\neq0$.`,String.raw`$t=-${a}$ gives zero, so the nonzero vectors are perpendicular.`);}),
  F('dot-angle','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`Find the angle between $\mathbf u=(${s},0)$ and $\mathbf v=(${s},${s}\sqrt3)$.`,String.raw`$\mathbf u\cdot\mathbf v=${s*s}$ and the magnitudes are $${s}$ and $${2*s}$.`,String.raw`Thus $\cos\theta=${s*s}/(${s}\cdot${2*s})=1/2$.`,String.raw`The smaller angle is $\theta=60^\circ$.`);}),
 ],
 'AHL 3.14':[
  F('line-through-two-points','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Write a vector line through $P=(${a},0,1)$ and $Q=(${a+b},2,4)$, using a real parameter.`,String.raw`Direction $Q-P=(${b},2,3)$ is nonzero.`,String.raw`Anchor at $P$ and add a multiple of that direction.`,String.raw`One valid form is $\mathbf r=(${a},0,1)+t(${b},2,3)$ for $t\in\mathbb R$.`);}),
  F('point-on-line','P1',k=>{const a=at([1,2,3,4],k),t=at([2,3,4,5],k);return Q(String.raw`Check whether $(${a+t},${2*t},${3*t})$ lies on $\mathbf r=(${a},0,0)+s(1,2,3)$.`,String.raw`The first coordinate requires $s=${t}$.`,String.raw`Then the other coordinates are $2s=${2*t}$ and $3s=${3*t}$.`,String.raw`One common parameter works, so the point is on the line at $s=${t}$.`);}),
  F('parametric-constant-coordinate','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Convert $\mathbf r=(${a},${b},1)+t(2,0,3)$ into three parametric coordinate equations.`,String.raw`Read the first component as $x=${a}+2t$.`,String.raw`The zero middle direction keeps $y=${b}$ for every $t$.`,String.raw`The third coordinate is $z=1+3t$, with $t\in\mathbb R$.`);}),
  F('cartesian-symmetric-line','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Express $\mathbf r=(${a},${b},1)+t(2,3,4)$ as a three-dimensional Cartesian symmetric line equation.`,String.raw`The parametric equations are $x=${a}+2t$, $y=${b}+3t$ and $z=1+4t$.`,String.raw`Therefore $t=(x-${a})/2=(y-${b})/3=(z-1)/4$.`,String.raw`The Cartesian form is $(x-${a})/2=(y-${b})/3=(z-1)/4$; division is allowed because all three direction components are nonzero.`);}),
 ],
 'AHL 3.15':[
  F('coincident-lines','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Classify $L_1=(1,0,0)+t(1,2,0)$ and $L_2=(${a+1},${2*a},0)+s(2,4,0)$.`, 'The direction $(2,4,0)$ is twice $(1,2,0)$, so the lines are parallel in orientation.',String.raw`$(${a+1},${2*a},0)$ lies on $L_1$ at $t=${a}$.`, 'They share a point and parallel directions, so they are coincident, not distinct parallels.');}),
  F('parallel-distinct','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Classify $L_1=(0,0,0)+t(1,0,0)$ and $L_2=(0,${a},0)+s(2,0,0)$.`, 'Directions $(1,0,0)$ and $(2,0,0)$ are parallel.',String.raw`Every point on $L_1$ has $y=0$; every point on $L_2$ has $y=${a}\neq0$.`, 'The lines are distinct and parallel, so no intersection exists.');}),
  F('skew-lines','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Classify $L_1=(t,0,0)$ and $L_2=(0,s,${a})$ in three dimensions.`, 'Their directions $(1,0,0)$ and $(0,1,0)$ are not scalar multiples.',String.raw`The first line always has $z=0$ while the second always has $z=${a}\neq0$.`, 'They cannot meet and are not parallel, so they are skew lines.');}),
  F('intersecting-lines','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Classify $L_1=(t,t,0)$ and $L_2=(${a},s,0)$ in three dimensions, and find any intersection.`,String.raw`Matching the first coordinates gives $t=${a}$; the second then gives $s=${a}$.`,String.raw`Both lines have $z=0$, so at these parameters they share $(${a},${a},0)$.`, 'Their direction vectors $(1,1,0)$ and $(0,1,0)$ are not parallel, so this is a single intersection.');}),
 ],
 'AHL 3.16':[
  F('cross-parallelogram','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`For $\mathbf u=(${a},0,0)$ and $\mathbf v=(0,${b},0)$, calculate $\mathbf u\times\mathbf v$ and parallelogram area.`,String.raw`Right-hand-rule component calculation gives $\mathbf u\times\mathbf v=(0,0,${a*b})$.`,String.raw`Its magnitude is $${a*b}$.`,String.raw`The parallelogram area is $${a*b}$ square units; the associated triangle has half that area.`);}),
  F('cross-order','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Let $\mathbf u=(${a},0,0)$ and $\mathbf v=(0,1,0)$. Compare $\mathbf u\times\mathbf v$ and $\mathbf v\times\mathbf u$.`,String.raw`$\mathbf u\times\mathbf v=(0,0,${a})$.`,String.raw`Reversing the order gives $(0,0,-${a})$.`,String.raw`The vectors are opposites with equal magnitude $${a}$, both perpendicular to the input plane.`);}),
  F('triple-volume','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k),c=at([1,2,3,4],k);return Q(String.raw`Three edges of a box are $(${a},0,0)$, $(0,${b},0)$ and $(0,0,${c})$. Use a scalar triple product for volume.`,String.raw`First cross product $((${a},0,0)\times(0,${b},0))=(0,0,${a*b})$.`,String.raw`Dot with $(0,0,${c})$ to obtain $${a*b*c}$.`,String.raw`The absolute scalar triple product gives volume $${a*b*c}$ cubic units.`);}),
 ],
 'AHL 3.17':[
  F('normal-plane','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Find the plane through $(${a},0,0)$ with normal vector $(1,${b},2)$.`,String.raw`Normal form is $(1,${b},2)\cdot[(x,y,z)-(${a},0,0)]=0$.`,String.raw`This gives $(x-${a})+${b}y+2z=0$.`,String.raw`Cartesian form is $x+${b}y+2z=${a}$; the given point checks.`);}),
  F('test-point-on-plane','P1',k=>{const a=at([1,2,3,4],k),b=at([2,3,4,5],k);return Q(String.raw`Is $P=(${a},${b},0)$ on the plane $x+y+z=${a+b}$? Explain by substitution.`,String.raw`Evaluate the left side at $P$: $${a}+${b}+0=${a+b}$.`,String.raw`This equals the stated right side $${a+b}$.`, 'The point lies on the plane; one coordinate equation suffices for this membership check.');}),
  F('plane-from-axis-directions','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find a Cartesian equation for the plane through $(0,0,${a})$ spanned by directions $(1,0,0)$ and $(0,1,0)$.`, 'The two independent directions span all horizontal motion in $x$ and $y$.', 'A normal is $(0,0,1)$, perpendicular to both.',String.raw`The plane keeps height fixed: $z=${a}$.`);}),
 ],
 'AHL 3.18':[
  F('line-meets-plane','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Find the intersection of $\mathbf r=(1,0,0)+t(1,2,1)$ with the plane $x+y+z=${1+4*a}$.`,String.raw`Substitute $x=1+t$, $y=2t$, $z=t$ to get $1+4t=${1+4*a}$.`,String.raw`The line parameter solving the plane equation is $t=${a}$.`,String.raw`The intersection is $(${1+a},${2*a},${a})$, which satisfies the plane equation.`);}),
  F('line-contained-or-parallel','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Classify the line $(x,y,z)=(0,${a},0)+t(1,-1,0)$ relative to the plane $x+y=${a}$.`,String.raw`On the line, $x+y=t+${a}-t=${a}$ for every parameter value.`, 'The direction is parallel to the plane because its dot product with normal $(1,1,0)$ is zero.', 'Every line point also satisfies the plane, so the entire line is contained in it.');}),
  F('plane-plane-intersection','P1',k=>{const a=at([2,4,6,8],k),b=at([0,2,4,6],k);return Q(String.raw`Find the intersection line of the planes $x+y=${a}$ and $x-y=${b}$ in $\mathbb R^3$.`,String.raw`Add the equations: $2x=${a+b}$, so $x=${(a+b)/2}$.`,String.raw`Subtract them: $2y=${a-b}$, so $y=${(a-b)/2}$.`,String.raw`$z$ is free; intersection line is $(${(a+b)/2},${(a-b)/2},t)$ for $t\in\mathbb R$.`);}),
 ],
};
