// Independently authored parameterized practice. Each family is a distinct skill;
// k=0..3 makes small exact variants with checked, explicit marking steps.
const F = (name, paper, build) => ({ name, paper, build });
const Q = (prompt, ...steps) => ({ prompt, steps: steps.map((text) => [1, text]) });
const at = (xs, k) => xs[k % xs.length];
const C = (n, r) => { let out=1; for(let j=1;j<=r;j++)out=out*(n-j+1)/j; return out; };
export const families = {
  'SL 1.1': [
    F('normalize-small', 'P1', k => { const a=at([37,54,82,69],k), d=at([5,6,4,7],k); return Q(String.raw`Write $${a}/10^{${d}}$ in normalized scientific notation. State why your coefficient is valid.`, String.raw`$${a}=(${a/10})10$, so divide the coefficient by ten.`, String.raw`$${a}/10^{${d}}=${a/10}\times10^{${1-d}}$.`, 'The coefficient lies between 1 and 10, so the answer is normalized.'); }),
    F('multiply-powers', 'P1', k => { const a=at([2,3,4,5],k), b=at([3,2,5,4],k), e=at([4,5,3,6],k); const product=a*b, c=product>=10?product/10:product, shift=product>=10?1:0; return Q(String.raw`Calculate $(${a}\times10^{${e}})(${b}\times10^{-2})$ in standard form, without a calculator.`, String.raw`Multiply coefficients: $${a}(${b})=${product}$.`, String.raw`Add exponents: $10^{${e}}10^{-2}=10^{${e-2}}$.`, String.raw`Normalize: $${product}\times10^{${e-2}}=${c}\times10^{${e-2+shift}}$.`); }),
    F('divide-powers', 'P1', k => { const a=at([6,8,9,4],k), b=at([2,4,3,2],k), e=at([3,5,4,6],k); return Q(String.raw`Divide $(${a}\times10^{${e}})/(${b}\times10^{-2})$ and express the quotient in standard form.`, String.raw`Divide the coefficients: $${a}/${b}=${a/b}$.`, String.raw`Subtract exponents: $${e}-(-2)=${e+2}$.`, String.raw`The quotient is $${a/b}\times10^{${e+2}}$, with valid normalized coefficient.`); }),
  ],
  'SL 1.2': [
    F('term-arithmetic', 'P1', k => { const a=at([4,7,11,2],k), d=at([3,-2,4,-3],k), n=at([8,9,6,10],k), u=a+(n-1)*d; return Q(String.raw`An arithmetic sequence starts at $${a}$ and has difference $${d}$. Find $u_{${n}}$ and explain the index.`, String.raw`There are $${n-1}$ jumps from term $1$ to term $${n}$.`, String.raw`Use $u_n=u_1+(n-1)d=${a}+(${n-1})(${d})$.`, String.raw`Hence $u_{${n}}=${u}$. Check the sign of the difference.`); }),
    F('sum-arithmetic', 'P1', k => { const a=at([3,4,6,8],k), d=at([2,3,-1,4],k), n=at([6,8,10,12],k), u=a+(n-1)*d, sum=n*(a+u)/2; return Q(String.raw`The first term is $${a}$ and difference $${d}$. Calculate the sum of the first $${n}$ terms.`, String.raw`Find the last term: $u_{${n}}=${a}+${n-1}(${d})=${u}$.`, String.raw`Apply $S_n=\frac n2(u_1+u_n)=\frac{${n}}2(${a}+${u})$.`, String.raw`The finite sum is $S_{${n}}=${sum}$.`); }),
    F('recover-difference', 'P1', k => { const a=at([2,5,3,8],k), d=at([3,4,-2,5],k), p=at([3,4,2,5],k), r=p+at([4,3,5,2],k); const x=a+(p-1)*d, y=a+(r-1)*d; return Q(String.raw`An arithmetic sequence has $u_{${p}}=${x}$ and $u_{${r}}=${y}$. Find $d$ and $u_1$.`, String.raw`Subtract: $(${r}-${p})d=${y}-${x}=${y-x}$.`, String.raw`Thus $d=${d}$; use $u_{${p}}=u_1+${p-1}d$.`, String.raw`$u_1=${x}-${p-1}(${d})=${a}$. Both given terms check.`); }),
  ],
  'SL 1.3': [
    F('term-geometric', 'P1', k => { const a=at([2,3,4,5],k), r=at([2,-2,3,-1],k), n=at([5,4,3,6],k); return Q(String.raw`A geometric sequence has $u_1=${a}$ and ratio $r=${r}$. Find $u_{${n}}$.`, String.raw`Use $u_n=u_1r^{n-1}$, with exponent $${n-1}$.`, String.raw`Substitute $u_{${n}}=${a}(${r})^{${n-1}}$.`, String.raw`Evaluate with parentheses: $u_{${n}}=${a*r**(n-1)}$.`); }),
    F('finite-geometric', 'P1', k => { const a=at([2,3,5,4],k), r=at([2,3,-2,2],k), n=at([4,3,4,5],k), sum=a*(1-r**n)/(1-r); return Q(String.raw`Find $S_{${n}}$ for a geometric sequence with first term $${a}$ and ratio $${r}$.`, String.raw`The ratio $${r}\neq1$, so $S_n=u_1(1-r^n)/(1-r)$.`, String.raw`Substitute $${a}(1-(${r})^{${n}})/(1-(${r}))$.`, String.raw`Simplify the finite sum: $S_{${n}}=${sum}$.`); }),
    F('constant-geometric', 'P1', k => { const a=at([3,5,7,9],k), n=at([4,6,8,10],k); return Q(String.raw`A geometric sequence has $u_1=${a}$ and ratio $r=1$. Find the first $${n}$ terms' sum and explain why the usual quotient formula is unsuitable.`, String.raw`Every term remains $${a}$ because multiplication by $1$ changes nothing.`, String.raw`There are $${n}$ equal terms, so $S_{${n}}=${n}(${a})=${n*a}$.`, 'The usual formula has denominator $1-r=0$ here, so use direct counting.'); }),
  ],
  'SL 1.4': [
    F('compound-annually', 'P2', k => { const P=at([1000,1500,2000,2400],k), rate=at([2,3,4,5],k), t=at([3,4,2,5],k), V=(P*(1+rate/100)**t).toFixed(2); return Q(String.raw`A deposit of €${P} earns ${rate}% compound interest annually for ${t} years. Find the modeled future value to cents.`, String.raw`The annual factor is $1+${rate}/100=${(1+rate/100).toFixed(2)}$.`, String.raw`There are $${t}$ annual periods, so $FV=${P}(1+${rate}/100)^{${t}}$.`, `Using full precision before rounding gives €${V}.`); }),
    F('depreciate', 'P2', k => { const P=at([4000,6000,8000,10000],k), rate=at([10,15,20,25],k), t=at([2,3,4,2],k), V=(P*(1-rate/100)**t).toFixed(2); return Q(String.raw`A €${P} item loses ${rate}% of its current value each year for ${t} years. Find its modeled remaining value.`, String.raw`Annual multiplier $1-${rate}/100=${1-rate/100}$.`, String.raw`After $${t}$ years the value is $${P}(1-${rate}/100)^{${t}}$.`, `It is €${V} to cents, not the original price minus the same amount each year.`); }),
    F('present-value', 'P2', k => { const P=at([1000,2000,3000,4000],k), rate=at([2,3,4,5],k), t=at([2,3,2,4],k), V=(P*(1+rate/100)**t).toFixed(2); return Q(String.raw`A future balance is €${V} after ${t} years at ${rate}% annual compounding. Estimate the original balance to the nearest euro.`, String.raw`Use $FV=PV(1+${rate}/100)^{${t}}$.`, String.raw`Rearrange $PV=${V}/(1+${rate}/100)^{${t}}$.`, `The initial balance is approximately €${P} to the nearest euro; the displayed future balance was rounded to cents.`); }),
  ],
  'SL 1.5': [
    F('log-inverse', 'P1', k => { const b=at([2,3,4,5],k), power=at([3,2,3,2],k), c=at([1,2,3,4],k); return Q(String.raw`Solve $\log_{${b}}(x+${c})=${power}$ and check the argument is positive.`, String.raw`The domain requires $x+${c}>0$.`, String.raw`Rewrite exponentially: $x+${c}=${b}^{${power}}=${b**power}$.`, String.raw`$x=${b**power-c}$ is in the domain and reproduces the given logarithm.`); }),
    F('log-base', 'P1', k => { const b=at([2,3,4,5],k), n=at([3,4,2,3],k); return Q(String.raw`Find $y$ exactly when $\log_{${b}}(${b**n})=y$. Explain why your logarithm is defined.`, String.raw`$${b}>0$, $${b}\neq1$, and the argument $${b**n}>0$.`, String.raw`Exponentially, $${b}^y=${b**n}$.`, String.raw`Equal positive bases give $y=${n}$.`); }),
    F('log-domain', 'P1', k => { const a=at([2,3,4,5],k), b=at([3,5,7,9],k); return Q(String.raw`For real $x$, state the domain of $f(x)=\log_2(${a}x-${b})$ and its vertical asymptote.`, String.raw`A real log needs $${a}x-${b}>0$.`, String.raw`Solve $x>${b}/${a}$ because $${a}>0$.`, String.raw`The argument approaches zero at $x=${b}/${a}$, so that is the vertical asymptote.`); }),
  ],
  'SL 1.6': [
    F('even-product-proof', 'P1', k => { const h=at([1,3,5,7],k); return Q(String.raw`Prove for every integer $n$ that $(n+${h})(n+${h+1})$ is even. State why testing $n=1$ alone is inadequate.`, String.raw`$n+${h}$ and $n+${h+1}$ are consecutive integers for any $n\in\mathbb Z$.`, 'Exactly one of two consecutive integers is even, so their product has a factor of two.', 'The argument covers all integers; one numerical check cannot prove the universal claim.'); }),
    F('odd-sum-proof', 'P1', k => { const h=at([1,3,5,7],k); return Q(String.raw`Show for every integer $n$ that the sum of $2n+${h}$ and $2n+${h+2}$ is even.`, String.raw`Their sum is $(2n+${h})+(2n+${h+2})=4n+${2*h+2}$.`, String.raw`Factor $2$: $4n+${2*h+2}=2(2n+${h+1})$.`, 'The factor in parentheses is an integer, proving divisibility by two.'); }),
    F('refute-odd-claim', 'P1', k => { const b=at([2,4,6,8],k); return Q(String.raw`A claim says $n(n+1)+${b}$ is odd for every integer $n$. Refute it and explain its actual parity.`, String.raw`Take $n=0$: the expression equals $${b}$, which is even.`, 'Consecutive integer products are always even, for negative integers too.', String.raw`Adding the even number $${b}$ leaves an even number, so the universal odd claim fails.`); }),
  ],
  'SL 1.7': [
    F('exponent-laws', 'P1', k => { const a=at([2,3,4,5],k), b=at([3,2,4,3],k), c=at([1,2,3,2],k); return Q(String.raw`Simplify $x^{${a}}x^{${b}}/x^{${c}}$ for $x\neq0$.`, String.raw`Multiplying like bases adds powers: $x^{${a}}x^{${b}}=x^{${a+b}}$.`, String.raw`Dividing by $x^{${c}}$ subtracts its exponent.`, String.raw`The result is $x^{${a+b-c}}$ on the stated nonzero domain.`); }),
    F('log-product-domain', 'P1', k => { const base=at([2,3,4,5],k), power=at([3,2,3,2],k), factor=at([2,3,4,5],k); return Q(String.raw`Solve $\log_{${base}}(${factor}x)= ${power}$ and check the original domain.`, String.raw`The argument requires $${factor}x>0$, so $x>0$.`, String.raw`Exponentiation gives $${factor}x=${base}^{${power}}=${base**power}$.`, String.raw`$x=${base**power}/${factor}$ is positive and satisfies the equation.`); }),
    F('log-sum-solve', 'P1', k => { const b=at([2,3,4,5],k), a=at([1,2,3,4],k), shift=at([1,2,1,3],k), value=b**shift+a; return Q(String.raw`Solve $\log_{${b}}(x-${a})+\log_{${b}}${b}=${shift+1}$ over the reals.`, String.raw`Require $x-${a}>0$, or $x>${a}$.`, String.raw`Since $\log_{${b}}${b}=1$, $\log_{${b}}(x-${a})=${shift}$.`, String.raw`$x-${a}=${b**shift}$, so $x=${value}>${a}$.`); }),
  ],
  'SL 1.8': [
    F('infinite-geo', 'P1', k => { const a=at([6,9,12,15],k), r=at([1/2,-1/2,1/3,-1/3],k), denom=at(['1/2','3/2','2/3','4/3'],k), sum=a/(1-r); return Q(String.raw`Find the infinite sum of the geometric series with $u_1=${a}$ and $r=${r}$, if it exists.`, String.raw`$|${r}|<1$, so the partial sums converge.`, String.raw`Use $S_\infty=u_1/(1-r)=${a}/(${denom})$.`, String.raw`The limit is $${sum}$; no finite-sum term count is needed.`); }),
    F('find-ratio', 'P1', k => { const a=at([8,12,16,20],k), r=at([1/2,1/3,1/4,1/5],k), b=a*r, sum=a/(1-r); return Q(String.raw`A geometric series begins $${a},${b},\ldots$. Find the ratio and its infinite sum, explaining convergence.`, String.raw`$r=u_2/u_1=${b}/${a}=${r}$.`, String.raw`Because $|r|<1$, $S_\infty=${a}/(1-${r})$.`, String.raw`The infinite total is $${sum}$.`); }),
    F('bounce-travel', 'P2', k => { const H=at([4,6,8,10],k); return Q(String.raw`A ball first drops ${H} m, then rebounds to half each previous height. Find the total idealized travel over all bounces.`, String.raw`The first downward ${H} m occurs only once. Later upward distances total $${H}/2+${H}/4+\cdots=${H}$.`, String.raw`Later downward distances have the same total $${H}$, since the rebound ratio is $1/2<1$.`, String.raw`Total travel is $${H}+${H}+${H}=${3*H}$ m.`); }),
  ],
  'SL 1.9': [
    F('binomial-x2-coefficient', 'P1', k => { const n=at([3,4,5,6],k), a=at([2,3,2,4],k), v=C(n,2)*a*a; return Q(String.raw`Find the coefficient of $x^2$ in $(1+${a}x)^{${n}}$ without fully expanding.`, String.raw`Use the $r=2$ term $\binom{${n}}2(1)^{${n-2}}(${a}x)^2$.`, String.raw`$\binom{${n}}2=${C(n,2)}$ and $(${a}x)^2=${a*a}x^2$.`, String.raw`The coefficient is $${v}$.`); }),
    F('binomial-signed-x3', 'P1', k => { const n=at([4,5,6,7],k), a=at([1,2,1,2],k), v=-C(n,3)*a**3; return Q(String.raw`Find the signed coefficient of $x^3$ in $(1-${a}x)^{${n}}$.`, String.raw`Select the term with $r=3$: $\binom{${n}}3(-${a}x)^3$.`, String.raw`$(-${a})^3=-${a**3}$ and $\binom{${n}}3=${C(n,3)}$.`, String.raw`The requested coefficient is $${v}$, negative because the power is odd.`); }),
    F('pascal-check', 'P1', k => { const n=at([5,6,7,8],k), r=at([2,3,2,3],k); return Q(String.raw`Verify Pascal's rule $\binom{${n}}{${r}}=\binom{${n-1}}{${r-1}}+\binom{${n-1}}{${r}}$ by evaluating all three counts.`, String.raw`Count the left side: $\binom{${n}}{${r}}=${C(n,r)}$.`, String.raw`The two right-side counts are $${C(n-1,r-1)}$ and $${C(n-1,r)}$.`, String.raw`Their sum is $${C(n-1,r-1)}+${C(n-1,r)}=${C(n,r)}$, so the rule holds here.`); }),
  ],
  'AHL 1.10': [
    F('permutations', 'P1', k => { const n=at([5,6,7,8],k), r=at([2,3,2,3],k), v=Array.from({length:r},(_,i)=>n-i).reduce((a,b)=>a*b,1); return Q(String.raw`From ${n} people, assign ${r} distinct ordered roles without replacement. How many assignments are possible?`, String.raw`Roles are different, so order matters and the count is $P(${n},${r})$.`, String.raw`Multiply descending options: $${Array.from({length:r},(_,i)=>n-i).join('\cdot')}$.`, String.raw`The number of assignments is $${v}$.`); }),
    F('combinations', 'P1', k => { const n=at([5,6,7,8],k), r=at([2,3,2,3],k); return Q(String.raw`Choose a committee of ${r} from ${n} volunteers with no distinct roles. Count the committees.`, 'A committee does not change when its members are listed in a new order.', String.raw`Use $\binom{${n}}{${r}}=${n}!/[${r}!(${n-r})!]$.`, String.raw`The number of committees is $${C(n,r)}$.`); }),
    F('generalized-series', 'P1', k => { const a=at([2,3,4,5],k); return Q(String.raw`Expand $(1+${a}x)^{-1}$ through $x^2$ and state an open interval of validity.`, String.raw`Use $(1+t)^{-1}=1-t+t^2-\cdots$ with $t=${a}x$.`, String.raw`The first three terms are $1-${a}x+${a*a}x^2$.`, String.raw`The expansion is valid for $|${a}x|<1$, namely $-1/${a}<x<1/${a}$.`); }),
  ],
  'AHL 1.11': [
    F('distinct-partial', 'P1', k => { const A=at([1,2,3,4],k), B=at([2,3,4,5],k); return Q(String.raw`Decompose $(${A+B}x+${A})/[x(x+1)]$ into linear partial fractions. Include the domain.`, String.raw`Let the expression equal $A/x+B/(x+1)$ for $x\neq0,-1$.`, String.raw`Clearing denominators gives $${A+B}x+${A}=A(x+1)+Bx$, so $A=${A}$ and $B=${B}$.`, String.raw`Answer: $${A}/x+${B}/(x+1)$, for $x\neq0,-1$.`); }),
    F('repeated-partial', 'P1', k => { const A=at([1,2,3,4],k), B=at([2,3,4,5],k); return Q(String.raw`Split $(${A}x+${B})/x^2$ into terms with denominators $x$ and $x^2$.`, String.raw`For $x\neq0$, propose $C/x+D/x^2=(Cx+D)/x^2$.`, String.raw`Compare numerators: $C=${A}$ and $D=${B}$.`, String.raw`Hence $(${A}x+${B})/x^2=${A}/x+${B}/x^2$, retaining $x\neq0$.`); }),
    F('improper-partial', 'P1', k => { const a=at([1,2,3,4],k), b=at([2,3,4,5],k), c=a+b; return Q(String.raw`Divide $(x^2+${a+1}x+${c})/(x+1)$ and give the remainder term; state the excluded input.`, String.raw`Expand $(x+1)(x+${a})=x^2+${a+1}x+${a}$.`, String.raw`The remaining numerator is $${c}-${a}=${b}$.`, String.raw`Thus the quotient is $x+${a}+${b}/(x+1)$, for $x\neq-1$.`); }),
  ],
  'AHL 1.12': [
    F('complex-product', 'P1', k => { const a=at([1,2,3,4],k), b=at([2,3,4,5],k), c=at([2,1,3,2],k); return Q(String.raw`Expand $(${a}+${b}i)(${c}-i)$ in Cartesian form, where $i^2=-1$.`, String.raw`Multiply terms: real candidate $${a*c}$ and imaginary coefficient $${b*c-a}$.`, String.raw`The final product term is $-${b}i^2=+${b}$.`, String.raw`So the result is $${a*c+b}${b*c-a>=0?'+':''}${b*c-a}i$.`); }),
    F('complex-conjugate', 'P1', k => { const a=at([2,3,4,5],k), b=at([1,2,3,4],k); return Q(String.raw`For $z=${a}+${b}i$, find $\overline z$, $z\overline z$, and $|z|$.`, String.raw`The conjugate changes only the sign of the imaginary part: $\overline z=${a}-${b}i$.`, String.raw`$z\overline z=${a}^2+${b}^2=${a*a+b*b}$.`, String.raw`$|z|=\sqrt{${a*a+b*b}}$, the nonnegative square root.`); }),
    F('complex-reciprocal', 'P1', k => { const a=at([1,2,3,4],k), b=at([1,2,1,2],k); return Q(String.raw`Write $1/(${a}+${b}i)$ in $u+vi$ form and state why the denominator is nonzero.`, String.raw`Multiply by the conjugate $${a}-${b}i$ above and below.`, String.raw`The denominator is $${a}^2+${b}^2=${a*a+b*b}>0$.`, String.raw`The result is $${a}/${a*a+b*b}-(${b}/${a*a+b*b})i$.`); }),
  ],
  'AHL 1.13': [
    F('polar-quadrant', 'P1', k => { const quadrant=at([1,2,3,4],k), a=at([1,-1,-1,1],quadrant-1), b=at([1,1,-1,-1],quadrant-1), angle=at(['\\pi/4','3\\pi/4','-3\\pi/4','-\\pi/4'],quadrant-1); return Q(String.raw`Write $z=${a}${b>=0?'+':''}${b}i$ in modulus-argument form with a principal argument.`, String.raw`$|z|=\sqrt{${a*a}+${b*b}}=\sqrt2$.`, String.raw`The point $(${a},${b})$ lies in quadrant ${quadrant}, so an argument is $${angle}$.`, String.raw`Thus $z=\sqrt2e^{i(${angle})}$, equivalently $\sqrt2(\cos(${angle})+i\sin(${angle}))$.`); }),
    F('de-moivre-power', 'P1', k => { const n=at([2,3,4,6],k), m=at([3,4,2,5],k); return Q(String.raw`Let $z=${m}e^{i\pi/${n}}$. Write $z^{${n}}$ exactly in Cartesian form.`, String.raw`Raise the modulus: $|z^{${n}}|=${m}^{${n}}=${m**n}$.`, String.raw`Multiply the argument: $${n}(\pi/${n})=\pi$.`, String.raw`$z^{${n}}=${m**n}e^{i\pi}=-${m**n}+0i$.`); }),
    F('polar-multiply', 'P1', k => { const a=at([2,3,4,5],k), b=at([3,4,2,5],k), angle=at([2,3,4,6],k); return Q(String.raw`If $z=${a}e^{i\pi/${angle}}$ and $w=${b}e^{-i\pi/${angle}}$, find $zw$ in both polar and Cartesian form.`, String.raw`Multiply moduli: $${a}(${b})=${a*b}$.`, String.raw`Add arguments: $\pi/${angle}-\pi/${angle}=0$.`, String.raw`Therefore $zw=${a*b}e^{i0}=${a*b}$, a positive real number.`); }),
  ],
  'AHL 1.14': [
    F('conjugate-factor', 'P1', k => { const a=at([1,2,3,4],k), b=at([1,2,1,3],k); return Q(String.raw`A real-coefficient polynomial has root $${a}+${b}i$. Find the real monic quadratic factor forced by this information.`, String.raw`The conjugate $${a}-${b}i$ is also a root because coefficients are real.`, String.raw`Multiply $(x-${a}-${b}i)(x-${a}+${b}i)=(x-${a})^2+${b*b}$.`, String.raw`Expand to $x^2-${2*a}x+${a*a+b*b}$.`); }),
    F('roots-of-unity', 'P1', k => { const n=at([3,4,5,6],k); return Q(String.raw`List all $${n}$ distinct solutions of $z^{${n}}=1$ using a single general expression, with integer index bounds.`, String.raw`Write $1=e^{2\pi i j}$ for integer $j$, since arguments differ by full turns.`, String.raw`Divide the angle by $${n}$: $z_j=e^{2\pi i j/${n}}$.`, String.raw`Take $j=0,1,\ldots,${n-1}$; these are exactly $${n}$ distinct roots.`); }),
    F('de-moivre-square', 'P1', k => { const n=at([2,3,4,5],k); return Q(String.raw`For $z=\cos(\pi/${n})+i\sin(\pi/${n})$, express $z^2$ in trigonometric form and state its modulus.`, 'The initial modulus is one since the point lies on the unit circle.', String.raw`De Moivre doubles the argument to $2\pi/${n}$.`, String.raw`Thus $z^2=\cos(2\pi/${n})+i\sin(2\pi/${n})$ and $|z^2|=1$.`); }),
  ],
  'AHL 1.15': [
    F('induction-arithmetic', 'P1', k => { const a=at([1,2,3,4],k); return Q(String.raw`Prove by induction that $${a}+2\cdot${a}+\cdots+n\cdot${a}=\frac{${a}\,n(n+1)}{2}$ for all integers $n\geq1$.`, String.raw`Base $n=1$: the left side $${a}$ equals $\frac{${a}(1)(2)}{2}$.`, String.raw`Assume the result at $k$; adding the next term $${a}(k+1)$ gives $\frac{${a}\,k(k+1)}{2}+${a}(k+1)$.`, String.raw`Factor to $\frac{${a}(k+1)(k+2)}{2}$, the result at $k+1$; induction completes the proof.`); }),
    F('contradiction-sqrt', 'P1', k => { const prime=at([2,3,5,7],k); return Q(String.raw`Outline a contradiction proof that $\sqrt{${prime}}$ is irrational. State the lowest-terms assumption.`, String.raw`Assume $\sqrt{${prime}}=a/b$ for coprime positive integers $a,b$; then $a^2=${prime}b^2$.`, String.raw`As $${prime}$ is prime, it divides $a$, say $a=${prime}c$, giving $${prime}b^2=${prime*prime}c^2$.`, String.raw`Then $${prime}$ divides $b$ as well, contradicting coprimality; so $\sqrt{${prime}}$ is irrational.`); }),
    F('counterexample-universal', 'P1', k => { const n=at([2,3,4,5],k); return Q(String.raw`A claim says $m^2-m+${n}$ is prime for every positive integer $m$. Find a valid counterexample and explain why it refutes the claim.`, String.raw`Choose $m=${n}$, a permitted positive integer.`, String.raw`Then $m^2-m+${n}=${n*n}$, a product $${n}\cdot${n}$ with $${n}>1$.`, 'A composite instance disproves the universal prime claim; it does not decide all other inputs.'); }),
  ],
  'AHL 1.16': [
    F('linear-two-unknowns', 'P1', k => { const x=at([2,3,4,5],k), y=at([1,2,3,4],k); return Q(String.raw`Solve the system $x+y=${x+y}$ and $x-y=${x-y}$. Show elimination and check both equations.`, String.raw`Add the two equations to get $2x=${2*x}$.`, String.raw`Hence $x=${x}$ and the first equation gives $y=${x+y}-${x}=${y}$.`, String.raw`Check $${x}+${y}=${x+y}$ and $${x}-${y}=${x-y}$.`); }),
    F('linear-three-unknowns', 'P1', k => { const x=at([1,2,3,4],k), y=at([2,3,1,2],k), z=at([3,1,2,4],k); return Q(String.raw`Solve $x+y+z=${x+y+z}$, $y+z=${y+z}$ and $z=${z}$ by back-substitution.`, String.raw`The third equation immediately gives $z=${z}$.`, String.raw`Subtract it from the second: $y=${y+z}-${z}=${y}$.`, String.raw`Subtract $y+z=${y+z}$ from the first: $x=${x+y+z}-${y+z}=${x}$.`); }),
    F('system-consistency', 'P1', k => { const c=at([2,3,4,5],k), d=at([2*c,2*c+1,2*c,2*c-1],k); return Q(String.raw`Classify the solutions of $x+y=${c}$ and $2x+2y=${d}$: none, one or infinitely many. Justify without dividing by zero.`, String.raw`Twice the first left side equals the second left side for every pair.`, String.raw`Twice the first right side is $${2*c}$; compare it with $${d}$.`, d===2*c?String.raw`The equations coincide, so infinitely many pairs $(t,${c}-t)$ satisfy both.`:String.raw`They give incompatible totals ($${2*c}\neq${d}$), so there is no solution.`); }),
  ],
};
