const F=(name,paper,build)=>({name,paper,build});
const Q=(prompt,...steps)=>({prompt,steps:steps.map(text=>[1,text])});
const at=(xs,k)=>xs[k%xs.length];
const choose=(n,r)=>{let v=1;for(let i=1;i<=r;i++)v=v*(n-i+1)/i;return v;};
export const families={
 'SL 4.1':[
  F('proportional-strata','P1',k=>{const a=at([600,500,400,300],k),b=1000-a;return Q(String.raw`A school has ${a} pupils in group A and ${b} in group B. Allocate a proportional stratified random sample of 100.`,String.raw`Population total is ${a}+${b}=1000.`,String.raw`Group A receives $100(${a}/1000)=${a/10}$ places.`,String.raw`Group B receives $100(${b}/1000)=${b/10}$ places; select randomly within each group.`);}),
  F('convenience-bias','P1',k=>{const group=at(['students arriving early','students attending one club','visitors to the school website','students who answer a voluntary poll'],k);return Q(`A school surveys only ${group} about all students' sleep habits. Identify a sampling problem and suggest an improvement.`, 'The selection frame may exclude other pupils, so it need not represent the whole population.', 'A larger number from the same restricted group would not remove this selection bias.', 'Draw a random or appropriately stratified sample from the complete student roster instead.');}),
  F('systematic-sampling','P1',k=>{const N=at([200,300,400,500],k);return Q(`A roster of ${N} pupils is to supply a systematic sample of 20. State the interval and one limitation if the list has a repeating pattern.`,String.raw`The selection interval is $${N}/20=${N/20}$.`,String.raw`Choose a random starting position among the first $${N/20}$ entries, then take every $${N/20}$th.`, 'If the roster repeats a cycle matching this interval, the sample may systematically miss some types.');}),
 ],
 'SL 4.2':[
  F('histogram-density','P1',k=>{const w=at([2,4,5,10],k),f=at([12,20,25,30],k);return Q(`A histogram class has width ${w} units and frequency ${f}. Find its frequency density and explain which quantity the bar area shows.`,String.raw`Density is frequency divided by class width: $${f}/${w}=${f/w}$.`,String.raw`Bar area is width times density, $${w}(${f/w})=${f}$.`, 'Thus area, not height alone, equals frequency when class widths differ.');}),
  F('quartiles-median-halves','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Eight ordered measurements are $${a},${a+1},${a+2},${a+3},${a+4},${a+5},${a+6},${a+7}$. Using the median-of-halves convention, find $Q_1$, median, $Q_3$ and IQR.`,String.raw`Median is $(${a+3}+${a+4})/2=${a+3.5}$.`,String.raw`Lower-half median is $Q_1=${a+1.5}$ and upper-half median is $Q_3=${a+5.5}$.`,String.raw`$IQR=Q_3-Q_1=${a+5.5}-${a+1.5}=4$ units.`);}),
  F('cumulative-median','P2',k=>{const n=at([20,40,60,80],k);return Q(`A cumulative-frequency curve reaches frequency ${n} at the upper class boundary. At which cumulative frequency would you read its median, and what extra information is needed for a numerical data value?`,String.raw`The middle rank lies at cumulative frequency approximately $${n}/2=${n/2}$.`, 'Go horizontally at that frequency to the curve, then vertically to the measurement axis.', 'Without the plotted curve or class intervals, the numerical measurement cannot be determined.');}),
  F('box-plot-five-number','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`An unmodified box plot with whiskers at the extremes has minimum $${a}$, lower quartile $${a+2}$, median $${a+4}$, upper quartile $${a+7}$ and maximum $${a+10}$. Give the box endpoints, median line and interquartile range.`,String.raw`The box extends from $Q_1=${a+2}$ to $Q_3=${a+7}$; the median line is $${a+4}$.`,String.raw`Its interquartile range is $Q_3-Q_1=${a+7}-${a+2}=5$.`,String.raw`The whiskers run to minimum $${a}$ and maximum $${a+10}$ under this stated five-number summary.`);}),
 ],
 'SL 4.3':[
  F('central-tendency','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`For the four values $${a-1},${a},${a},${a+1}$ find mean, median and mode.`,String.raw`Sum $(${a-1})+${a}+${a}+${a+1}=${4*a}$, so mean is $${a}$.`,String.raw`The middle two values are both $${a}$, so median is $${a}$.`,String.raw`$${a}$ occurs twice and other values once, so the mode is $${a}$.`);}),
  F('population-variance','P1',k=>{const a=at([2,3,4,5],k);return Q(String.raw`Find population variance and standard deviation of $${a-1},${a},${a},${a+1}$.`,String.raw`Their mean is $${a}$, with deviations $-1,0,0,1$.`,String.raw`Population variance is $(1+0+0+1)/4=1/2$.`,String.raw`Population standard deviation is $\sqrt{1/2}=1/\sqrt2$, in the original units.`);}),
  F('grouped-mean','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`A grouped table has class midpoints $${a},${a+2},${a+4}$ with frequencies $1,2,1$. Estimate its mean.`, 'Use each midpoint as a representative observation, so the total frequency is four.',String.raw`Weighted sum is $${a}+2(${a+2})+${a+4}=${4*a+8}$.`,String.raw`Estimated mean is $(${4*a+8})/4=${a+2}$; true values within classes are unknown.`);}),
 ],
 'SL 4.4':[
  F('regression-y-on-x','P2',k=>{const c=at([0,1,2,3],k);return Q(`Four data pairs are (1,${1+c}), (2,${2+c}), (3,${4+c}), (4,${5+c}). Find the least-squares line predicting y from x using centered sums Sxx=5 and Sxy=7.`,String.raw`Means are $\bar x=2.5$ and $\bar y=${3+c}$.`,String.raw`Slope $b=S_{xy}/S_{xx}=7/5=1.4$.`,String.raw`Intercept is $${3+c}-1.4(2.5)=${c-0.5}$, so $\hat y=1.4x${c-0.5>=0?'+':''}${c-0.5}$.`);}),
  F('pearson-r','P2',k=>{const c=at([0,1,2,3],k);return Q(`The pairs (1,${1+c}), (2,${2+c}), (3,${4+c}), (4,${5+c}) have centered sums Sxx=5, Syy=10, Sxy=7. Calculate Pearson r and interpret its sign.`,String.raw`$r=S_{xy}/\sqrt{S_{xx}S_{yy}}=7/\sqrt{5(10)}$.`,String.raw`$r=7/\sqrt{50}\approx0.98995$.`, 'The association is strongly positive and approximately linear; correlation alone does not prove causation.');}),
  F('regression-prediction','P2',k=>{const c=at([0,1,2,3],k),x=at([1,2,3,4],k),y=1.4*x+c-0.5;return Q(String.raw`For observations with $1\leq x\leq4$, the fitted $y$ on $x$ line is $\hat y=1.4x${c-0.5>=0?'+':''}${c-0.5}$. Predict at $x=${x}$ and describe whether this is interpolation.`,String.raw`Substitute $x=${x}$ into the given regression equation.`,String.raw`The fitted prediction is $1.4(${x})${c-0.5>=0?'+':''}${c-0.5}=${y.toFixed(1)}$.`, 'The input lies in the observed range, so this is interpolation; an individual result may differ.');}),
 ],
 'SL 4.5':[
  F('fair-die-count','P1',k=>{const s=at([1,2,3,4],k);return Q(String.raw`A fair six-sided die is thrown once. Find the chance of a result greater than $${s}$, showing the equally likely outcomes.`,String.raw`The favorable results are $${Array.from({length:6-s},(_,i)=>s+1+i).join(', ')}$.`,String.raw`There are $${6-s}$ favorable results out of six equally likely faces.`,String.raw`Probability is $${6-s}/6$.`);}),
  F('at-least-one','P1',k=>{const n=at([2,3,4,5],k);return Q(String.raw`A fair coin is flipped $${n}$ independent times. Find the probability of at least one head exactly.`,String.raw`The complement is no heads, namely $${n}$ tails.`,String.raw`$P(\text{all tails})=(1/2)^{${n}}=1/${2**n}$.`,String.raw`$P(\text{at least one head})=1-1/${2**n}=(${2**n-1})/${2**n}$.`);}),
  F('expected-count','P1',k=>{const N=at([30,60,90,120],k),p=at([0.1,0.2,0.3,0.4],k);return Q(`A repeatable event has chance ${p} per trial. Over ${N} comparable trials, what is the expected number of occurrences and why is it not guaranteed?`,String.raw`Expected count equals trial number times chance: $${N}(${p})$.`,String.raw`The result is $${N*p}$ occurrences on average.`, 'Individual outcomes vary; an expected count need not be the realized count.');}),
 ],
 'SL 4.6':[
  F('union-overlap','P1',k=>{const p=at([0.1,0.15,0.2,0.25],k),union=0.5+0.4-p;return Q(`Events A and B satisfy P(A)=0.5, P(B)=0.4 and P(A intersect B)=${p}. Find P(A union B).`,String.raw`Use inclusion-exclusion $P(A\cup B)=P(A)+P(B)-P(A\cap B)$.`,String.raw`Substitute $0.5+0.4-${p}$.`,String.raw`The union probability is $${union.toFixed(2)}$, between zero and one.`);}),
  F('conditional-from-overlap','P1',k=>{const p=at([0.1,0.15,0.2,0.25],k),value=p/0.4;return Q(`Given P(B)=0.4 and P(A intersect B)=${p}, compute P(A given B). Specify the denominator.`,String.raw`Conditioning on $B$ restricts the denominator to $P(B)=0.4>0$.`,String.raw`$P(A\mid B)=P(A\cap B)/P(B)=${p}/0.4$.`,String.raw`The conditional probability is $${value.toFixed(3)}$.`);}),
  F('independence-check','P1',k=>{const p=at([0.1,0.15,0.2,0.25],k);return Q(`Let P(A)=0.5, P(B)=0.4, P(A intersect B)=${p}. Determine whether A and B are independent.`,String.raw`The independent-product target is $P(A)P(B)=0.5(0.4)=0.2$.`,String.raw`Compare the actual intersection $${p}$ with $0.2$.`,p===0.2?'They match, so the events are independent despite possibly occurring together.':'They differ, so the events are not independent.');}),
  F('mutually-exclusive','P1',k=>{const p=at([0.2,0.3,0.4,0.5],k),r=at([0.1,0.2,0.3,0.4],k);return Q(`Events A and B are mutually exclusive with P(A)=${p} and P(B)=${r}. Find P(A union B) and decide whether they are independent.`, 'Mutual exclusivity means $P(A\\cap B)=0$: they cannot happen together.',String.raw`$P(A\cup B)=${p}+${r}=${(p+r).toFixed(1)}$.`,String.raw`Since $P(A)P(B)=${(p*r).toFixed(2)}>0$ but $P(A\cap B)=0$, they are not independent.`);}),
 ],
 'SL 4.7':[
  F('mass-normalization','P1',k=>{const a=at([0,1,2,3],k);return Q(String.raw`A random variable has values $${a},${a+1},${a+2}$ with probabilities $1/4,1/2,1/4$. Check validity and find $E(X)$.`, 'All probabilities are nonnegative and their sum is $1/4+1/2+1/4=1$.',String.raw`$E(X)=(${a})/4+(${a+1})/2+(${a+2})/4$.`,String.raw`The weighted mean is $E(X)=${a+1}$.`);}),
  F('discrete-variance','P1',k=>{const a=at([0,1,2,3],k);return Q(String.raw`For values $${a},${a+1},${a+2}$ with weights $1/4,1/2,1/4$, calculate $\operatorname{Var}(X)$.`,String.raw`The mean is $${a+1}$, so deviations are $-1,0,1$.`,String.raw`$E[(X-E(X))^2]=1(1/4)+0(1/2)+1(1/4)$.`, 'Variance equals $1/2$ squared units, independent of the common shift.');}),
  F('missing-probability','P1',k=>{const a=at([1,2,3,4],k);return Q(String.raw`Probabilities of $X=${a},${a+1},${a+2}$ are $1/4,p,1/4$. Find $p$ and $E(X)$.`,String.raw`Normalize: $1/4+p+1/4=1$, so $p=1/2$.`,String.raw`$E(X)=${a}(1/4)+${a+1}(1/2)+${a+2}(1/4)$.`,String.raw`The expectation is $${a+1}$; it need not occur on every trial.`);}),
 ],
 'SL 4.8':[
  F('exactly-one-success','P1',k=>{const n=at([4,5,6,7],k);return Q(String.raw`If $X\sim B(${n},1/2)$, calculate $P(X=1)$ exactly and explain its combinatorial factor.`,String.raw`There are $\binom{${n}}1=${n}$ choices for the single successful trial.`,String.raw`Each specific pattern has probability $(1/2)^1(1/2)^{${n-1}}=1/${2**n}$.`,String.raw`Hence $P(X=1)=${n}/${2**n}$.`);}),
  F('binomial-complement','P1',k=>{const n=at([4,5,6,7],k);return Q(String.raw`For ${n} independent equally likely success/failure trials, find the chance of at least one success.`,String.raw`The complement is zero successes with probability $(1/2)^{${n}}$.`,String.raw`Thus $P(X\geq1)=1-(1/2)^{${n}}$.`,String.raw`The exact fraction is $(${2**n-1})/${2**n}$.`);}),
  F('binomial-moments','P1',k=>{const n=at([4,6,8,10],k);return Q(String.raw`For $X\sim B(${n},1/2)$, find mean and variance, stating the binomial assumptions.`, 'Assume a fixed number of independent trials with constant success chance $1/2$.',String.raw`$E(X)=np=${n}(1/2)=${n/2}$.`,String.raw`$\operatorname{Var}(X)=np(1-p)=${n}(1/2)(1/2)=${n/4}$.`);}),
 ],
 'SL 4.9':[
  F('normal-center','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k);return Q(String.raw`If $X$ is normally distributed with mean $${mu}$ and standard deviation $${sigma}$, find $P(X>${mu})$.`,String.raw`The normal curve is symmetric about its mean $${mu}$.`,String.raw`Half its total area lies above $${mu}$.`, 'The probability is $0.5$; an exact single point has zero continuous probability.');}),
  F('one-sigma-tail','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k),x=mu+sigma;return Q(String.raw`Let $X$ be normal with mean $${mu}$ and standard deviation $${sigma}$. Estimate $P(X>${x})$ using $P(Z<1)\approx0.8413$.`,String.raw`$z=(${x}-${mu})/${sigma}=1$.`,String.raw`The upper tail is $1-P(Z<1)\approx1-0.8413$.`, String.raw`So $P(X>${x})\approx0.1587$, an area under the density curve.`);}),
  F('symmetric-normal-interval','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k);return Q(String.raw`If $X$ is normal with mean $${mu}$ and deviation $${sigma}$, estimate $P(${mu-sigma}<X<${mu+sigma})$ using $P(Z<1)\approx0.8413$.`,String.raw`The endpoints standardize to $z=-1$ and $z=1$.`,String.raw`By symmetry $P(Z<-1)\approx1-0.8413=0.1587$.`,String.raw`Central probability $\approx0.8413-0.1587=0.6826$; rounding of the supplied table value affects the last digit.`);}),
 ],
 'SL 4.10':[
  F('regression-x-on-y','P2',k=>{const c=at([0,1,2,3],k);return Q(`Pairs (1,${1+c}), (2,${2+c}), (3,${4+c}), (4,${5+c}) have Sxy=7 and Syy=10. Find the regression of x on y.`,String.raw`Means are $\bar x=2.5$ and $\bar y=${3+c}$.`,String.raw`The slope predicting $x$ from $y$ is $S_{xy}/S_{yy}=7/10=0.7$.`,String.raw`Thus $\hat x=2.5+0.7(y-${3+c})$.`);}),
  F('compare-regressions','P2',k=>{const c=at([0,1,2,3],k);return Q(`For pairs (1,${1+c}), (2,${2+c}), (3,${4+c}), (4,${5+c}) with Sxx=5, Syy=10 and Sxy=7, compare both regression slopes. Is either the reciprocal of the other?`,String.raw`Slope of $y$ on $x$ is $S_{xy}/S_{xx}=7/5=1.4$.`,String.raw`Slope of $x$ on $y$ is $S_{xy}/S_{yy}=7/10=0.7$.`, 'Their product is $0.98$, not $1$, so they are not reciprocal slopes.');}),
  F('predict-x-from-y','P2',k=>{const c=at([0,1,2,3],k),t=at([1,2,3,4],k),y=3+c+t,x=2.5+0.7*t;return Q(String.raw`A fitted line is $\hat x=2.5+0.7(y-${3+c})$. Predict $x$ at $y=${y}$ and name the predicted variable.`,String.raw`Compute centered input $y-${3+c}=${t}$.`,String.raw`$\hat x=2.5+0.7(${t})=${x.toFixed(1)}$.`, 'This line predicts $x$, not $y$; using the reverse regression would give a different estimate.');}),
 ],
 'SL 4.11':[
  F('table-conditional','P1',k=>{const both=at([10,12,15,20],k);return Q(`In a group of 100, 40 belong to A, 25 to B, and ${both} to both. Find P(A given B).`,String.raw`Within event $B$ there are $25$ people, of whom $${both}$ also belong to $A$.`,String.raw`$P(A\mid B)=P(A\cap B)/P(B)=${both}/25$.`,String.raw`This is $${(both/25).toFixed(2)}$; the denominator is not all 100 people.`);}),
  F('table-independence','P1',k=>{const both=at([10,12,15,20],k);return Q(`Among 100 people, 40 belong to A and 25 to B, with ${both} in both. Test independence of A and B.`,String.raw`$P(A)P(B)=(40/100)(25/100)=0.10$.`,String.raw`The observed joint probability is $P(A\cap B)=${both}/100=${(both/100).toFixed(2)}$.`,both===10?'Both values agree, so A and B are independent in this data model.':'The values differ, so A and B are not independent in this data model.');}),
  F('reverse-conditional','P1',k=>{const both=at([10,12,15,20],k);return Q(`Out of 100, 40 belong to A, 25 to B and ${both} to both. Compare P(A given B) with P(B given A).`,String.raw`$P(A\mid B)=${both}/25=${(both/25).toFixed(2)}$.`,String.raw`$P(B\mid A)=${both}/40=${(both/40).toFixed(3)}$.`, 'The two probabilities condition on different populations, so equality is not expected.');}),
 ],
 'SL 4.12':[
  F('z-score','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k),z=at([1,2,-1,-2],k),x=mu+z*sigma;return Q(String.raw`A normal model has mean $${mu}$ and standard deviation $${sigma}$. Find the z-score of $x=${x}$.`,String.raw`Use $z=(x-\mu)/\sigma$.`,String.raw`$z=(${x}-${mu})/${sigma}=${z}$.`,String.raw`The value lies $${Math.abs(z)}$ standard deviation(s) ${z<0?'below':'above'} the mean.`);}),
  F('inverse-normal-z','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k),z=at([1,2,-1,-2],k);return Q(String.raw`A normal variable has $\mu=${mu}$ and $\sigma=${sigma}$. Find the raw cutoff corresponding to $z=${z}$.`,String.raw`Rearrange $z=(x-\mu)/\sigma$ as $x=\mu+z\sigma$.`,String.raw`Substitute $x=${mu}+(${z})(${sigma})$.`,String.raw`The cutoff is $x=${mu+z*sigma}$ in the original units.`);}),
  F('find-sigma-two-percentiles','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k);return Q(String.raw`A normal variable has mean $${mu}$; a value $${mu+sigma}$ has $z=1$. Determine its standard deviation and explain why it is positive.`,String.raw`$z=(x-\mu)/\sigma$, so $1=(${mu+sigma}-${mu})/\sigma$.`,String.raw`Thus $\sigma=${mu+sigma}-${mu}=${sigma}$.`, 'Standard deviation is a positive scale; a negative solution would not describe a normal model.');}),
  F('recover-mean-and-sigma','P2',k=>{const mu=at([40,50,60,70],k),sigma=at([5,10,15,20],k),x1=mu+sigma,x2=mu+2*sigma;return Q(String.raw`For a normal model, a value $${x1}$ has $z=1$ and a value $${x2}$ has $z=2$. Find both mean $\mu$ and standard deviation $\sigma$.`,String.raw`Standardization gives $${x1}=\mu+\sigma$ and $${x2}=\mu+2\sigma$.`,String.raw`Subtract to find $\sigma=${x2}-${x1}=${sigma}>0$.`,String.raw`Then $\mu=${x1}-${sigma}=${mu}$. Reinsert both values to check the given z-scores.`);}),
 ],
 'AHL 4.13':[
  F('medical-bayes','P2',k=>{const denom=at([10,20,50,100],k),p=1/denom,truth=p*.9,falsePos=(1-p)*.1,posterior=truth/(truth+falsePos);return Q(`A condition affects 1 in ${denom}. A test has sensitivity 0.9 and specificity 0.9. Estimate P(condition given positive) to four decimals.`,String.raw`$P(\text{condition and +})=(1/${denom})(0.9)=${truth.toFixed(5)}$.`,String.raw`$P(\text{no condition and +})=(1-1/${denom})(0.1)=${falsePos.toFixed(5)}$.`,String.raw`Posterior is ${truth.toFixed(5)}/(${truth.toFixed(5)}+${falsePos.toFixed(5)}) $\approx${posterior.toFixed(4)}$.`);}),
  F('two-boxes-posterior','P1',k=>{const a=at([1,2,3,4],k);return Q(`A box is chosen uniformly from two boxes. Box A has ${a} red and 1 blue token; Box B has 1 red and ${a} blue tokens. Given a red draw, find P(box A).`,String.raw`$P(A)=P(B)=1/2$, $P(R\mid A)=${a}/${a+1}$ and $P(R\mid B)=1/${a+1}$.`,String.raw`$P(R)=\tfrac12(${a}/${a+1})+\tfrac12(1/${a+1})=1/2$.`,String.raw`Bayes gives $P(A\mid R)=\tfrac12(${a}/${a+1})/(1/2)=${a}/${a+1}$.`);}),
  F('base-rate-shift','P2',k=>{const denom=at([10,20,50,100],k),p=1/denom;return Q(`A test correctly identifies a condition 90% of the time and has a 10% false-positive rate. If prevalence is 1/${denom}, set up the denominator P(positive) before using Bayes.`,String.raw`True positives contribute $(1/${denom})(0.9)=${(p*.9).toFixed(5)}$.`,String.raw`False positives contribute $(1-1/${denom})(0.1)=${((1-p)*.1).toFixed(5)}$.`,String.raw`Total evidence probability is $${(p*.9+(1-p)*.1).toFixed(5)}$, not just the true-positive branch.`);}),
 ],
 'AHL 4.14':[
  F('linear-transform-moments','P1',k=>{const m=at([1,2,3,4],k),a=at([2,3,4,5],k),b=at([1,2,3,4],k);return Q(String.raw`If $E(X)=${m}$ and $\operatorname{Var}(X)=4$, find $E(${a}X+${b})$ and its variance.`,String.raw`Expectation is linear: $E(${a}X+${b})=${a}(${m})+${b}=${a*m+b}$.`,String.raw`A shift does not change spread; scaling by $${a}$ multiplies variance by $${a*a}$.`,String.raw`So $\operatorname{Var}(${a}X+${b})=${a*a}(4)=${4*a*a}$.`);}),
  F('uniform-continuous','P1',k=>{const L=at([2,4,6,8],k);return Q(String.raw`A continuous variable is uniform on $0<x<${L}$. Give its density, mean and variance.`,String.raw`Density is $f(x)=1/${L}$ on $(0,${L})$ and zero elsewhere, integrating to one.`,String.raw`$E(X)=\int_0^{${L}}x/${L}\,dx=${L/2}$.`,String.raw`$\operatorname{Var}(X)=${L}^2/12=${L*L}/12$, in squared units.`);}),
  F('linear-density','P2',k=>{const L=at([3,6,9,12],k),density=2/(L*L);return Q(String.raw`A density is $f(x)=cx$ on $0<x<${L}$, zero elsewhere. Find $c$ and $E(X)$.`,String.raw`Normalization $1=\int_0^{${L}}cx\,dx=\frac{${L*L}c}{2}$, so $c=2/${L*L}$.`,String.raw`$E(X)=\int_0^{${L}}x(2x/${L*L})\,dx=\frac{2(${L})^3}{3(${L*L})}$.`,String.raw`Thus $E(X)=\frac{2(${L})}{3}=${2*L/3}$, within the support.`);}),
 ],
};
